import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {ArrowLeft,RefreshCw,User,BriefcaseBusiness,Building2,ReceiptText,LockKeyhole,WalletCards,CheckCircle2,Clock3,AlertTriangle} from 'lucide-react';

export const AdminTraceabilityWindow:React.FC<{serviceId:string;onClose:()=>void}>=({serviceId,onClose})=>{
 const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setData(await api.get<any>(`/admin-panel/trace/${serviceId}`))}catch(e:any){setError(e?.message||'No se pudo cargar la trazabilidad.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[serviceId]);
 const money=(n:any)=>`RD$ ${Number(n||0).toLocaleString('es-DO',{minimumFractionDigits:2})}`;
 const stages=[['CONTRATACIÓN','Cliente y trabajador quedan vinculados al servicio.'],['DEPÓSITO','Se identifica banco, cuenta, voucher y monto.'],['CUSTODIA','El dinero queda retenido hasta completar el trabajo.'],['LIQUIDACIÓN','Se separa la comisión SERVIYA y el pago del trabajador.'],['RETIRO','El trabajador retira usando su cuenta bancaria registrada.']];
 return <div className="fixed inset-0 z-[100] bg-slate-950/70 p-0 sm:p-4 overflow-auto"><div className="min-h-full sm:min-h-0 sm:max-w-5xl sm:mx-auto sm:my-4 bg-white sm:rounded-3xl shadow-2xl overflow-hidden">
  <header className="bg-red-950 text-white p-5 flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-red-200">Administración SERVIYA</p><h2 className="text-xl font-black mt-1">Trazabilidad del dinero</h2><p className="text-xs text-red-200 mt-1">Servicio: {serviceId}</p></div><button onClick={onClose} className="px-3 py-2 rounded-xl bg-white/10 font-bold text-sm inline-flex items-center gap-2"><ArrowLeft className="w-4 h-4"/> Volver</button></header>
  <div className="p-5 sm:p-7 space-y-5">{loading?<div className="py-16 text-center text-slate-500"><RefreshCw className="w-7 h-7 animate-spin mx-auto mb-3"/>Cargando trazabilidad...</div>:error?<div className="p-5 rounded-2xl bg-red-50 border border-red-200 text-red-700 font-bold"><AlertTriangle className="w-5 h-5 inline mr-2"/>{error}<button onClick={load} className="block mt-3 px-4 py-2 rounded-xl bg-red-700 text-white text-sm">Reintentar</button></div>:data&&<>
   <div className="grid sm:grid-cols-3 gap-3"><div className="p-4 rounded-2xl bg-slate-50 border"><p className="text-[10px] font-black uppercase text-slate-400">Cliente</p><p className="font-black mt-1">{data.identity?.client_name||'—'}</p><p className="text-xs text-slate-500">{data.identity?.client_id}</p></div><div className="p-4 rounded-2xl bg-slate-50 border"><p className="text-[10px] font-black uppercase text-slate-400">Trabajador destinatario</p><p className="font-black mt-1">{data.identity?.worker_name||'—'}</p><p className="text-xs text-slate-500">{data.identity?.worker_id}</p></div><div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200"><p className="text-[10px] font-black uppercase text-emerald-600">Total del servicio</p><p className="text-xl font-black mt-1">{money(data.money?.total_rd)}</p><p className="text-xs text-emerald-700">Custodia: {data.escrow?.status||'—'}</p></div></div>
   <section className="p-5 rounded-3xl border-2 border-blue-100 bg-blue-50/40"><div className="flex items-center gap-2 mb-5"><Clock3 className="w-5 h-5 text-blue-600"/><h3 className="font-black">Recorrido de la operación</h3></div><div className="grid sm:grid-cols-5 gap-3">{stages.map(([name,desc],i)=><div key={name} className="relative bg-white p-3 rounded-2xl border"><div className="w-8 h-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-black text-sm">{i+1}</div><p className="font-black text-xs mt-2">{name}</p><p className="text-[10px] text-slate-500 mt-1">{desc}</p></div>)}</div></section>
   <div className="grid lg:grid-cols-2 gap-4"><section className="p-5 rounded-3xl border"><div className="flex items-center gap-2 mb-4"><BriefcaseBusiness className="w-5 h-5 text-blue-600"/><h3 className="font-black">Servicio</h3></div><p className="font-black">{data.service?.title||'—'}</p><p className="text-sm text-slate-500 mt-1">Estado: {data.service?.status||'—'}</p><p className="text-sm font-bold mt-2">Precio acordado: {money(data.service?.agreed_price_rd)}</p></section>
   <section className="p-5 rounded-3xl border"><div className="flex items-center gap-2 mb-4"><Building2 className="w-5 h-5 text-blue-600"/><h3 className="font-black">Origen del depósito</h3></div><p className="font-black">{data.bank?.bank_name||'Banco no registrado'}</p><p className="text-sm text-slate-500">Cuenta: {data.bank?.account_number||'—'}</p><p className="text-sm text-slate-500">Tipo: {data.bank?.account_type||'—'}</p><p className="text-sm font-bold mt-2">Voucher: {data.escrow?.voucher_received?<span className="text-emerald-700">RECIBIDO</span>:<span className="text-orange-700">PENDIENTE</span>}</p></section></div>
   <section className="p-5 rounded-3xl border bg-slate-50"><div className="flex items-center gap-2 mb-4"><WalletCards className="w-5 h-5 text-emerald-600"/><h3 className="font-black">Destino del dinero</h3></div><div className="grid sm:grid-cols-3 gap-3"><div className="bg-white rounded-2xl border p-4"><p className="text-[10px] font-black text-slate-400">TOTAL</p><p className="font-black text-lg">{money(data.money?.total_rd)}</p></div><div className="bg-white rounded-2xl border p-4"><p className="text-[10px] font-black text-slate-400">COMISIÓN SERVIYA</p><p className="font-black text-lg">{money(data.money?.commission_rd)}</p></div><div className="bg-white rounded-2xl border p-4"><p className="text-[10px] font-black text-slate-400">TRABAJADOR RECIBE</p><p className="font-black text-lg text-emerald-700">{money(data.money?.worker_payout_rd)}</p></div></div><div className="mt-4 p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-sm font-bold text-emerald-800"><CheckCircle2 className="w-4 h-4 inline mr-2"/>El destinatario del pago está fijado al trabajador registrado en esta Custodia. No se elige otro trabajador al retirar.</div></section>
   <section className="p-5 rounded-3xl border"><div className="flex items-center gap-2 mb-4"><ReceiptText className="w-5 h-5 text-orange-600"/><h3 className="font-black">Referencia y movimientos</h3></div><p className="text-xs text-slate-500 mb-3">ID de trazabilidad: <span className="font-mono text-slate-700">{data.trace_id}</span></p>{(data.transactions||[]).length===0?<p className="text-sm text-slate-400">No hay movimientos adicionales registrados.</p>:(data.transactions||[]).map((t:any,i:number)=><div key={i} className="p-3 rounded-xl bg-slate-50 border mb-2 flex justify-between gap-3"><div><b>{t.type||'Movimiento'}</b><p className="text-[11px] text-slate-500 font-mono">{t.reference_code||'Sin referencia'}</p></div><div className="text-right"><b>{money(t.amount)}</b><p className="text-[11px] text-slate-500">{t.status||'—'}</p></div></div>)}</section>
   <div className="flex justify-end"><button onClick={load} className="px-4 py-3 rounded-xl border bg-white font-black text-sm inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/> Actualizar trazabilidad</button></div>
  </>}</div></div></div>;
};
