import React,{useEffect,useState} from 'react';
import {Activity,RefreshCw,ArrowDownLeft,ShieldCheck} from 'lucide-react';
import {api} from '../services/api';

type Tx={id:any;user_id?:string;user_name?:string;amount?:number;type?:string;status?:string;reference_code?:string;created_at?:string};
type Audit={id:any;admin_id?:string;action?:string;resource?:string;target_id?:any;details?:string;timestamp?:string};

export const AdminGlobalActivity:React.FC=()=>{
 const [tx,setTx]=useState<Tx[]>([]); const [audit,setAudit]=useState<Audit[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const [t,a]=await Promise.allSettled([api.get<any>('/admin-panel/transactions'),api.get<any>('/admin-panel/audit')]);let failed=false;if(t.status==='fulfilled')setTx(t.value?.transactions||[]);else failed=true;if(a.status==='fulfilled')setAudit(a.value?.admin_audit||[]);else failed=true;if(failed)setError('Algunas fuentes de actividad no respondieron. Los datos que sí están conectados se mantienen visibles.');setLoading(false)};
 useEffect(()=>{load()},[]);
 return <section className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center"><Activity className="w-5 h-5"/></div><div><h3 className="font-black text-lg">Movimientos globales</h3><p className="text-xs text-slate-500">Super Administrador: movimientos financieros y acciones de todas las áreas.</p></div></div><button onClick={load} disabled={loading} className="px-3 py-2 rounded-xl border bg-white text-xs font-black inline-flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> Actualizar</button></div>{error&&<div className="mx-5 mt-4 p-3 rounded-xl bg-amber-50 border border-amber-200 text-amber-800 text-xs font-bold">{error}</div>}<div className="grid lg:grid-cols-2 gap-4 p-5"><div><div className="flex items-center gap-2 mb-3"><ArrowDownLeft className="w-4 h-4 text-emerald-600"/><h4 className="font-black text-sm">Movimientos financieros</h4></div>{tx.length===0?<p className="text-xs text-slate-400 py-6 text-center">No hay movimientos registrados.</p>:<div className="space-y-2 max-h-[420px] overflow-y-auto">{tx.map(x=><div key={`tx-${x.id}`} className="p-3 rounded-xl border bg-slate-50"><div className="flex justify-between gap-3"><b className="text-xs">{x.type||'MOVIMIENTO'}</b><span className="text-xs font-black">RD$ {Number(x.amount||0).toLocaleString()}</span></div><p className="text-[10px] text-slate-500 mt-1">{x.user_name||x.user_id||'Usuario'} • {x.status||'—'}</p><p className="text-[10px] text-slate-400 mt-1">{x.reference_code||'Sin referencia'} • {x.created_at?new Date(x.created_at).toLocaleString():'—'}</p></div>)}</div>}</div><div><div className="flex items-center gap-2 mb-3"><ShieldCheck className="w-4 h-4 text-blue-600"/><h4 className="font-black text-sm">Acciones administrativas</h4></div>{audit.length===0?<p className="text-xs text-slate-400 py-6 text-center">No hay acciones administrativas registradas.</p>:<div className="space-y-2 max-h-[420px] overflow-y-auto">{audit.map(x=><div key={`audit-${x.id}`} className="p-3 rounded-xl border bg-slate-50"><div className="flex justify-between gap-3"><b className="text-xs">{x.action||'ACCIÓN'}</b><span className="text-[10px] font-black text-slate-500">{x.resource||'—'}</span></div><p className="text-[10px] text-slate-500 mt-1">Administrador: {x.admin_id||'—'} • Objetivo: {x.target_id??'—'}</p><p className="text-[10px] text-slate-600 mt-1">{x.details||'Sin detalle'}</p><p className="text-[10px] text-slate-400 mt-1">{x.timestamp?new Date(x.timestamp).toLocaleString():'—'}</p></div>)}</div>}</div></div></section>;
};
