import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {AdminRolesPanel} from './AdminRolesPanel';
import {AdminUsersModal} from './AdminUsersModal';
import {RefreshCw,Users,Wallet,Banknote,FileCheck2,Building2,CheckCircle2,ShieldCheck} from 'lucide-react';

type Row=Record<string,any>;
type Bank={id:number;bank_name:string;account_number:string;account_type?:string;account_holder?:string;is_active?:boolean;is_primary?:boolean};
type AdminUser={id:string;first_name:string;last_name:string;email:string;phone:string;role:string;is_active:boolean;is_verified:boolean};

export const AdminPanelV2:React.FC=()=>{
 const [stats,setStats]=useState<any>({});const [banks,setBanks]=useState<Bank[]>([]);const [deposits,setDeposits]=useState<Row[]>([]);const [releases,setReleases]=useState<Row[]>([]);const [users,setUsers]=useState<AdminUser[]>([]);const [verifications,setVerifications]=useState<Row[]>([]);const [withdrawals,setWithdrawals]=useState<Row[]>([]);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const [showUsers,setShowUsers]=useState(false);
 const [bankName,setBankName]=useState('');const [number,setNumber]=useState('');const [type,setType]=useState('CORRIENTE');const [holder,setHolder]=useState('SERVIYA DOMINICANA SRL');const [rnc,setRnc]=useState('');
 const flash=(ok?:string,bad?:any)=>{setMessage(ok||'');setError(bad?.message||'')};
 const load=async()=>{setLoading(true);setError('');const results=await Promise.allSettled([api.get<any>('/admin/stats'),api.get<any>('/admin/bank-accounts'),api.get<any>('/admin-panel/escrows/pending-deposits'),api.get<any>('/admin-panel/escrows/pending-release'),api.get<any>('/admin/users'),api.get<any>('/admin/verifications'),api.get<any>('/admin/withdrawals')]);const [s,b,d,r,u,v,w]=results;const failed:number[]=[];if(s.status==='fulfilled')setStats(s.value?.stats||{});else failed.push(1);if(b.status==='fulfilled')setBanks(b.value?.bank_accounts||[]);else failed.push(2);if(d.status==='fulfilled')setDeposits(d.value?.pending_deposits||[]);else failed.push(3);if(r.status==='fulfilled')setReleases(r.value?.pending_releases||[]);else failed.push(4);if(u.status==='fulfilled')setUsers(u.value?.users||[]);else failed.push(5);if(v.status==='fulfilled')setVerifications((v.value?.verifications||[]).filter((x:any)=>x.status==='PENDIENTE'));else failed.push(6);if(w.status==='fulfilled')setWithdrawals((w.value?.withdrawals||[]).filter((x:any)=>x.status==='PENDIENTE'));else failed.push(7);if(failed.length)setError(`${failed.length} sección${failed.length>1?'es':''} administrativa${failed.length>1?'s':''} no respondió. Las demás siguen conectadas.`);setLoading(false)};
 useEffect(()=>{load()},[]);
 const act=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setMessage('');setError('');try{const r=await fn();flash(r?.message||'Acción realizada correctamente.');await load()}catch(e:any){flash('',e)}finally{setBusy('')}};
 const addBank=async(e:React.FormEvent)=>{e.preventDefault();if(!bankName.trim())return flash('',{message:'Escribe el nombre del banco.'});if(!number.trim())return flash('',{message:'Escribe el número de cuenta.'});await act('add-bank',async()=>{const r=await api.post('/admin/bank-accounts',{bank_name:bankName.trim(),account_number:number.trim(),account_type:type,account_holder:holder.trim(),rnc_cedula:rnc.trim(),is_active:true,is_primary:banks.length===0});setBankName('');setNumber('');setRnc('');return r})};
 return <div className="space-y-5 pb-12 max-w-7xl mx-auto">
  <header className="bg-slate-950 text-white p-5 sm:p-7 rounded-3xl shadow-xl flex items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-full text-xs font-black"><ShieldCheck className="w-4 h-4"/> ADMINISTRACIÓN SERVIYA</div><h1 className="text-2xl sm:text-3xl font-black mt-2">Panel central</h1><p className="text-sm text-slate-300 mt-1">Un solo administrador para controlar toda la plataforma.</p></div><button onClick={load} disabled={loading} className="bg-white text-slate-950 rounded-xl px-4 py-3 font-black text-sm inline-flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Actualizar</button></header>
  {message&&<div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold">✓ {message}</div>}{error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">⚠ {error}<button onClick={load} className="ml-3 underline">Reintentar</button></div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Usuarios" value={stats.total_users||0} icon={<Users className="w-5 h-5"/>}/><Metric label="En Custodia" value={`RD$ ${Number(stats.escrow_held_rd||0).toLocaleString()}`} icon={<Wallet className="w-5 h-5"/>}/><Metric label="Retiros pendientes" value={stats.pending_withdrawals||0} icon={<Banknote className="w-5 h-5"/>}/><Metric label="Verificaciones" value={stats.pending_verifications||0} icon={<FileCheck2 className="w-5 h-5"/>}/></div>
  <Section title={`Depósitos pendientes de verificación (${deposits.length})`} icon={<Building2 className="w-5 h-5"/>} help="Voucher recibido → Administración verifica → Custodia.">{deposits.length?deposits.map(r=><RowCard key={String(r.id||r.service_id)} title={r.display_title||r.title||'Depósito'} text={`${r.bank_name||'Banco'} • RD$ ${Number(r.total_amount_rd||0).toLocaleString()} • ${r.voucher_url?'Voucher recibido':'Sin voucher'}`} actions={<><button disabled={!r.voucher_url||!!busy} onClick={()=>act('dep'+r.service_id,()=>api.post(`/admin-panel/escrows/${r.service_id}/approve-deposit`,{notes:'Verificado por Administración'}))} className="btn-green">Confirmar y poner en Custodia</button><button disabled={!!busy} onClick={()=>act('rej'+r.service_id,()=>api.post(`/admin-panel/escrows/${r.service_id}/reject-deposit`,{notes:'Rechazado por Administración'}))} className="btn-red">Rechazar</button></>}/>):<Empty text="No hay depósitos pendientes."/>}</Section>
  <Section title={`Liberaciones pendientes (${releases.length})`} icon={<CheckCircle2 className="w-5 h-5"/>} help="Solo llegan aquí los trabajos que el cliente ya aprobó.">{releases.length?releases.map(r=><RowCard key={String(r.id||r.service_id)} title={r.display_title||r.title||'Servicio'} text={`Trabajador: ${r.worker_name||r.worker_id||'—'} • RD$ ${Number(r.amount_rd||0).toLocaleString()} • Recibe RD$ ${Number(r.payout_rd||0).toLocaleString()}`} actions={<button disabled={busy===String(r.service_id)} onClick={()=>act('rel'+r.service_id,()=>api.post(`/admin-panel/escrows/${r.service_id}/approve-release`,{notes:'Liberación confirmada por Administración'}))} className="btn-green">{busy===String(r.service_id)?'Liberando…':'Liberar custodia y pagar al trabajador'}</button>}/>):<Empty text="No hay liberaciones pendientes."/>}</Section>
  <Section title={`Retiros pendientes (${withdrawals.length})`} icon={<Banknote className="w-5 h-5"/>} help="Solo los trabajadores pueden solicitar retiros.">{withdrawals.length?withdrawals.map(r=><RowCard key={String(r.id)} title={`RD$ ${Number(r.amount_rd||r.amount||0).toLocaleString()}`} text={`${r.bank_name||r.method||'Banco'} • cuenta terminada en •••• ${String(r.account_number||'').slice(-4)}`} actions={<><button onClick={()=>act('wd'+r.id,()=>api.patch(`/admin/withdrawals/${r.id}`,{status:'COMPLETADO',notes:'Pago confirmado por Administración'}))} className="btn-green">Marcar pagado</button><button onClick={()=>act('wr'+r.id,()=>api.patch(`/admin/withdrawals/${r.id}`,{status:'RECHAZADO',notes:'Retiro rechazado por Administración'}))} className="btn-red">Rechazar</button></>}/>):<Empty text="No hay retiros pendientes."/>}</Section>
  <Section title={`Verificaciones pendientes (${verifications.length})`} icon={<FileCheck2 className="w-5 h-5"/>} help="Solo se muestran documentos realmente pendientes.">{verifications.length?verifications.map(r=><RowCard key={String(r.id)} title={`Trabajador ${r.user_id||r.worker_id||'—'}`} text={`${r.document_type||'Documento'} • PENDIENTE`} actions={<><button onClick={()=>act('v'+r.id,()=>api.post(`/admin/verifications/${r.id}/approve`))} className="btn-green">Aprobar</button><button onClick={()=>act('vr'+r.id,()=>api.patch(`/admin/verifications/${r.id}`,{status:'RECHAZADO'}))} className="btn-red">Rechazar</button></>}/>):<Empty text="No hay verificaciones pendientes."/>}</Section>
  <Section title="Cuentas bancarias de SERVIYA" icon={<Building2 className="w-5 h-5"/>} help="Puedes registrar BHD, Popular, Banreservas o cualquier otro banco que SERVIYA utilice."><form onSubmit={addBank} className="grid sm:grid-cols-2 lg:grid-cols-5 gap-2 p-4 rounded-2xl bg-slate-50 border"><input required value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="Nombre del banco" className="p-3 rounded-xl border bg-white text-sm"/><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="Número de cuenta" className="p-3 rounded-xl border bg-white text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="p-3 rounded-xl border bg-white text-sm"><option>CORRIENTE</option><option>AHORRO</option></select><input value={holder} onChange={e=>setHolder(e.target.value)} placeholder="Titular" className="p-3 rounded-xl border bg-white text-sm"/><button disabled={busy==='add-bank'} className="bg-blue-600 text-white rounded-xl px-4 py-3 font-black text-sm">+ Agregar cuenta</button></form><div className="mt-3 space-y-2">{banks.map(b=><div key={b.id} className="p-3 rounded-xl border bg-slate-50 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>{b.bank_name}</b><span className="font-mono text-xs ml-2">{b.account_number}</span><p className="text-[10px] text-slate-500">{b.account_type} • {b.account_holder} • {b.is_active?'ACTIVA':'INACTIVA'} {b.is_primary?'• PRINCIPAL':''}</p></div><div className="flex gap-2"><button onClick={()=>act('ba'+b.id,()=>api.put(`/admin/bank-accounts/${b.id}`,{is_active:!b.is_active}))} className="btn-gray">{b.is_active?'Desactivar':'Activar'}</button>{!b.is_primary&&<button onClick={()=>act('bp'+b.id,()=>api.put(`/admin/bank-accounts/${b.id}`,{is_primary:true}))} className="btn-gray">Hacer principal</button>}</div></div>)}</div></Section>
  <Section title={`Usuarios (${users.length})`} icon={<Users className="w-5 h-5"/>} help="Gestión general de clientes, trabajadores y administradores."><button onClick={()=>setShowUsers(true)} className="bg-blue-600 text-white px-4 py-3 rounded-xl text-sm font-black">Gestionar usuarios</button></Section>
  <AdminRolesPanel/>
  {showUsers&&<AdminUsersModal users={users} onClose={()=>setShowUsers(false)} onReload={load}/>} 
  <style>{`.btn-green{background:#059669;color:white;padding:.6rem .8rem;border-radius:.7rem;font-size:.72rem;font-weight:800}.btn-red{background:#fff1f2;color:#be123c;border:1px solid #fecdd3;padding:.6rem .8rem;border-radius:.7rem;font-size:.72rem;font-weight:800}.btn-gray{background:white;border:1px solid #cbd5e1;padding:.55rem .7rem;border-radius:.65rem;font-size:.7rem;font-weight:800}`}</style>
 </div>;
};

const Section:React.FC<{title:string;icon:React.ReactNode;help:string;children:React.ReactNode}>=({title,icon,help,children})=><section className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm"><div className="flex items-start gap-2 mb-4"><div className="text-blue-600 mt-0.5">{icon}</div><div><h2 className="font-black text-lg">{title}</h2><p className="text-xs text-slate-500 mt-1">{help}</p></div></div>{children}</section>;
const RowCard:React.FC<{title:string;text:string;actions:React.ReactNode}>=({title,text,actions})=><div className="p-4 rounded-2xl border bg-slate-50 mb-2 flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><b>{title}</b><p className="text-xs text-slate-500 mt-1">{text}</p></div><div className="flex flex-wrap gap-2">{actions}</div></div>;
const Empty:React.FC<{text:string}>=({text})=><p className="text-sm text-slate-400 text-center py-6">{text}</p>;
const Metric:React.FC<{label:string;value:any;icon:React.ReactNode}>=({label,value,icon})=><div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm"><div className="text-blue-600">{icon}</div><p className="text-[10px] font-black uppercase text-slate-400 mt-3">{label}</p><p className="text-xl font-black mt-1">{value}</p></div>;
