import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {AdminRolesPanel} from './AdminRolesPanel';
import {AdminUsersModal} from './AdminUsersModal';
import {AdminVoucherVerificationWindow} from './AdminVoucherVerificationWindow';
import {AdminTraceabilityWindow} from './AdminTraceabilityWindow';
import {ShieldCheck,RefreshCw,Users,Wallet,Banknote,FileCheck2,Settings,Eye,Building2,ReceiptText,Route,CheckCircle} from 'lucide-react';

type Bank={id:number;bank_name:string;account_number:string;account_type?:string;account_holder?:string;rnc_cedula?:string;is_active?:boolean;is_primary?:boolean};
type WorkerBankAccount={id:number;worker_id:string;worker_name?:string;worker_email?:string;bank_name:string;account_number:string;account_type:string;account_holder_name:string;account_holder_cedula:string;is_active:boolean;updated_at?:string};
type AdminUser={id:string;first_name:string;last_name:string;email:string;phone:string;role:string;is_active:boolean;is_verified:boolean};
const BANKS=['BHD','Banreservas','Banco Popular'];

export const AdminPanelV2:React.FC=()=>{
 const [stats,setStats]=useState<any>({}); const [banks,setBanks]=useState<Bank[]>([]); const [workerBankAccounts,setWorkerBankAccounts]=useState<WorkerBankAccount[]>([]); const [deposits,setDeposits]=useState<any[]>([]); const [users,setUsers]=useState<AdminUser[]>([]); const [verifications,setVerifications]=useState<any[]>([]); const [withdrawals,setWithdrawals]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [showUsers,setShowUsers]=useState(false); const [showVoucherVerification,setShowVoucherVerification]=useState(false); const [traceServiceId,setTraceServiceId]=useState<string|null>(null);
 const [bank,setBank]=useState('BHD'); const [number,setNumber]=useState(''); const [type,setType]=useState('CORRIENTE'); const [holder,setHolder]=useState('SERVIYA DOMINICANA SRL'); const [rnc,setRnc]=useState('');
 const flash=(ok?:string,bad?:any)=>{setMessage(ok||'');setError(bad?.message||'')};
 const load=async()=>{setLoading(true);setError('');const results=await Promise.allSettled([api.get<any>('/admin/stats'),api.get<any>('/admin/bank-accounts'),api.get<any>('/admin-panel/escrows/pending-deposits'),api.get<any>('/admin/users'),api.get<any>('/admin/verifications'),api.get<any>('/admin/withdrawals'),api.get<any>('/worker/bank-account/admin/all')]);const [s,b,d,u,v,w,wb]=results;let failed=0;if(s.status==='fulfilled')setStats(s.value?.stats||{});else failed++;if(b.status==='fulfilled')setBanks(b.value?.bank_accounts||[]);else failed++;if(d.status==='fulfilled')setDeposits(d.value?.pending_deposits||[]);else failed++;if(u.status==='fulfilled')setUsers(u.value?.users||[]);else failed++;if(v.status==='fulfilled')setVerifications(v.value?.verifications||[]);else failed++;if(w.status==='fulfilled')setWithdrawals(w.value?.withdrawals||[]);else failed++;if(wb.status==='fulfilled')setWorkerBankAccounts(wb.value?.bank_accounts||[]);else failed++;if(failed)setError(`${failed} fuente${failed>1?'s':''} administrativa${failed>1?'s':''} no respondió. Los datos que sí están conectados permanecen visibles.`);setLoading(false)};
 useEffect(()=>{load()},[]);
 const addBank=async(e:React.FormEvent)=>{e.preventDefault();if(!number.trim())return flash('',{message:'Escribe el número de cuenta.'});try{await api.post('/admin/bank-accounts',{bank_name:bank,account_number:number.trim(),account_type:type,account_holder:holder,rnc_cedula:rnc,is_active:true,is_primary:true});setNumber('');flash(`Cuenta ${bank} agregada y marcada como principal.`);await load()}catch(e){flash('',e)}};
 const toggleBank=async(b:Bank)=>{try{await api.put(`/admin/bank-accounts/${b.id}`,{is_active:!b.is_active});flash(`Cuenta ${b.bank_name} ${b.is_active?'desactivada':'activada'}.`);await load()}catch(e){flash('',e)}};
 const primaryBank=async(b:Bank)=>{try{await api.put(`/admin/bank-accounts/${b.id}`,{is_primary:true});flash(`Cuenta ${b.bank_name} marcada como principal.`);await load()}catch(e){flash('',e)}};
 const removeBank=async(b:Bank)=>{if(!confirm(`¿Eliminar la cuenta ${b.bank_name} terminada en ${b.account_number.slice(-4)}?`))return;try{await api.delete(`/admin/bank-accounts/${b.id}`);flash('Cuenta eliminada.');await load()}catch(e){flash('',e)}};
 const verify=async(id:number,approved:boolean)=>{try{if(approved) await api.post(`/admin/verifications/${id}/approve`);else await api.patch(`/admin/verifications/${id}`,{status:'RECHAZADO'});flash(approved?'Documento aprobado y trabajador verificado.':'Documento rechazado.');await load()}catch(e){flash('',e)}};
 const withdrawal=async(id:number,status:string)=>{try{await api.patch(`/admin/withdrawals/${id}`,{status});flash(status==='COMPLETADO'?'Retiro marcado como pagado.':'Retiro rechazado.');await load()}catch(e){flash('',e)}};
 return <div className="space-y-6 pb-12 max-w-7xl mx-auto">
  <header className="bg-red-950 text-white p-6 sm:p-8 rounded-3xl shadow-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 bg-red-900/70 text-red-100 px-3 py-1.5 rounded-full text-xs font-black"><ShieldCheck className="w-4 h-4"/> ADMINISTRACIÓN SERVIYA</div><h1 className="text-2xl sm:text-3xl font-black mt-2">Consola Central</h1><p className="text-sm text-red-200 mt-1">Control operativo, financiero, usuarios, verificaciones y Custodia.</p></div><button onClick={load} disabled={loading} className="bg-white text-red-950 rounded-xl px-4 py-3 font-black text-sm inline-flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> Actualizar</button></header>
  {message&&<div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold">✓ {message}</div>}{error&&<div className="p-4 rounded-2xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">⚠ {error}</div>}
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[[Users,'Usuarios',stats.total_users],[Wallet,'Custodia',`RD$ ${Number(stats.escrow_held_rd||0).toLocaleString()}`],[Banknote,'Retiros pendientes',stats.pending_withdrawals||0],[FileCheck2,'Verificaciones',stats.pending_verifications||0]].map(([I,l,v])=><div key={String(l)} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm"><I className="w-5 h-5 text-blue-600"/><p className="text-[10px] font-black uppercase text-slate-400 mt-3">{l}</p><p className="text-xl font-black mt-1">{v}</p></div>)}</div>
  <section className="bg-white p-6 rounded-3xl border-2 border-orange-200 shadow-sm"><div className="flex items-center justify-between gap-3 mb-4"><div className="flex items-center gap-2"><Eye className="w-5 h-5 text-orange-600"/><div><h2 className="font-black text-lg">Depósitos y Custodia</h2><p className="text-xs text-slate-500">Cada depósito queda vinculado al cliente, servicio y trabajador destinatario.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setShowVoucherVerification(true)} className="bg-orange-600 text-white rounded-xl px-4 py-3 font-black text-sm inline-flex items-center gap-2"><ReceiptText className="w-4 h-4"/> Verificar vouchers</button>{deposits[0]?.service_id&&<button onClick={()=>setTraceServiceId(String(deposits[0].service_id))} className="bg-blue-600 text-white rounded-xl px-4 py-3 font-black text-sm inline-flex items-center gap-2"><Route className="w-4 h-4"/> Ver trazabilidad</button>}</div></div><div className="p-4 rounded-2xl bg-orange-50 border border-orange-100 flex items-center justify-between gap-3"><div><p className="font-black text-sm">Control de destino</p><p className="text-xs text-slate-600 mt-1">Antes de liberar fondos se puede consultar el recorrido completo: cliente → trabajador → banco → voucher → Custodia → comisión → pago.</p></div><span className="text-xs font-black text-orange-700">{deposits.length} pendientes</span></div>{deposits.length>0&&<div className="mt-3 grid sm:grid-cols-2 gap-2">{deposits.slice(0,4).map((d:any)=><div key={String(d.service_id)} className="p-3 rounded-xl border bg-slate-50 flex items-center justify-between gap-3"><div><b className="text-sm">{d.title||'Servicio'}</b><p className="text-xs text-slate-500">Cliente: {d.client_name||'—'} • Trabajador: {d.worker_name||'—'}</p><p className="text-xs font-bold mt-1">{d.bank_name||'Banco'} • RD$ {Number(d.total_amount_rd||0).toLocaleString()}</p></div><button onClick={()=>setTraceServiceId(String(d.service_id))} className="shrink-0 px-3 py-2 rounded-lg bg-white border text-xs font-black">Abrir</button></div>)}</div>}</section>
  <section className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><div className="flex items-center gap-2 mb-4"><Building2 className="w-5 h-5 text-blue-600"/><div><h2 className="font-black">Cuentas bancarias de SERVIYA</h2><p className="text-xs text-slate-500">Una sola zona para agregar y administrar las cuentas. Sin casillas duplicadas.</p></div></div><form onSubmit={addBank} className="p-4 rounded-2xl bg-slate-50 border grid sm:grid-cols-2 lg:grid-cols-5 gap-2"><select value={bank} onChange={e=>setBank(e.target.value)} className="p-3 rounded-xl border bg-white text-sm">{BANKS.map(x=><option key={x}>{x}</option>)}</select><input value={number} onChange={e=>setNumber(e.target.value)} placeholder="Número de cuenta" className="p-3 rounded-xl border bg-white text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="p-3 rounded-xl border bg-white text-sm"><option>CORRIENTE</option><option>AHORRO</option></select><input value={holder} onChange={e=>setHolder(e.target.value)} placeholder="Titular" className="p-3 rounded-xl border bg-white text-sm"/><button className="bg-blue-600 text-white rounded-xl px-4 py-3 font-black text-sm">+ Agregar cuenta</button></form><div className="mt-4 space-y-2">{banks.map(b=><div key={b.id} className="p-3 rounded-xl bg-slate-50 border flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>{b.bank_name}</b><span className="font-mono text-xs ml-2">{b.account_number}</span><p className="text-[10px] text-slate-500">{b.account_type} • {b.account_holder} • {b.is_active?'ACTIVA':'INACTIVA'} {b.is_primary?'• PRINCIPAL':''}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>primaryBank(b)} disabled={!!b.is_primary} className="px-3 py-2 rounded-lg border bg-white text-xs font-bold">{b.is_primary?'Principal':'Hacer principal'}</button><button onClick={()=>toggleBank(b)} className="px-3 py-2 rounded-lg border bg-white text-xs font-bold">{b.is_active?'Desactivar':'Activar'}</button><button onClick={()=>removeBank(b)} className="px-3 py-2 rounded-lg border border-red-200 bg-red-50 text-red-700 text-xs font-bold">Eliminar</button></div></div>)}</div></section>
  <section className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><div className="flex items-center gap-2 mb-4"><CheckCircle className="w-5 h-5 text-emerald-600"/><div><h2 className="font-black">Cuentas bancarias de trabajadores</h2><p className="text-xs text-slate-500">Esta es la misma cuenta registrada desde Mi Billetera. No se crea una segunda cuenta ni un segundo formulario.</p></div></div>{workerBankAccounts.length===0?<p className="text-sm text-slate-400 text-center py-5">Ningún trabajador tiene una cuenta bancaria registrada todavía.</p>:<div className="space-y-2">{workerBankAccounts.map(a=><div key={a.id} className="p-4 rounded-2xl bg-slate-50 border flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><b className="text-sm">{a.worker_name||a.worker_id}</b><span className={`text-[10px] font-black px-2 py-1 rounded-full ${a.is_active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}`}>{a.is_active?'ACTIVA':'INACTIVA'}</span></div><p className="text-xs text-slate-500 mt-1">{a.worker_email||'Sin correo'} • {a.bank_name} • {a.account_type}</p><p className="text-xs font-mono mt-1">Cuenta terminada en •••• {String(a.account_number).slice(-4)}</p><p className="text-[10px] text-slate-500 mt-1">Titular: {a.account_holder_name} • Cédula registrada • Actualizada: {a.updated_at?new Date(a.updated_at).toLocaleString():'—'}</p></div><span className="text-xs font-black text-blue-700">Usada para retiros</span></div>)}</div>}</section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-2"><Users className="w-5 h-5 text-blue-600"/><div><h2 className="font-black">Gestión de usuarios</h2><p className="text-xs text-slate-500">La lista completa se abre en una ventana con búsqueda para no hacer crecer el panel.</p></div></div><button onClick={()=>setShowUsers(true)} className="bg-blue-600 text-white px-4 py-3 rounded-xl text-sm font-black inline-flex items-center justify-center gap-2"><Users className="w-4 h-4"/> Gestionar usuarios ({users.length})</button></div></section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2 mb-4"><FileCheck2 className="w-5 h-5 text-blue-600"/><h2 className="font-black">Revisar evidencias y documentos ({verifications.length})</h2></div>{!verifications.length?<p className="text-sm text-slate-400 text-center py-4">No hay verificaciones pendientes.</p>:verifications.map(v=><div key={v.id} className="p-3 rounded-xl bg-slate-50 border flex justify-between items-center gap-3"><div><b>{v.user_name||'Trabajador'}</b><p className="text-xs text-slate-500">{v.document_type||'Documento'} • {v.status}</p></div><div className="flex gap-2"><button onClick={()=>verify(Number(v.id),true)} className="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-bold">Aprobar</button><button onClick={()=>verify(Number(v.id),false)} className="bg-red-50 text-red-700 border border-red-200 px-3 py-2 rounded-lg text-xs font-bold">Rechazar</button></div></div>)}</section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2 mb-4"><Banknote className="w-5 h-5 text-emerald-600"/><h2 className="font-black">Retiros financieros ({withdrawals.length})</h2></div>{!withdrawals.length?<p className="text-sm text-slate-400 text-center py-4">No hay retiros pendientes.</p>:withdrawals.map(w=><div key={w.id} className="p-3 rounded-xl bg-slate-50 border flex justify-between items-center gap-3"><div><b>RD$ {Number(w.amount_rd||w.amount||0).toLocaleString()}</b><p className="text-xs text-slate-500">{w.bank_name||w.method} • {w.account_number}</p></div><div className="flex gap-2"><button onClick={()=>withdrawal(Number(w.id),'COMPLETADO')} className="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-bold">Marcar pagado</button><button onClick={()=>withdrawal(Number(w.id),'RECHAZADO')} className="bg-red-50 text-red-700 border border-red-200 px-3 py-2 rounded-lg text-xs font-bold">Rechazar</button></div></div>)}</section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2"><Settings className="w-5 h-5 text-blue-600"/><h2 className="font-black">Configuración administrativa</h2></div><p className="text-xs text-slate-500 mt-1 mb-4">Aquí se administran los administradores y sus permisos por área.</p><AdminRolesPanel/></section>
  {showUsers&&<AdminUsersModal users={users} onClose={()=>setShowUsers(false)} onReload={load}/>} 
  {showVoucherVerification&&<AdminVoucherVerificationWindow onClose={()=>{setShowVoucherVerification(false);load()}}/>}
  {traceServiceId&&<AdminTraceabilityWindow serviceId={traceServiceId} onClose={()=>setTraceServiceId(null)}/>} 
 </div>;
};
