import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {ShieldCheck,Wallet,BriefcaseBusiness,Eye,Headphones,Scale,FileCheck2,Users,Settings,LockKeyhole,RefreshCw,ChevronRight,LayoutDashboard,Landmark,ClipboardCheck,ReceiptText,Briefcase,FileText,Handshake,Clock3,CheckCircle2,AlertTriangle,Banknote,Shield,MessageSquare,Flag,History,UserCheck,UserCog} from 'lucide-react';
import {AdminPanelV2} from './AdminPanelV2';
import {AdminGlobalActivity} from './AdminGlobalActivity';

type Role={code:string;name:string;description?:string;permissions?:string[]};
const ICONS:any={SUPER_ADMIN:ShieldCheck,ADMINISTRADOR_GENERAL:Settings,ADMIN_FINANCIERO:Wallet,ADMIN_OPERACIONES:BriefcaseBusiness,ADMIN_CUSTODIA:Landmark,ADMIN_VERIFICACION:FileCheck2,ADMIN_SOPORTE:Headphones,ADMIN_MODERACION:Eye,ADMIN_DISPUTAS:Scale,AUDITOR:LockKeyhole};
const META:any={SUPER_ADMIN:{group:'Dirección',short:'Control total',accent:'bg-red-50 text-red-700 border-red-200'},ADMINISTRADOR_GENERAL:{group:'Dirección',short:'Operación general',accent:'bg-blue-50 text-blue-700 border-blue-200'},ADMIN_FINANCIERO:{group:'Finanzas',short:'Dinero y cuentas',accent:'bg-emerald-50 text-emerald-700 border-emerald-200'},ADMIN_CUSTODIA:{group:'Finanzas',short:'Custodia y liberaciones',accent:'bg-orange-50 text-orange-700 border-orange-200'},ADMIN_OPERACIONES:{group:'Operación',short:'Servicios y contratos',accent:'bg-violet-50 text-violet-700 border-violet-200'},ADMIN_VERIFICACION:{group:'Operación',short:'Documentos y validación',accent:'bg-cyan-50 text-cyan-700 border-cyan-200'},ADMIN_SOPORTE:{group:'Usuarios',short:'Atención y tickets',accent:'bg-sky-50 text-sky-700 border-sky-200'},ADMIN_MODERACION:{group:'Usuarios',short:'Contenido y perfiles',accent:'bg-pink-50 text-pink-700 border-pink-200'},ADMIN_DISPUTAS:{group:'Control',short:'Conflictos y evidencias',accent:'bg-rose-50 text-rose-700 border-rose-200'},AUDITOR:{group:'Control',short:'Consulta y auditoría',accent:'bg-slate-100 text-slate-700 border-slate-300'}};
const WORK:any={
 ADMINISTRADOR_GENERAL:[['Usuarios','Supervisar cuentas, estados y actividad',Users],['Servicios','Supervisar el ciclo completo de servicios',Briefcase],['Finanzas','Supervisar depósitos, custodia y retiros',Wallet],['Verificación','Revisar validaciones y trabajadores',UserCheck],['Disputas','Supervisar conflictos y resoluciones',Scale],['Configuración','Control general de la plataforma',Settings]],
 ADMIN_FINANCIERO:[['Panel financiero','Visión de fondos y movimientos',Banknote],['Depósitos','Revisar ingresos y comprobantes',ReceiptText],['Custodia','Controlar fondos retenidos',Shield],['Retiros','Revisar y procesar solicitudes',Wallet],['Cuentas bancarias','Consultar cuentas de trabajadores',Landmark],['Trazabilidad','Seguir cada movimiento financiero',ActivityIcon]],
 ADMIN_OPERACIONES:[['Servicios','Buscar, filtrar y supervisar servicios',Briefcase],['Postulaciones','Revisar candidatos y aplicaciones',Users],['Contratos','Supervisar contratación y estados',Handshake],['Trabajos en progreso','Dar seguimiento al servicio contratado',Clock3],['Finalizados','Controlar trabajos completados',CheckCircle2],['Incidencias','Detectar problemas y enviarlos a control',AlertTriangle],['Historial','Consultar el recorrido operativo',History]],
 ADMIN_CUSTODIA:[['Depósitos pendientes','Validar comprobantes y depósitos',ReceiptText],['Fondos retenidos','Consultar dinero bajo custodia',Shield],['Liberaciones','Ejecutar liberaciones autorizadas',CheckCircle2],['Reembolsos','Controlar devoluciones',Banknote],['Disputas en custodia','Coordinar fondos con disputas',Scale],['Trazabilidad','Ver origen y destino del dinero',ActivityIcon]],
 ADMIN_VERIFICACION:[['Pendientes','Cola de documentos por revisar',FileCheck2],['Identidad','Validar Cédula y datos',UserCheck],['Documentos','Revisar archivos enviados',FileText],['INFOTEP','Controlar acreditaciones',ClipboardCheck],['Verificados','Consultar trabajadores aprobados',Users],['Historial','Consultar decisiones anteriores',History]],
 ADMIN_SOPORTE:[['Tickets','Atender solicitudes de usuarios',MessageSquare],['Usuarios','Consultar cuenta y contexto',Users],['Incidencias','Dar seguimiento a problemas',AlertTriangle],['Conversaciones','Coordinar atención y respuestas',MessageSquare],['Escalaciones','Enviar casos a Operaciones o Disputas',Flag],['Historial','Consultar atención realizada',History]],
 ADMIN_MODERACION:[['Perfiles','Revisar contenido de perfiles',Users],['Servicios','Revisar publicaciones',Briefcase],['Portafolios','Controlar trabajos y muestras',FileText],['Reseñas','Supervisar contenido de opiniones',MessageSquare],['Reportes','Revisar contenido señalado',Flag],['Historial','Consultar acciones de moderación',History]],
 ADMIN_DISPUTAS:[['Casos abiertos','Cola de conflictos pendientes',Scale],['Evidencias','Revisar pruebas de las partes',FileText],['Cliente','Consultar información del reclamante',Users],['Trabajador','Consultar información del proveedor',UserCheck],['Resolución','Gestionar devolución o liberación',CheckCircle2],['Historial','Consultar decisiones y auditoría',History]],
 AUDITOR:[['Auditoría','Consultar todas las acciones administrativas',ActivityIcon],['Usuarios','Consultar actividad de cuentas',Users],['Servicios','Consultar ciclo operativo',Briefcase],['Finanzas','Consultar movimientos financieros',Banknote],['Custodia','Consultar fondos y liberaciones',Shield],['Seguridad','Consultar cambios críticos',LockKeyhole]],
};
const ActivityIcon=({className}:any)=><span className={className||''}>●</span>;

export const AdminRoleWindows:React.FC=()=>{
 const [access,setAccess]=useState<any>(null);const [roles,setRoles]=useState<Role[]>([]);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [mobileOpen,setMobileOpen]=useState(false);
 const load=async()=>{setRefreshing(true);setError('');try{const [a,r]=await Promise.all([api.get<any>('/admin/super-admin/access'),api.get<any>('/admin/administrator-roles')]);const role=String(a?.admin_role||'').toUpperCase();const all=(r?.roles||[]).map((x:any)=>({code:String(x.key||x.code||'').toUpperCase(),name:x.label||x.name,description:x.description,permissions:x.permissions||[]}));setAccess(a);setRoles(all);setSelected(prev=>prev||role||'ADMIN_OPERACIONES')}catch(e:any){setError(e?.message||'No se pudo cargar el acceso administrativo.')}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load()},[]);
 const superAdmin=!!access?.is_super_admin;const visible=useMemo(()=>superAdmin?roles:roles.filter(r=>r.code===String(access?.admin_role||'').toUpperCase()),[superAdmin,roles,access]);const current=roles.find(r=>r.code===selected)||visible[0];
 if(loading)return <div className="min-h-screen bg-slate-100 flex items-center justify-center text-slate-600 font-semibold">Cargando áreas administrativas…</div>;
 if(error)return <div className="min-h-screen bg-slate-100 p-6"><div className="max-w-xl mx-auto p-5 rounded-2xl bg-red-50 border border-red-200 text-red-700 font-bold">{error}<button onClick={load} className="block mt-3 px-4 py-2 rounded-xl bg-white border text-sm">Reintentar</button></div></div>;
 if(!current)return <div className="p-6">No hay un rol administrativo asignado.</div>;
 const choose=(code:string)=>{setSelected(code);setMobileOpen(false);window.scrollTo({top:0,behavior:'smooth'})};const Icon=ICONS[current.code]||Settings;const meta=META[current.code]||META.ADMINISTRADOR_GENERAL;
 return <div className="min-h-screen bg-slate-100 text-slate-800"><header className="sticky top-0 z-30 bg-slate-950 text-white border-b border-white/10 shadow-lg"><div className="max-w-[1500px] mx-auto px-3 sm:px-5 py-3 flex items-center justify-between gap-3"><div className="flex items-center gap-3 min-w-0"><div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><ShieldCheck className="w-5 h-5"/></div><div><p className="text-[10px] font-black tracking-[.18em] text-slate-400">SERVIYA • ADMINISTRACIÓN</p><h1 className="font-black text-base sm:text-lg">Centro de administración</h1></div></div><div className="flex items-center gap-2"><span className="hidden sm:inline-flex px-3 py-2 rounded-xl bg-red-500/15 text-red-200 text-[11px] font-black">{superAdmin?'SUPER ADMINISTRADOR • CONTROL TOTAL':current.name}</span><button onClick={load} disabled={refreshing} className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><RefreshCw className={`w-4 h-4 ${refreshing?'animate-spin':''}`}/></button><button onClick={()=>setMobileOpen(v=>!v)} className="lg:hidden w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><LayoutDashboard className="w-4 h-4"/></button></div></div></header>
 <div className="max-w-[1500px] mx-auto p-3 sm:p-5 lg:grid lg:grid-cols-[270px_minmax(0,1fr)] lg:gap-5"><aside className={`${mobileOpen?'block':'hidden'} lg:block mb-4 lg:mb-0`}><div className="lg:sticky lg:top-[76px] bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Áreas administrativas</p><p className="text-sm font-bold mt-1">{superAdmin?'Acceso total del Super Administrador':'Área asignada'}</p></div><nav className="p-2 max-h-[70vh] overflow-y-auto">{visible.map(r=>{const I=ICONS[r.code]||Settings;const active=r.code===current.code;return <button key={r.code} onClick={()=>choose(r.code)} className={`w-full text-left p-3 rounded-xl flex items-center gap-3 mb-1 ${active?'bg-slate-900 text-white':'hover:bg-slate-50 text-slate-700'}`}><div className={`w-9 h-9 rounded-lg flex items-center justify-center ${active?'bg-white/10':'bg-slate-100'}`}><I className="w-4 h-4"/></div><div className="min-w-0 flex-1"><p className="text-xs font-black truncate">{r.name}</p><p className={`text-[10px] mt-0.5 truncate ${active?'text-slate-300':'text-slate-400'}`}>{(META[r.code]||meta).short}</p></div>{active&&<ChevronRight className="w-4 h-4"/>}</button>})}</nav><div className="p-3 border-t border-slate-100 bg-slate-50 text-[10px] text-slate-500">{superAdmin?'Puedes entrar a todas las ventanas y consultar el ecosistema completo sin cerrar esta sesión.':'Acceso limitado al área asignada.'}</div></div></aside>
 <main className="min-w-0 space-y-4"><section className={`rounded-3xl border p-5 sm:p-6 ${meta.accent}`}><div className="flex items-start gap-4"><div className="w-12 h-12 rounded-2xl bg-white/80 flex items-center justify-center"><Icon className="w-6 h-6"/></div><div><p className="text-[10px] font-black uppercase tracking-wider opacity-70">Ventana activa • {meta.group}</p><h2 className="text-xl sm:text-2xl font-black mt-1">{current.name}</h2><p className="text-sm opacity-80 mt-1 max-w-4xl">{current.description}</p></div></div></section>
 {superAdmin&&current.code==='SUPER_ADMIN'?<><section className="bg-slate-900 text-white rounded-3xl p-5 sm:p-6"><div className="flex items-start gap-4"><ShieldCheck className="w-7 h-7 shrink-0"/><div><h3 className="text-lg font-black">Control total del Super Administrador</h3><p className="text-sm text-slate-300 mt-1">Desde aquí puedes entrar a cada área administrativa y ver sus movimientos, trabajo, historial y resultados con la misma sesión. No se crea un segundo panel.</p></div></div></section><div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 sm:p-5 border-b border-slate-100"><h3 className="font-black text-lg">Centro operativo completo</h3><p className="text-xs text-slate-500 mt-1">La consola oficial existente permanece aquí; las demás áreas se abren desde el menú.</p></div><div className="p-3 sm:p-5"><AdminPanelV2/></div></div><AdminGlobalActivity/></>:<RoleWorkspace role={current}/>}</main></div></div>;
};

const RoleWorkspace:React.FC<{role:Role}>=({role})=>{const Icon=ICONS[role.code]||Settings;const items=WORK[role.code]||[];return <div className="space-y-4"><section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5 sm:p-6"><div className="flex items-center gap-3"><Icon className="w-6 h-6"/><div><h3 className="font-black text-lg">Responsabilidades y funciones</h3><p className="text-xs text-slate-500">Este es el ecosistema de trabajo de {role.name}.</p></div></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3 mt-5">{items.map((x:any)=><div key={x[0]} className="rounded-2xl border border-slate-200 p-4 bg-slate-50"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-white border flex items-center justify-center"><x[2] className="w-5 h-5 text-slate-700"/></div><div><p className="text-sm font-black">{x[0]}</p><p className="text-xs text-slate-500 mt-1 leading-relaxed">{x[1]}</p></div></div></div>)}</div></section><section className="bg-slate-900 text-white rounded-3xl p-5"><div className="flex items-center gap-3"><UserCog className="w-5 h-5"/><div><p className="font-black text-sm">Área protegida por permisos</p><p className="text-xs text-slate-400 mt-1">Las acciones críticas deben usar los endpoints reales del área. El Super Administrador conserva acceso transversal desde esta misma consola.</p></div></div></section></div>};
