import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {RefreshCw,CheckCircle2,XCircle,PauseCircle,PlayCircle,Scale,Wallet,Briefcase,Users,MessageSquare,FileCheck2,Eye,Landmark,Activity,ShieldCheck} from 'lucide-react';

type Props={role:string;name:string};
type Row=Record<string,any>;
const ENDPOINTS:Record<string,string>={
 ADMIN_OPERACIONES:'/admin-panel/services',
 ADMIN_FINANCIERO:'/admin-panel/transactions',
 ADMIN_CUSTODIA:'/admin-panel/overview',
 ADMIN_VERIFICACION:'/admin/verifications',
 ADMIN_VERIFICACIONES:'/admin/verifications',
 ADMIN_SOPORTE:'/admin-panel/support',
 ADMIN_MODERACION:'/admin-panel/portfolio',
 ADMIN_DISPUTAS:'/admin-panel/overview',
 AUDITOR:'/admin-panel/audit',
 ADMINISTRADOR_GENERAL:'/admin-panel/overview'
};

export const AdminOperationalWorkspace:React.FC<Props>=({role,name})=>{
 const [rows,setRows]=useState<Row[]>([]);const [overview,setOverview]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const ep=ENDPOINTS[role]||'/admin-panel/overview';const data=await api.get<any>(ep);if(Array.isArray(data?.services))setRows(data.services);else if(Array.isArray(data?.transactions))setRows(data.transactions);else if(Array.isArray(data?.verifications))setRows(data.verifications);else if(Array.isArray(data?.tickets))setRows(data.tickets);else if(Array.isArray(data?.portfolio))setRows(data.portfolio);else if(Array.isArray(data?.admin_audit))setRows(data.admin_audit);else setRows([]);setOverview(data)}catch(e:any){setError(e?.message||'No se pudieron cargar los datos del área.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[role]);
 const act=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setMessage('');setError('');try{await fn();setMessage('Acción realizada correctamente y registrada.');await load()}catch(e:any){setError(e?.message||'La acción no pudo completarse.')}finally{setBusy('')}};
 const serviceStatus=(id:string,status:string)=>act('s'+id,()=>api.patch(`/admin-panel/services/${id}/moderation`,{status,reason:`Gestión desde ${name}`}));
 const verify=(id:number,ok:boolean)=>act('v'+id,()=>ok?api.post(`/admin/verifications/${id}/approve`,{}):api.patch(`/admin/verifications/${id}`,{status:'RECHAZADO'}));
 const support=(id:number,status:string)=>act('t'+id,()=>api.patch(`/admin-panel/support/${id}`,{status,admin_response:`Atendido por ${name}`}));
 const portfolio=(id:number,action:string)=>act('p'+id,()=>api.patch(`/admin-panel/portfolio/${id}/moderation`,{action,reason:`Moderación desde ${name}`}));
 const userState=(id:string,active:boolean)=>act('u'+id,()=>api.patch(`/admin-panel/users/${id}/state`,{is_active:active,reason:`Gestión desde ${name}`}));
 if(loading)return <section className="bg-white rounded-3xl border p-6"><div className="flex items-center gap-2 font-bold"><RefreshCw className="w-4 h-4 animate-spin"/> Cargando datos reales de {name}…</div></section>;
 if(error&&role!=='ADMIN_CUSTODIA'&&role!=='ADMIN_DISPUTAS')return <section className="bg-white rounded-3xl border p-6"><div className="p-4 rounded-2xl bg-red-50 border border-red-200 text-red-700 font-bold">{error}</div><button onClick={load} className="mt-3 px-4 py-2 rounded-xl border font-bold">Reintentar</button></section>;
 const title=role==='ADMIN_OPERACIONES'?'Servicios, postulaciones y contratos':role==='ADMIN_FINANCIERO'?'Movimientos financieros y retiros':role==='ADMIN_CUSTODIA'?'Custodia, liberaciones y control de fondos':role.startsWith('ADMIN_VERIFIC')?'Verificación de trabajadores':role==='ADMIN_SOPORTE'?'Soporte y tickets':role==='ADMIN_MODERACION'?'Moderación de contenido':role==='ADMIN_DISPUTAS'?'Disputas y resolución':role==='AUDITOR'?'Auditoría y trazabilidad':'Supervisión general';
 return <section className="space-y-4">
  {message&&<div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold">✓ {message}</div>}
  {error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">⚠ {error}</div>}
  <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase text-slate-400">Herramienta operativa</p><h3 className="text-xl font-black mt-1">{title}</h3><p className="text-xs text-slate-500 mt-1">Datos consultados desde PostgreSQL y acciones guardadas en la auditoría.</p></div><button onClick={load} className="px-3 py-2 rounded-xl border font-bold inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Actualizar</button></div></div>
  {role==='ADMIN_OPERACIONES'&&<List title="Servicios" rows={rows} empty="No hay servicios registrados." render={(r,i)=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>{r.title||'Servicio'}</b><p className="text-xs text-slate-500">{r.category_name||'Sin categoría'} • {r.status||'—'} • Cliente: {r.client_name||'—'}</p><p className="text-xs mt-1">RD$ {Number(r.price_rd||0).toLocaleString()}</p></div><div className="flex gap-2 flex-wrap"><button disabled={busy==='s'+r.id} onClick={()=>serviceStatus(String(r.id),'EN_PROGRESO')} className="px-3 py-2 rounded-lg bg-blue-600 text-white text-xs font-bold">Poner en progreso</button><button disabled={busy==='s'+r.id} onClick={()=>serviceStatus(String(r.id),'COMPLETADA')} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold">Completar</button><button disabled={busy==='s'+r.id} onClick={()=>serviceStatus(String(r.id),'CANCELADA')} className="px-3 py-2 rounded-lg border border-red-200 text-red-700 text-xs font-bold">Cancelar</button></div></div>}/>} 
  {role==='ADMIN_FINANCIERO'&&<List title="Movimientos" rows={rows} empty="No hay movimientos registrados." render={r=><div><div className="flex justify-between gap-3"><b>{r.type||'Movimiento'}</b><span className="font-black">RD$ {Number(r.amount||0).toLocaleString()}</span></div><p className="text-xs text-slate-500">{r.reference_code||'Sin referencia'} • {r.status||'—'} • {r.user_name||r.user_id||'—'}</p></div>}/>} 
  {role==='ADMIN_CUSTODIA'&&<Custody overview={overview}/>} 
  {(role==='ADMIN_VERIFICACION'||role==='ADMIN_VERIFICACIONES')&&<List title="Documentos de verificación" rows={rows.filter(r=>r.status==='PENDIENTE')} empty="No hay verificaciones pendientes." render={r=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>Trabajador: {r.user_id||r.worker_id}</b><p className="text-xs text-slate-500">{r.document_type||'Documento'} • {r.status}</p></div><div className="flex gap-2"><button disabled={!!busy} onClick={()=>verify(Number(r.id),true)} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold">Aprobar</button><button disabled={!!busy} onClick={()=>verify(Number(r.id),false)} className="px-3 py-2 rounded-lg border border-red-200 text-red-700 text-xs font-bold">Rechazar</button></div></div>}/>} 
  {role==='ADMIN_SOPORTE'&&<List title="Tickets" rows={rows} empty="No hay tickets." render={r=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>{r.subject||'Solicitud'}</b><p className="text-xs text-slate-500">{r.user_name||r.user_id||'Usuario'} • {r.status||'—'}</p></div><div className="flex gap-2"><button onClick={()=>support(Number(r.id),'EN_REVISION')} className="px-3 py-2 rounded-lg bg-blue-600 text-white text-xs font-bold">En revisión</button><button onClick={()=>support(Number(r.id),'RESUELTO')} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold">Resolver</button></div></div>}/>} 
  {role==='ADMIN_MODERACION'&&<List title="Portafolios" rows={rows} empty="No hay elementos de portafolio." render={r=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>{r.title||'Trabajo'}</b><p className="text-xs text-slate-500">{r.worker_name||r.worker_id||'Trabajador'} • {r.description||'Sin descripción'}</p></div><div className="flex gap-2"><button onClick={()=>portfolio(Number(r.id),'APPROVE')} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold">Aprobar</button><button onClick={()=>portfolio(Number(r.id),'REMOVE')} className="px-3 py-2 rounded-lg border border-red-200 text-red-700 text-xs font-bold">Retirar</button></div></div>}/>} 
  {role==='ADMIN_DISPUTAS'&&<Disputes/>}
  {role==='AUDITOR'&&<List title="Registro de auditoría" rows={rows} empty="No hay acciones administrativas registradas." render={r=><div><div className="flex justify-between gap-3"><b>{r.action||'Acción'}</b><span className="text-xs font-bold">{r.resource||'—'}</span></div><p className="text-xs text-slate-500 mt-1">{r.details||'Sin detalle'} • {r.timestamp||'—'}</p></div>}/>} 
  {role==='ADMINISTRADOR_GENERAL'&&<General overview={overview}/>} 
 </section>;
};

const List:React.FC<{title:string;rows:Row[];empty:string;render:(r:Row,i:number)=>React.ReactNode}>=({title,rows,empty,render})=><div className="bg-white rounded-3xl border shadow-sm p-5"><div className="flex items-center gap-2 mb-4"><Activity className="w-5 h-5 text-blue-600"/><h4 className="font-black">{title} ({rows.length})</h4></div>{rows.length?<div className="space-y-2 max-h-[620px] overflow-auto">{rows.slice(0,100).map((r,i)=><div key={String(r.id??i)} className="p-4 rounded-2xl border bg-slate-50">{render(r,i)}</div>)}</div>:<p className="text-sm text-slate-400 text-center py-8">{empty}</p>}</div>;

const Custody:React.FC<{overview:Row|null}>=({overview})=>{
 const [items,setItems]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [msg,setMsg]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const d=await api.get<any>('/admin-panel/escrows/pending-release');setItems(d?.pending_releases||[])}catch(e:any){setError(e?.message||'No se pudo cargar la cola de liberaciones.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const release=async(serviceId:string)=>{setBusy(serviceId);setError('');setMsg('');try{const r=await api.post<any>(`/admin-panel/escrows/${serviceId}/approve-release`,{notes:'Liberación confirmada desde Custodia SERVIYA'});setMsg(r?.message||'Fondos liberados correctamente.');await load()}catch(e:any){setError(e?.message||'No se pudo liberar la custodia.')}finally{setBusy('')}};
 return <div className="space-y-4">
  <div className="bg-white rounded-3xl border shadow-sm p-5"><div className="grid sm:grid-cols-3 gap-3"><Metric label="En custodia" value={`RD$ ${Number(overview?.finance?.custody_rd||0).toLocaleString()}`}/><Metric label="Liberado" value={`RD$ ${Number(overview?.finance?.released_rd||0).toLocaleString()}`}/><Metric label="Retiros pendientes" value={overview?.finance?.pending_withdrawals||0}/></div></div>
  {msg&&<div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold">✓ {msg}</div>}
  {error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">⚠ {error}</div>}
  <div className="bg-white rounded-3xl border shadow-sm p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><p className="text-[10px] font-black uppercase text-slate-400">Cola real de liberaciones</p><h4 className="font-black text-lg">Trabajos aprobados por el cliente</h4><p className="text-xs text-slate-500 mt-1">Aquí aparecen los trabajos en PENDIENTE_APROBACION que esperan la confirmación de Administración.</p></div><button onClick={load} disabled={loading} className="px-3 py-2 rounded-xl border font-bold inline-flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Actualizar</button></div>
   {items.length?<div className="space-y-3">{items.map(r=><div key={String(r.id)} className="p-4 rounded-2xl border bg-slate-50"><div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div className="min-w-0"><p className="font-black text-slate-900">{r.display_title||r.title||'Servicio'}</p><p className="text-xs text-slate-500 mt-1">Trabajador: {r.worker_name||r.worker_id||'—'} • Servicio: {r.service_id}</p><p className="text-xs text-slate-500 mt-1">Estado: PENDIENTE_APROBACION • Trabajo enviado a revisión: {r.completion_submitted?'Sí':'No'}</p>{r.completion_summary&&<p className="text-sm text-slate-700 mt-2">“{r.completion_summary}”</p>}</div><div className="lg:text-right shrink-0"><p className="text-lg font-black">RD$ {Number(r.amount_rd||0).toLocaleString()}</p><p className="text-xs text-slate-500">Trabajador recibe RD$ {Number(r.payout_rd||0).toLocaleString()}</p><button disabled={busy===String(r.service_id)} onClick={()=>release(String(r.service_id))} className="mt-2 px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black disabled:opacity-50">{busy===String(r.service_id)?'Liberando…':'Liberar custodia y pagar al trabajador'}</button></div></div></div>)}</div>:<div className="py-10 text-center"><p className="font-bold text-slate-500">No hay trabajos pendientes de liberación.</p><p className="text-xs text-slate-400 mt-1">Cuando el cliente confirme un trabajo completado, aparecerá aquí automáticamente.</p></div>}
  </div>
 </div>;
};

const General:React.FC<{overview:Row|null}>=({overview})=><div className="bg-white rounded-3xl border shadow-sm p-5"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Usuarios" value={overview?.users?.total||0}/><Metric label="Servicios" value={overview?.services?.total||0}/><Metric label="En progreso" value={overview?.services?.in_progress||0}/><Metric label="Disputas" value={overview?.services?.disputed||0}/></div><div className="mt-4 p-4 rounded-2xl bg-slate-50 text-xs text-slate-600">Supervisión general basada en datos reales. Las acciones críticas permanecen en sus áreas especializadas para mantener separación de funciones.</div></div>;
const Metric=({label,value}:{label:string;value:any})=><div className="p-4 rounded-2xl bg-slate-50 border"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="text-xl font-black mt-1">{value}</p></div>;
const Disputes=()=>{const [items,setItems]=useState<Row[]>([]);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');const [err,setErr]=useState('');const load=async()=>{try{const d=await api.get<any>('/admin/disputes');setItems(d?.disputes||[])}catch(e:any){setErr(e?.message||'No se pudieron cargar las disputas.')}};useEffect(()=>{load()},[]);const resolve=async(id:number,action:string)=>{setBusy(String(id));try{await api.post(`/admin/disputes/${id}/resolve`,{action,resolution:action==='REFUND_TO_CLIENT'?'Reembolso al cliente':'Liberación al trabajador'});setMsg('Disputa resuelta y registrada.');await load()}catch(e:any){setErr(e?.message||'No se pudo resolver.')}finally{setBusy('')}};return <List title="Casos de disputa" rows={items} empty={err||'No hay disputas abiertas.'} render={r=><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>Disputa #{r.id}</b><p className="text-xs text-slate-500">Servicio: {r.service_id||'—'} • {r.status||'—'}</p></div><div className="flex gap-2"><button disabled={busy===String(r.id)} onClick={()=>resolve(Number(r.id),'REFUND_TO_CLIENT')} className="px-3 py-2 rounded-lg border text-xs font-bold">Reembolsar cliente</button><button disabled={busy===String(r.id)} onClick={()=>resolve(Number(r.id),'RELEASE_TO_WORKER')} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-bold">Liberar trabajador</button></div></div>}/>};
