import React, { useEffect, useState } from 'react';
import { BellRing, ImagePlus, Pencil, Plus, Trash2, X } from 'lucide-react';
import { api } from '../services/api';

type Announcement = { id:number; title:string; body:string; image_urls:string[]; audience:string; priority:string; action_label?:string|null; action_tab?:string|null; published:boolean; };
type Form = Omit<Announcement,'id'|'published'> & { published:boolean };
const empty: Form = { title:'', body:'', image_urls:[], audience:'TODOS', priority:'NORMAL', action_label:'', action_tab:'', published:true };

export const AdminAnnouncementsPanel: React.FC = () => {
  const [items,setItems] = useState<Announcement[]>([]); const [form,setForm] = useState<Form>(empty); const [editing,setEditing] = useState<number|null>(null); const [imageUrl,setImageUrl] = useState(''); const [saving,setSaving] = useState(false);
  const load = async()=>{ try { const d=await api.get<{announcements:Announcement[]}>('/announcements/admin'); setItems(d.announcements||[]); } catch {} };
  useEffect(()=>{load();},[]);
  const addImage=()=>{ const u=imageUrl.trim(); if(!u)return; setForm(f=>({...f,image_urls:[...f.image_urls,u].slice(0,8)})); setImageUrl(''); };
  const save=async()=>{ if(!form.title.trim()||!form.body.trim())return; setSaving(true); try { const payload={...form,action_label:form.action_label||null,action_tab:form.action_tab||null}; if(editing) await api.patch(`/announcements/admin/${editing}`,payload); else await api.post('/announcements/admin',payload); setForm(empty); setEditing(null); await load(); } finally {setSaving(false);} };
  const edit=(a:Announcement)=>{setEditing(a.id);setForm({...a,action_label:a.action_label||'',action_tab:a.action_tab||''});};
  const remove=async(id:number)=>{if(!confirm('¿Eliminar este anuncio?'))return; await api.delete(`/announcements/admin/${id}`); await load();};
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">Comunicación oficial</p><h2 className="mt-1 text-xl font-black text-slate-900">📢 Anuncios</h2><p className="mt-1 text-xs text-slate-500">Publica novedades, avisos, promociones y campañas de SERVIYA.</p></div><BellRing className="w-6 h-6 text-blue-600"/></div>
    <div className="mt-5 grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="rounded-2xl bg-slate-50 border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-black">{editing?'Editar anuncio':'Crear anuncio'}</h3>{editing&&<button onClick={()=>{setEditing(null);setForm(empty)}} className="p-2 rounded-lg bg-white"><X className="w-4 h-4"/></button>}</div>
      <input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Título del anuncio" className="mt-4 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none"/>
      <textarea value={form.body} onChange={e=>setForm(f=>({...f,body:e.target.value}))} placeholder="Texto del anuncio" rows={6} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none"/>
      <div className="mt-2 flex gap-2"><input value={imageUrl} onChange={e=>setImageUrl(e.target.value)} placeholder="URL de imagen (puedes agregar varias)" className="flex-1 rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs outline-none"/><button onClick={addImage} className="rounded-xl bg-slate-900 px-3 text-white"><ImagePlus className="w-4 h-4"/></button></div>
      {!!form.image_urls.length&&<div className="mt-2 flex flex-wrap gap-2">{form.image_urls.map((u,i)=><span key={i} className="max-w-full rounded-lg bg-white border border-slate-200 px-2 py-1 text-[10px] truncate">{u}</span>)}</div>}
      <div className="mt-3 grid grid-cols-2 gap-2"><select value={form.audience} onChange={e=>setForm(f=>({...f,audience:e.target.value}))} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs"><option value="TODOS">Todos</option><option value="CLIENTE">Clientes</option><option value="TRABAJADOR">Trabajadores</option></select><select value={form.priority} onChange={e=>setForm(f=>({...f,priority:e.target.value}))} className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs"><option value="NORMAL">Normal</option><option value="IMPORTANTE">Importante</option><option value="URGENTE">Urgente</option></select></div>
      <div className="mt-2 grid grid-cols-2 gap-2"><input value={form.action_label||''} onChange={e=>setForm(f=>({...f,action_label:e.target.value}))} placeholder="Texto del botón (opcional)" className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs outline-none"/><input value={form.action_tab||''} onChange={e=>setForm(f=>({...f,action_tab:e.target.value}))} placeholder="Destino interno (opcional)" className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-xs outline-none"/></div>
      <button disabled={saving} onClick={save} className="mt-3 w-full rounded-xl bg-blue-600 py-3 text-sm font-black text-white disabled:opacity-50">{saving?'Guardando…':editing?'Guardar cambios':'Publicar anuncio'}</button>
    </div><div className="space-y-2"><h3 className="font-black text-slate-900">Anuncios publicados</h3>{items.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-6 text-center text-xs text-slate-500">Todavía no hay anuncios.</div>:items.map(a=><div key={a.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase text-blue-600">{a.audience} · {a.priority}</p><h4 className="mt-1 font-black">{a.title}</h4><p className="mt-1 text-xs text-slate-500 line-clamp-2">{a.body}</p></div><div className="flex gap-1"><button onClick={()=>edit(a)} className="p-2 rounded-lg bg-slate-100"><Pencil className="w-4 h-4"/></button><button onClick={()=>remove(a.id)} className="p-2 rounded-lg bg-red-50 text-red-600"><Trash2 className="w-4 h-4"/></button></div></div></div>)}</div></div>
  </section>;
};
