import React,{useEffect,useState} from 'react';
import {Award,CheckCircle2,Clock3,FileCheck2,ShieldCheck,X} from 'lucide-react';
import {api} from '../services/api';

type Row=Record<string,any>;

export const AdminVerificationDossierPanel:React.FC=()=>{
 const [workers,setWorkers]=useState<Row[]>([]); const [selected,setSelected]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const d=await api.get<any>('/admin/verifications/full');setWorkers(d?.workers||[]);}catch(e:any){setError(e?.message||'No se pudieron cargar las verificaciones.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const decide=async(id:any,status:'VERIFICADO'|'RECHAZADO')=>{const notes=status==='RECHAZADO'?window.prompt('Indica el motivo del rechazo:'):'';if(status==='RECHAZADO'&&!notes)return;setBusy(String(id));setMessage('');setError('');try{const r=await api.patch(`/admin/verifications/${id}`,{status,notes:notes||null});setMessage(r?.message||'Verificación actualizada.');await load();if(selected){const refreshed=(await api.get<any>('/admin/verifications/full')).workers?.find((w:any)=>w.worker?.id===selected.worker?.id);setSelected(refreshed||null)}}catch(e:any){setError(e?.message||'No se pudo actualizar la verificación.')}finally{setBusy('')}};
 const fileUrl=(url:string)=>{if(!url)return '';const base=(import.meta as any).env?.VITE_API_BASE_URL||'/api/v1';return url.startsWith('http')?url:`${base.replace(/\/api\/v1$/,'')}${url}`};
 if(loading)return <div className="p-5 text-sm text-slate-500">Cargando verificaciones completas…</div>;
 return <div className="p-4 sm:p-5 space-y-4">
  <div className="rounded-2xl bg-violet-50 border border-violet-200 p-4"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-violet-700"/><h3 className="font-black text-slate-900">Verificación completa de trabajadores</h3></div><p className="text-xs text-slate-600 mt-1">La Cédula es obligatoria. Las cuatro áreas adicionales son opcionales y cada área aprobada suma una estrella.</p></div>
  {message&&<div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold">✓ {message}</div>}{error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs font-bold">⚠ {error}</div>}
  <div className="grid gap-3">{workers.map(w=>{const s=Number(w.stars||0);return <button key={w.worker?.id} type="button" onClick={()=>setSelected(w)} className="text-left rounded-2xl border border-slate-200 bg-white p-4 hover:border-violet-300 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-900">{w.worker?.name||'Trabajador'}</p><p className="text-xs text-slate-500">{w.worker?.email||'—'} {w.worker?.phone?`• ${w.worker.phone}`:''}</p></div><div className="text-lg tracking-tight" aria-label={`${s} de 5 estrellas`}>{'★'.repeat(s)}<span className="text-slate-300">{'★'.repeat(5-s)}</span></div></div><div className="mt-2 flex flex-wrap gap-1.5">{(w.categories||[]).map((c:any)=><span key={c.key} className={`text-[10px] font-bold px-2 py-1 rounded-full ${c.verified?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{c.verified?'✓':'○'} {c.label}</span>)}</div></button>})}</div>
  {!workers.length&&<div className="p-8 text-center text-sm text-slate-500">No hay trabajadores con registros de verificación.</div>}
  {selected&&<div className="fixed inset-0 z-[70] bg-slate-950/60 backdrop-blur-sm p-3 sm:p-6 overflow-y-auto"><div className="max-w-3xl mx-auto bg-white rounded-3xl shadow-2xl overflow-hidden"><div className="p-5 bg-slate-950 text-white flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-widest text-slate-400">Dossier de verificación</p><h3 className="text-xl font-black">{selected.worker?.name}</h3></div><button onClick={()=>setSelected(null)} className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><X className="w-5 h-5"/></button></div><div className="p-5 space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 flex items-center justify-between"><div><p className="text-[10px] font-black uppercase text-amber-700">Nivel de verificación</p><p className="font-black text-slate-900">{selected.level}</p></div><div className="text-2xl">{'★'.repeat(Number(selected.stars||0))}<span className="text-slate-300">{'★'.repeat(5-Number(selected.stars||0))}</span></div></div><div className="grid sm:grid-cols-2 gap-3">{(selected.documents||[]).map((d:Row)=>{const verified=d.status==='VERIFICADO';const src=fileUrl(d.document_url);return <article key={String(d.id||d.document_type)+String(d.created_at)} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-black text-sm text-slate-900">{d.document_name||d.document_type}</p><p className="text-[10px] text-slate-500 mt-1">{d.verification_category||d.document_type}</p></div><span className={`text-[10px] font-black px-2 py-1 rounded-full ${verified?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{verified?'VERIFICADO':d.status}</span></div>{d.admin_feedback&&<p className="mt-2 text-[11px] text-red-700 bg-red-50 rounded-lg p-2">{d.admin_feedback}</p>}<div className="mt-3 flex flex-wrap gap-2">{src&&<a href={src.replace('/api/v1/verification/file/','/api/v1/admin/verifications/file/')} target="_blank" rel="noreferrer" className="text-xs font-black text-blue-700 underline">Abrir documento</a>}{!verified&&d.status!=='RECHAZADO'&&<button disabled={!!busy} onClick={()=>decide(d.id,'VERIFICADO')} className="text-xs font-black text-emerald-700 underline">{busy===String(d.id)?'Guardando…':'Aprobar'}</button>}{d.status!=='VERIFICADO'&&<button disabled={!!busy} onClick={()=>decide(d.id,'RECHAZADO')} className="text-xs font-black text-red-700 underline">Rechazar</button>}</div></article>})}</div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black text-slate-900">Regla de estrellas</p><p className="text-[11px] text-slate-600 mt-1">⭐ Cédula · ⭐⭐⭐ Cédula + 1 área adicional · ⭐⭐⭐⭐ Cédula + 2 áreas adicionales · ⭐⭐⭐⭐⭐ las 5 áreas aprobadas.</p></div></div></div></div>}
 </div>;
};
