import React, { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import { Briefcase, ShieldCheck, Check, X, Sliders, Building2, Users, Wallet, Scale, Settings, RefreshCw, Ban, UserCheck, UserX, Eye, Banknote, FileCheck2 } from 'lucide-react';
import { AdminRolesPanel } from './AdminRolesPanel';

type BankAccount = { id:number; bank_name:string; account_number:string; account_type?:string; account_holder?:string; rnc_cedula?:string; is_active?:boolean; is_primary?:boolean };
const BANKS = ['BHD','Banreservas','Banco Popular'];

export const AdminPanel: React.FC = () => {
 const [stats,setStats]=useState<any>({total_users:0,active_workers:0,total_services:0,escrow_held_rd:0,commission_earned_rd:0,pending_withdrawals:0});
 const [commissionRate,setCommissionRate]=useState(10); const [verifications,setVerifications]=useState<any[]>([]); const [withdrawals,setWithdrawals]=useState<any[]>([]); const [disputes,setDisputes]=useState<any[]>([]); const [bankAccounts,setBankAccounts]=useState<BankAccount[]>([]); const [pendingDeposits,setPendingDeposits]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [msgSuccess,setMsgSuccess]=useState(''); const [msgError,setMsgError]=useState('');
 const [newBank,setNewBank]=useState('BHD'); const [newNumber,setNewNumber]=useState(''); const [newType,setNewType]=useState('CORRIENTE'); const [newHolder,setNewHolder]=useState('SERVIYA DOMINICANA SRL'); const [newRnc,setNewRnc]=useState(''); const [newPrimary,setNewPrimary]=useState(true);
 const notify=(ok?:string,err?:any)=>{if(ok){setMsgSuccess(ok);setMsgError('')}if(err){setMsgError(err?.message||String(err));setMsgSuccess('')}};
 const fetchAdminData=async()=>{setLoading(true);try{const d=await api.get<any>('/admin/stats');if(d){setStats(d.stats||stats);if(d.commission_rate!=null)setCommissionRate(Number(d.commission_rate));setVerifications(d.verifications||[]);setWithdrawals(d.withdrawals||[]);setDisputes(d.disputes||[])}const a=await api.get<any>('/admin/bank-accounts');setBankAccounts(a?.bank_accounts||[]);const p=await api.get<any>('/admin-panel/escrows/pending-deposits');setPendingDeposits(p?.pending_deposits||[])}catch(e){notify(undefined,e)}finally{setLoading(false)}};
 useEffect(()=>{fetchAdminData()},[]);
 const primaryByBank=useMemo(()=>Object.fromEntries(BANKS.map(b=>[b,bankAccounts.find(a=>a.bank_name?.toLowerCase()===b.toLowerCase()&&a.is_primary&&a.is_active)])),[bankAccounts]);
 const approveDeposit=async(id:string)=>{try{await api.post(`/admin-panel/escrows/${id}/approve-deposit`,{notes:'Depósito verificado por Administración.'});notify('Depósito confirmado. Fondos puestos en Custodia y trabajo activado.');await fetchAdminData()}catch(e){notify(undefined,e)}};
 const rejectDeposit=async(id:string)=>{try{await api.post(`/admin-panel/escrows/${id}/reject-deposit`,{notes:'Voucher o depósito no verificado.'});notify('Depósito rechazado.');await fetchAdminData()}catch(e){notify(undefined,e)}};
 const addBank=async(e:React.FormEvent)=>{e.preventDefault();if(!newNumber.trim()){notify(undefined,{message:'Escribe el número de cuenta.'});return}try{await api.post('/admin/bank-accounts',{bank_name:newBank,account_number:newNumber.trim(),account_type:newType,account_holder:newHolder,rnc_cedula:newRnc,is_active:true,is_primary:newPrimary});notify(`Cuenta ${newBank} agregada.`);setNewNumber('');await fetchAdminData()}catch(e){notify(undefined,e)}};
 const toggleBank=async(a:BankAccount)=>{try{await api.put(`/admin/bank-accounts/${a.id}`,{is_active:!a.is_active});notify(`Cuenta ${a.bank_name} ${a.is_active?'desactivada':'activada'}.`);await fetchAdminData()}catch(e){notify(undefined,e)}};
 const setPrimary=async(a:BankAccount)=>{try{await api.put(`/admin/bank-accounts/${a.id}`,{is_primary:true});notify(`Cuenta ${a.bank_name} marcada como principal.`);await fetchAdminData()}catch(e){notify(undefined,e)}};
 const deleteBank=async(a:BankAccount)=>{if(!window.confirm(`¿Eliminar la cuenta ${a.bank_name}?`))return;try{await api.delete(`/admin/bank-accounts/${a.id}`);notify('Cuenta bancaria eliminada.');await fetchAdminData()}catch(e){notify(undefined,e)}};
 const saveCommission=async()=>{try{await api.put('/admin/settings',{commission_percent:commissionRate});notify(`Comisión guardada en ${commissionRate}%.`)}catch(e){notify(undefined,e)}};
 const verifyDoc=async(id:string,status:string)=>{try{await api.patch(`/admin/verifications/${id}`,{status});notify(`Documento ${status.toLowerCase()}.`);await fetchAdminData()}catch(e){notify(undefined,e)}};
 const processWithdrawal=async(id:string,status:string)=>{try{await api.patch(`/admin/withdrawals/${id}`,{status});notify(`Retiro marcado como ${status}.`);await fetchAdminData()}catch(e){notify(undefined,e)}};
 const resolveDispute=async(id:string)=>{try{await api.post(`/admin/disputes/${id}/resolve`,{resolution:'Resolución administrativa SERVIYA'});notify('Disputa resuelta.');await fetchAdminData()}catch(e){notify(undefined,e)}};
 return <div className="space-y-7 pb-12 max-w-7xl mx-auto">
  <header className="bg-red-950 text-white p-6 sm:p-8 rounded-3xl shadow-xl flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 bg-red-900/80 text-red-200 text-xs font-bold px-3 py-1.5 rounded-full mb-2"><ShieldCheck className="w-4 h-4"/> ADMINISTRACIÓN SERVIYA</div><h1 className="text-2xl sm:text-3xl font-black">Consola Central</h1><p className="text-sm text-red-200 mt-1">Usuarios, trabajos, Custodia, depósitos, retiros, bancos, documentos y disputas.</p></div><button onClick={fetchAdminData} disabled={loading} className="bg-white text-red-950 font-black px-4 py-3 rounded-xl text-sm inline-flex items-center justify-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> Actualizar todo</button></header>
  {msgSuccess&&<div className="p-4 bg-emerald-50 text-emerald-800 rounded-2xl border border-emerald-200 text-sm font-semibold">✓ {msgSuccess}</div>}{msgError&&<div className="p-4 bg-red-50 text-red-800 rounded-2xl border border-red-200 text-sm font-semibold">⚠ {msgError}</div>}
  <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[[Users,'Usuarios',stats.total_users],[Briefcase,'Servicios',stats.total_services],[Wallet,'Custodia',`RD$ ${Number(stats.escrow_held_rd||0).toLocaleString()}`],[Banknote,'Retiros pendientes',stats.pending_withdrawals||0]].map(([Icon,label,value])=><div key={String(label)} className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm"><Icon className="w-5 h-5 text-blue-600"/><p className="text-[10px] font-black text-slate-400 uppercase mt-3">{label}</p><p className="text-xl font-black mt-1">{value}</p></div>)}</section>
  <section className="bg-white p-6 rounded-3xl border-2 border-orange-200 shadow-sm space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-black text-lg">Depósitos pendientes de verificación ({pendingDeposits.length})</h2><p className="text-xs text-slate-500">Revisa el voucher y confirma que el dinero llegó antes de ponerlo en Custodia.</p></div><ShieldCheck className="w-6 h-6 text-orange-600"/></div>{!pendingDeposits.length?<p className="text-sm text-slate-400 text-center py-7">No hay depósitos pendientes.</p>:pendingDeposits.map(d=><div key={d.id} className="p-4 rounded-2xl bg-orange-50 border border-orange-200 space-y-4"><div><h3 className="font-black">{d.title}</h3><p className="text-sm">Monto: <b>RD$ {Number(d.total_amount_rd||0).toLocaleString()}</b></p><p className="text-xs text-slate-500">{d.bank_name||'SERVIYA'} • {d.account_number||'—'} • {d.account_type||'—'}</p></div><div className="bg-white p-3 rounded-xl border">{d.voucher_url?<img src={d.voucher_url} alt="Voucher" className="max-h-96 w-full object-contain rounded-lg"/>:<p className="text-red-600 font-bold">Sin voucher. No aprobar.</p>}</div><div className="grid sm:grid-cols-2 gap-2"><button disabled={!d.voucher_url||loading} onClick={()=>approveDeposit(String(d.service_id))} className="bg-emerald-600 disabled:opacity-40 text-white font-black py-3 rounded-xl text-sm"><Check className="inline w-4 h-4 mr-1"/> Confirmé que llegó — Poner en Custodia</button><button disabled={loading} onClick={()=>rejectDeposit(String(d.service_id))} className="bg-white text-red-700 border border-red-200 font-black py-3 rounded-xl text-sm"><X className="inline w-4 h-4 mr-1"/> Rechazar depósito</button></div></div>)}</section>
  <section className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm"><div className="flex items-center gap-2 mb-5"><Building2 className="w-6 h-6 text-blue-600"/><div><h2 className="font-black text-lg">3 cuentas principales de SERVIYA</h2><p className="text-xs text-slate-500">Una cuenta principal para cada banco: BHD, Banreservas y Banco Popular.</p></div></div><div className="grid md:grid-cols-3 gap-3 mb-6">{BANKS.map(bank=>{const a:any=primaryByBank[bank];return <div key={bank} className="rounded-2xl border-2 border-slate-200 p-4"><p className="text-xs font-black uppercase text-slate-500">Cuenta principal</p><h3 className="text-lg font-black mt-1">{bank}</h3>{a?<><p className="font-mono text-sm mt-3">{a.account_number}</p><p className="text-xs text-slate-500 mt-1">{a.account_type||'—'} • {a.account_holder||'SERVIYA'}</p><span className="inline-block mt-3 text-[10px] font-black px-2 py-1 rounded-full bg-emerald-100 text-emerald-700">ACTIVA • PRINCIPAL</span></>:<p className="text-xs text-orange-600 font-bold mt-3">Aún no configurada</p>}</div>})}</div><form onSubmit={addBank} className="p-4 rounded-2xl bg-slate-50 border grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><select value={newBank} onChange={e=>setNewBank(e.target.value)} className="p-3 rounded-xl border bg-white text-sm">{BANKS.map(b=><option key={b}>{b}</option>)}</select><input value={newNumber} onChange={e=>setNewNumber(e.target.value)} placeholder="Número de cuenta" className="p-3 rounded-xl border text-sm bg-white"/><select value={newType} onChange={e=>setNewType(e.target.value)} className="p-3 rounded-xl border bg-white text-sm"><option>CORRIENTE</option><option>AHORRO</option></select><input value={newHolder} onChange={e=>setNewHolder(e.target.value)} placeholder="Titular" className="p-3 rounded-xl border text-sm bg-white"/><button className="bg-blue-600 text-white font-black rounded-xl px-4 py-3 text-sm">+ Agregar cuenta</button></form><div className="mt-5 space-y-2">{bankAccounts.map(a=><div key={a.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3 rounded-xl bg-slate-50 border"><div><b>{a.bank_name}</b> <span className="font-mono text-xs ml-2">{a.account_number}</span><p className="text-[10px] text-slate-500">{a.account_type} • {a.account_holder} • {a.is_active?'ACTIVA':'INACTIVA'} {a.is_primary?'• PRINCIPAL':''}</p></div><div className="flex gap-2"><button onClick={()=>setPrimary(a)} className="text-xs font-bold px-3 py-2 rounded-lg bg-white border">{a.is_primary?'Principal':'Hacer principal'}</button><button onClick={()=>toggleBank(a)} className="text-xs font-bold px-3 py-2 rounded-lg bg-white border">{a.is_active?'Desactivar':'Activar'}</button><button onClick={()=>deleteBank(a)} className="text-xs font-bold px-3 py-2 rounded-lg bg-red-50 text-red-700 border border-red-200">Eliminar</button></div></div>)}</div></section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2 mb-4"><Sliders className="w-5 h-5 text-blue-600"/><h2 className="font-black">Comisión de SERVIYA</h2><button onClick={saveCommission} className="ml-auto bg-blue-600 text-white px-3 py-2 rounded-xl text-xs font-black">Guardar tasa</button></div><div className="flex items-center gap-4"><input type="range" min="1" max="15" step="0.5" value={commissionRate} onChange={e=>setCommissionRate(Number(e.target.value))} className="flex-1"/><b>{commissionRate}%</b></div></section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2 mb-4"><FileCheck2 className="w-5 h-5 text-blue-600"/><h2 className="font-black">Verificación de trabajadores y documentos ({verifications.length})</h2></div>{!verifications.length?<p className="text-sm text-slate-400 py-5 text-center">No hay verificaciones pendientes.</p>:verifications.map(v=><div key={v.id} className="p-4 rounded-xl bg-slate-50 border flex flex-col sm:flex-row justify-between gap-3 mb-2"><div><b>{v.user_name||'Usuario'}</b><p className="text-xs text-slate-500">{v.document_type||'Documento'}: {v.document_number||'—'}</p></div><div className="flex gap-2"><button onClick={()=>verifyDoc(String(v.id),'APROBADO')} className="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-bold"><UserCheck className="inline w-4 h-4"/> Aprobar</button><button onClick={()=>verifyDoc(String(v.id),'RECHAZADO')} className="bg-red-50 text-red-700 px-3 py-2 rounded-lg text-xs font-bold border"><UserX className="inline w-4 h-4"/> Rechazar</button></div></div>)}</section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2 mb-4"><Wallet className="w-5 h-5 text-emerald-600"/><h2 className="font-black">Retiros bancarios ({withdrawals.length})</h2></div>{!withdrawals.length?<p className="text-sm text-slate-400 py-5 text-center">No hay retiros pendientes.</p>:withdrawals.map(w=><div key={w.id} className="p-4 rounded-xl bg-slate-50 border flex flex-col sm:flex-row justify-between gap-3 mb-2"><div><b>RD$ {Number(w.amount_rd||0).toLocaleString()}</b><p className="text-xs text-slate-500">{w.bank_name} • {w.account_type} • {w.account_number}</p></div><div className="flex gap-2"><button onClick={()=>processWithdrawal(String(w.id),'COMPLETADO')} className="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-bold">✓ Marcar pagado</button><button onClick={()=>processWithdrawal(String(w.id),'RECHAZADO')} className="bg-red-50 text-red-700 px-3 py-2 rounded-lg text-xs font-bold border">Rechazar</button></div></div>)}</section>
  <section className="bg-white p-6 rounded-3xl border shadow-sm"><div className="flex items-center gap-2 mb-4"><Scale className="w-5 h-5 text-red-600"/><h2 className="font-black">Centro de disputas ({disputes.length})</h2></div>{!disputes.length?<p className="text-sm text-slate-400 text-center py-7">No hay disputas abiertas.</p>:disputes.map(d=><div key={d.id} className="p-4 rounded-xl bg-slate-50 border flex justify-between gap-3 mb-2"><div><b>{d.title||`Disputa #${d.id}`}</b><p className="text-xs text-slate-500">{d.description||'Revisión administrativa requerida.'}</p></div><button onClick={()=>resolveDispute(String(d.id))} className="bg-blue-600 text-white px-3 py-2 rounded-lg text-xs font-bold">Resolver disputa</button></div>)}</section>
  <AdminRolesPanel />
  <section className="bg-slate-900 text-white p-6 rounded-3xl shadow-lg"><h2 className="font-black text-lg">Administración general</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4"><button onClick={()=>document.getElementById('admin-configuration')?.scrollIntoView({behavior:'smooth',block:'start'})} className="p-3 rounded-xl bg-slate-800 text-xs font-bold"><Users className="inline w-4 h-4 mr-1"/> Gestionar administradores</button><button onClick={()=>document.getElementById('admin-configuration')?.scrollIntoView({behavior:'smooth',block:'start'})} className="p-3 rounded-xl bg-slate-800 text-xs font-bold"><Ban className="inline w-4 h-4 mr-1"/> Roles y permisos</button><button onClick={()=>document.getElementById('admin-configuration')?.scrollIntoView({behavior:'smooth',block:'start'})} className="p-3 rounded-xl bg-slate-800 text-xs font-bold"><Eye className="inline w-4 h-4 mr-1"/> Equipo administrativo</button><button onClick={()=>document.getElementById('admin-configuration')?.scrollIntoView({behavior:'smooth',block:'start'})} className="p-3 rounded-xl bg-slate-800 text-xs font-bold"><Settings className="inline w-4 h-4 mr-1"/> Configuración</button></div></section>
 </div>;
};
