import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {RefreshCw,Activity,CheckCircle2,Landmark,Wallet,Scale,FileCheck2,Headphones,Eye} from 'lucide-react';
import {AdminAlerts} from './AdminAlerts';

type Props={role:string;name:string};
type Row=Record<string,any>;

export const AdminOperationalWorkspace:React.FC<Props>=({role,name})=>{
 const [data,setData]=useState<any>({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{
   if(role==='ADMIN_CUSTODIA'){
     const [o,d,r]=await Promise.all([api.get<any>('/admin-panel/overview'),api.get<any>('/admin-panel/escrows/pending-deposits'),api.get<any>('/admin-panel/escrows/pending-release')]);
     setData({overview:o,deposits:d?.pending_deposits||[],releases:r?.pending_releases||[]});
   }else if(role==='ADMIN_FINANCIERO'){
     const [t,w,o]=await Promise.all([api.get<any>('/admin-panel/transactions'),api.get<any>('/admin/withdrawals'),api.get<any>('/admin-panel/overview')]);
     setData({transactions:t?.transactions||[],withdrawals:w?.withdrawals||[],overview:o});
   }else if(role==='ADMIN_OPERACIONES') setData(await api.get<any>('/admin-panel/services'));
   else if(role==='ADMIN_VERIFICACION'||role==='ADMIN_VERIFICACIONES') setData(await api.get<any>('/admin/verifications'));
   else if(role==='ADMIN_SOPORTE') setData(await api.get<any>('/admin-panel/support'));
   else if(role==='ADMIN_MODERACION') setData(await api.get<any>('/admin-panel/portfolio'));
   else if(role==='ADMIN_DISPUTAS') setData(await api.get<any>('/admin/disputes'));
   else if(role==='AUDITOR') setData(await api.get<any>('/admin-panel/audit'));
   else setData(await api.get<any>('/admin-panel/overview'));
 }catch(e:any){setError(e?.message||'No se pudieron cargar los datos del área.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[role]);
 const act=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setMessage('');setError('');try{const r=await fn();setMessage(r?.message||'Acción realizada correctamente y registrada.');await load()}catch(e:any){setError(e?.message||'La acción no pudo completarse.')}finally{setBusy('')}};
 const title=role==='ADMIN_OPERACIONES'?'Servicios y flujo operativo':role==='ADMIN_FINANCIERO'?'Finanzas y retiros':role==='ADMIN_CUSTODIA'?'Depósitos, Custodia y liberaciones':role.startsWith('ADMIN_VERIFIC')?'Verificación de trabajadores':role==='ADMIN_SOPORTE'?'Soporte y tickets':role==='ADMIN_MODERACION'?'Moderación de contenido':role==='ADMIN_DISPUTAS'?'Disputas y resolución':role==='AUDITOR'?'Auditoría y trazabilidad':'Supervisión general';
 if(loading)return <section className="bg-white rounded-3xl border p-6 flex items-center gap-2 font-bold"><RefreshCw className="w-4 h-4 animate-spin"/>Cargando datos reales de {name}…</section>;
 return <section className="space-y-4">
  <AdminAlerts/>
  {message&&<div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold">✓ {message}</div>}
  {error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">⚠ {error}<button onClick={load} className="ml-3 underline">Reintentar</button></div>}
  <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5 flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase text-slate-400">Herramienta operativa</p><h3 className="text-xl font-black mt-1">{title}</h3><p className="text-xs text-slate-500 mt-1">Conectado a PostgreSQL. Las acciones críticas se guardan en auditoría.</p></div><button onClick={load} className="px-3 py-2 rounded-xl border font-bold inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Actualizar</button></div>
  {role==='ADMIN_CUSTODIA'&&<Custody data={data} busy={busy} act={act}/>} 
  {role==='ADMIN_FINANCIERO'&&<Finance data={data} busy={busy} act={act}/>} 
  {role==='ADMIN_OPERACIONES'&&<ServiceOps rows={data.services||[]} busy={busy} act={act}/>} 
  {(role==='ADMIN_VERIFICACION'||role==='ADMIN_VERIFICACIONES')&&<Verification rows={(data.verifications||[]).filter((r:any)=>r.status==='PENDIENTE')} busy={busy} act={act}/>} 
  {role==='ADMIN_SOPORTE'&&<Support rows={data.tickets||[]} busy={busy} act={act}/>} 
  {role==='ADMIN_MODERACION'&&<Moderation rows={data.portfolio||[]} busy={busy} act={act}/>} 
  {role==='ADMIN_DISPUTAS'&&<Disputes rows={data.disputes||[]} busy={busy} act={act}/>} 
  {role==='AUDITOR'&&<SimpleList title="Registro de auditoría" rows={data.admin_audit||[]} empty="No hay acciones administrativas registradas."/>}
  {role==='ADMINISTRADOR_GENERAL'&&<Overview data={data}/>} 
 </section>;
};

const Box:React.FC<{children:React.ReactNode}>=({children})=><div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5">{children}</div>;
const SimpleList:React.FC<{title:string;rows:Row[];empty:string}>=({title,rows,empty})=><Box><div className="flex items-center gap-2 mb-4"><Activity className="w-5 h-5 text-blue-600"/><h4 className="font-black">{title} ({rows.length})</h4></div>{rows.length?<div className="space-y-2 max-h-[620px] overflow-auto">{rows.slice(0,100).map((r,i)=><div key={String(r.id??i)} className="p-4 rounded-2xl border bg-slate-50"><b>{r.action||r.type||r.subject||'Registro'}</b><p className="text-xs text-slate-500 mt-1">{r.details||r.reference_code||r.description||r.status||'—'}</p></div>)}</div>:<p className="text-sm text-slate-400 text-center py-8">{empty}</p>}</Box>;

const Custody:React.FC<{data:any;busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({data,busy,act})=><div className="space-y-4">
 <Box><div className="grid sm:grid-cols-3 gap-3"><Metric label="En custodia" value={`RD$ ${Number(data.overview?.finance?.custody_rd||0).toLocaleString()}`}/><Metric label="Liberado" value={`RD$ ${Number(data.overview?.finance?.released_rd||0).toLocaleString()}`}/><Metric label="Retiros pendientes" value={data.overview?.finance?.pending_withdrawals||0}/></div></Box>
 <Box><div className="flex items-center gap-2 mb-4"><Landmark className="w-5 h-5 text-orange-600"/><div><h4 className="font-black">Depósitos pendientes de verificación ({data.deposits.length})</h4><p className="text-xs text-slate-500">Voucher recibido → verificación administrativa → Custodia.</p></div></div>{data.deposits.length?data.deposits.map((r:Row)=><div key={String(r.id)} className="p-4 rounded-2xl border bg-orange-50/40 mb-2 flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><b>{r.display_title||r.title||'Depósito'}</b><p className="text-xs text-slate-500 mt-1">{r.bank_name||'Banco'} • RD$ {Number(r.total_amount_rd||0).toLocaleString()} • Voucher: {r.voucher_url?'RECIBIDO':'NO DISPONIBLE'}</p></div><div className="flex gap-2"><button disabled={!r.voucher_url||!!busy} onClick={()=>act('d'+r.service_id,()=>api.post(`/admin-panel/escrows/${r.service_id}/approve-deposit`,{notes:'Verificado desde Administración'}))} className="px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black disabled:opacity-40">Confirmar y poner en Custodia</button><button disabled={!!busy} onClick={()=>act('dr'+r.service_id,()=>api.post(`/admin-panel/escrows/${r.service_id}/reject-deposit`,{notes:'Rechazado desde Administración'}))} className="px-3 py-2 rounded-xl border border-red-200 text-red-700 text-xs font-black">Rechazar</button></div></div>):<p className="text-sm text-slate-400 text-center py-6">No hay depósitos pendientes.</p>}</Box>
 <Box><div className="flex items-center gap-2 mb-4"><CheckCircle2 className="w-5 h-5 text-emerald-600"/><div><h4 className="font-black">Liberaciones pendientes ({data.releases.length})</h4><p className="text-xs text-slate-500">Solo aparecen trabajos aprobados por el cliente y enviados a revisión.</p></div></div>{data.releases.length?data.releases.map((r:Row)=><div key={String(r.id)} className="p-4 rounded-2xl border bg-emerald-50/40 mb-2 flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><b>{r.display_title||r.title||'Servicio'}</b><p className="text-xs text-slate-500 mt-1">Trabajador: {r.worker_name||r.worker_id||'—'} • RD$ {Number(r.amount_rd||0).toLocaleString()} • Recibe RD$ {Number(r.payout_rd||0).toLocaleString()}</p><p className="text-xs mt-1">Estado: PENDIENTE_APROBACION</p></div><button disabled={busy===String(r.service_id)} onClick={()=>act('r'+r.service_id,()=>api.post(`/admin-panel/escrows/${r.service_id}/approve-release`,{notes:'Liberación confirmada desde Custodia SERVIYA'}))} className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black disabled:opacity-50">{busy===String(r.service_id)?'Liberando…':'Liberar custodia y pagar al trabajador'}</button></div>):<p className="text-sm text-slate-400 text-center py-6">No hay trabajos pendientes de liberación.</p>}</Box>
 </div>;

const Finance:React.FC<{data:any;busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({data,busy,act})=><div className="space-y-4"><Box><div className="grid sm:grid-cols-3 gap-3"><Metric label="Retiros pendientes" value={data.overview?.finance?.pending_withdrawals||0}/><Metric label="Monto pendiente" value={`RD$ ${Number(data.overview?.finance?.withdrawals_rd||0).toLocaleString()}`}/><Metric label="Custodia" value={`RD$ ${Number(data.overview?.finance?.custody_rd||0).toLocaleString()}`}/></div></Box><SimpleList title="Movimientos financieros" rows={data.transactions||[]} empty="No hay movimientos registrados."/><Box><div className="flex items-center gap-2 mb-4"><Wallet className="w-5 h-5 text-emerald-600"/><h4 className="font-black">Retiros pendientes ({data.withdrawals.length})</h4></div>{data.withdrawals.length?data.withdrawals.filter((r:any)=>r.status==='PENDIENTE').map((r:Row)=><div key={String(r.id)} className="p-4 rounded-2xl border bg-slate-50 mb-2 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><b>RD$ {Number(r.amount_rd||r.amount||0).toLocaleString()}</b><p className="text-xs text-slate-500 mt-1">{r.bank_name||r.method} • cuenta terminada en •••• {String(r.account_number||'').slice(-4)} • {r.user_id||r.worker_id}</p></div><div className="flex gap-2"><button disabled={!!busy} onClick={()=>act('w'+r.id,()=>api.patch(`/admin/withdrawals/${r.id}`,{status:'COMPLETADO',notes:'Pago confirmado por Administración'}))} className="px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black">Marcar pagado</button><button disabled={!!busy} onClick={()=>act('wr'+r.id,()=>api.patch(`/admin/withdrawals/${r.id}`,{status:'RECHAZADO',notes:'Retiro rechazado por Administración'}))} className="px-3 py-2 rounded-xl border border-red-200 text-red-700 text-xs font-black">Rechazar</button></div></div>):<p className="text-sm text-slate-400 text-center py-6">No hay retiros pendientes.</p>}</Box></div>;
const ServiceOps:React.FC<{rows:Row[];busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({rows})=><SimpleList title="Servicios" rows={rows} empty="No hay servicios registrados."/>;
const Verification:React.FC<{rows:Row[];busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({rows,busy,act})=><Box><div className="flex items-center gap-2 mb-4"><FileCheck2 className="w-5 h-5 text-blue-600"/><h4 className="font-black">Verificaciones pendientes ({rows.length})</h4></div>{rows.length?rows.map(r=><div key={String(r.id)} className="p-4 rounded-2xl border bg-slate-50 mb-2 flex justify-between gap-3"><div><b>Trabajador: {r.user_id||r.worker_id}</b><p className="text-xs text-slate-500">{r.document_type||'Documento'} • {r.status}</p></div><div className="flex gap-2"><button disabled={!!busy} onClick={()=>act('v'+r.id,()=>api.post(`/admin/verifications/${r.id}/approve`,{}))} className="px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black">Aprobar</button><button disabled={!!busy} onClick={()=>act('vr'+r.id,()=>api.patch(`/admin/verifications/${r.id}`,{status:'RECHAZADO'}))} className="px-3 py-2 rounded-xl border border-red-200 text-red-700 text-xs font-black">Rechazar</button></div></div>):<p className="text-sm text-slate-400 text-center py-6">No hay verificaciones pendientes.</p>}</Box>;
const Support:React.FC<{rows:Row[];busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({rows,busy,act})=><Box><div className="flex items-center gap-2 mb-4"><Headphones className="w-5 h-5 text-blue-600"/><h4 className="font-black">Tickets ({rows.length})</h4></div>{rows.length?rows.map(r=><div key={String(r.id)} className="p-4 rounded-2xl border bg-slate-50 mb-2 flex justify-between gap-3"><div><b>{r.subject||'Solicitud'}</b><p className="text-xs text-slate-500">{r.user_name||r.user_id||'Usuario'} • {r.status}</p></div><div className="flex gap-2"><button disabled={!!busy} onClick={()=>act('t'+r.id,()=>api.patch(`/admin-panel/support/${r.id}`,{status:'EN_REVISION',admin_response:`Atendido por Administración`}))} className="px-3 py-2 rounded-xl bg-blue-600 text-white text-xs font-black">En revisión</button><button disabled={!!busy} onClick={()=>act('tr'+r.id,()=>api.patch(`/admin-panel/support/${r.id}`,{status:'RESUELTO',admin_response:`Resuelto por Administración`}))} className="px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black">Resolver</button></div></div>):<p className="text-sm text-slate-400 text-center py-6">No hay tickets.</p>}</Box>;
const Moderation:React.FC<{rows:Row[];busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({rows,busy,act})=><Box><div className="flex items-center gap-2 mb-4"><Eye className="w-5 h-5 text-blue-600"/><h4 className="font-black">Portafolios ({rows.length})</h4></div>{rows.length?rows.map(r=><div key={String(r.id)} className="p-4 rounded-2xl border bg-slate-50 mb-2 flex justify-between gap-3"><div><b>{r.title||'Trabajo'}</b><p className="text-xs text-slate-500">{r.worker_name||r.worker_id||'Trabajador'} • {r.description||'Sin descripción'}</p></div><button disabled={!!busy} onClick={()=>act('p'+r.id,()=>api.patch(`/admin-panel/portfolio/${r.id}/moderation`,{action:'REMOVE',reason:'Retirado por moderación administrativa'}))} className="px-3 py-2 rounded-xl border border-red-200 text-red-700 text-xs font-black">Retirar</button></div>):<p className="text-sm text-slate-400 text-center py-6">No hay elementos de portafolio.</p>}</Box>;
const Disputes:React.FC<{rows:Row[];busy:string;act:(k:string,f:()=>Promise<any>)=>Promise<void>}>=({rows,busy,act})=><Box><div className="flex items-center gap-2 mb-4"><Scale className="w-5 h-5 text-orange-600"/><h4 className="font-black">Disputas abiertas ({rows.length})</h4></div>{rows.length?rows.map(r=><div key={String(r.id)} className="p-4 rounded-2xl border bg-slate-50 mb-2"><b>{r.service_title||'Servicio'} • Disputa #{r.id}</b><p className="text-xs text-slate-500 mt-1">Cliente: {r.client_name||'—'} • Trabajador: {r.worker_name||'—'} • Custodia: {r.escrow_status||'—'}</p><p className="text-sm mt-2">{r.description||'Sin descripción'}</p><div className="flex gap-2 mt-3"><button disabled={!!busy} onClick={()=>act('dc'+r.id,()=>api.post(`/admin/disputes/${r.id}/resolve`,{resolution:'Reembolso al cliente',action:'REFUND_TO_CLIENT'}))} className="px-3 py-2 rounded-xl border border-blue-200 text-blue-700 text-xs font-black">Resolver a favor del cliente</button><button disabled={!!busy} onClick={()=>act('dw'+r.id,()=>api.post(`/admin/disputes/${r.id}/resolve`,{resolution:'Liberación al trabajador',action:'RELEASE_TO_WORKER'}))} className="px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black">Liberar al trabajador</button></div></div>):<p className="text-sm text-slate-400 text-center py-6">No hay disputas abiertas.</p>}</Box>;
const Overview:React.FC<{data:any}>=({data})=><Box><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Usuarios" value={data.users?.total||0}/><Metric label="Servicios" value={data.services?.total||0}/><Metric label="En progreso" value={data.services?.in_progress||0}/><Metric label="Disputas" value={data.moderation?.open_disputes||0}/></div></Box>;
const Metric:React.FC<{label:string;value:React.ReactNode}>=({label,value})=><div className="p-4 rounded-2xl bg-slate-50 border"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="text-xl font-black mt-1">{value}</p></div>;
