import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {UserPlus,Power,RefreshCw,ShieldCheck} from 'lucide-react';

type Administrator={id:string;first_name:string;last_name:string;email:string;phone:string;admin_role:string;role_label?:string;is_active:boolean;is_verified:boolean;is_primary?:boolean;created_at:string};

export const AdminRolesPanel:React.FC=()=>{
 const [admins,setAdmins]=useState<Administrator[]>([]); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 const [form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',password:''});
 const load=async()=>{setLoading(true);setError('');try{const data=await api.get<any>('/admin/super-admin/administrators');setAdmins(data?.administrators||[])}catch(e:any){setError(e?.message||'No se pudo cargar el equipo administrativo.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setMessage('');setError('');try{await api.post('/admin/super-admin/administrators',form);setForm({first_name:'',last_name:'',email:'',phone:'',password:''});setMessage('Administrador adicional creado correctamente.');await load()}catch(e:any){setError(e?.message||'No se pudo crear el administrador.')}finally{setSaving(false)}};
 const toggle=async(a:Administrator)=>{setMessage('');setError('');try{await api.patch(`/admin/super-admin/administrators/${a.id}`,{is_active:!a.is_active});setMessage(`Cuenta de ${a.first_name} ${a.last_name} actualizada.`);await load()}catch(e:any){setError(e?.message||'No se pudo actualizar la cuenta.')}};
 return <section id="admin-configuration" className="bg-white p-5 sm:p-6 rounded-3xl border border-slate-200 shadow-sm space-y-5">
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-2xl bg-blue-50 flex items-center justify-center"><ShieldCheck className="w-6 h-6 text-blue-600"/></div><div><h2 className="font-black text-lg">Administradores</h2><p className="text-xs text-slate-500">SERVIYA usa un único rol administrativo con acceso integral. Puedes añadir otra cuenta administrativa.</p></div></div><button onClick={load} disabled={loading} className="px-3 py-2 rounded-xl border bg-white text-xs font-black inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Actualizar</button></div>
  {message&&<div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold">✓ {message}</div>}{error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs font-bold">⚠ {error}</div>}
  <div className="grid lg:grid-cols-2 gap-5">
   <form onSubmit={create} className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-3"><div className="flex items-center gap-2"><UserPlus className="w-5 h-5 text-blue-600"/><h3 className="font-black">Añadir administrador</h3></div><div className="grid grid-cols-2 gap-2"><input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})} placeholder="Nombre" className="p-3 rounded-xl border bg-white text-sm"/><input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})} placeholder="Apellido" className="p-3 rounded-xl border bg-white text-sm"/></div><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Correo administrativo" className="w-full p-3 rounded-xl border bg-white text-sm"/><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Teléfono" className="w-full p-3 rounded-xl border bg-white text-sm"/><input required minLength={10} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Contraseña (mín. 10 caracteres)" className="w-full p-3 rounded-xl border bg-white text-sm" autoComplete="new-password"/><div className="p-3 rounded-xl bg-blue-50 text-[11px] text-blue-900">La nueva cuenta tendrá el mismo acceso integral: no se seleccionan áreas ni roles.</div><button disabled={saving} className="w-full bg-blue-600 disabled:opacity-50 text-white font-black py-3 rounded-xl text-sm inline-flex items-center justify-center gap-2"><UserPlus className="w-4 h-4"/>{saving?'Creando…':'Crear administrador'}</button></form>
   <div className="space-y-3"><h3 className="font-black">Cuentas administrativas ({admins.length})</h3>{admins.map(a=><div key={a.id} className="p-4 rounded-2xl bg-slate-50 border border-slate-200"><div className="flex items-start justify-between gap-3"><div><b>{a.first_name} {a.last_name}</b><p className="text-xs text-slate-500">{a.email} • {a.phone}</p><p className="text-[10px] font-black text-blue-700 mt-1">ADMINISTRADOR • ACCESO INTEGRAL {a.is_primary?'• PRINCIPAL':''}</p></div><span className={`text-[10px] font-black px-2 py-1 rounded-full ${a.is_active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-500'}`}>{a.is_active?'ACTIVO':'INACTIVO'}</span></div><button onClick={()=>toggle(a)} disabled={!!a.is_primary} className="mt-3 w-full p-2 rounded-lg border bg-white text-xs font-bold inline-flex items-center justify-center gap-1"><Power className="w-3.5 h-3.5"/>{a.is_active?'Desactivar':'Activar'}</button></div>)}</div>
  </div>
 </section>;
};
