import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {ShieldCheck,Wallet,BriefcaseBusiness,Eye,Headphones,Scale,FileCheck2,Users,Settings,LockKeyhole,ArrowLeft,RefreshCw,ChevronRight,LayoutDashboard,Landmark,ClipboardCheck,LifeBuoy,UserRoundCheck,ReceiptText,Briefcase,FileText,Handshake,Clock3,CheckCircle2,AlertTriangle,Search,Banknote,Shield,MessageSquare,Flag,History,UserCheck} from 'lucide-react';
import {AdminPanelV2} from './AdminPanelV2';

type Role={code:string;name:string;description?:string;permissions?:string[]};
type Kpis={total_users:number;active_workers:number;total_services:number;escrow_held_rd:number;commission_earned_rd:number;pending_verifications:number;open_disputes:number;pending_withdrawals:number};
const ICONS:any={SUPER_ADMIN:ShieldCheck,ADMINISTRADOR_GENERAL:Settings,ADMIN_FINANCIERO:Wallet,ADMIN_OPERACIONES:BriefcaseBusiness,ADMIN_CUSTODIA:Landmark,ADMIN_VERIFICACION:FileCheck2,ADMIN_SOPORTE:Headphones,ADMIN_MODERACION:Eye,ADMIN_DISPUTAS:Scale,AUDITOR:LockKeyhole};
const AREA_META:any={
 SUPER_ADMIN:{group:'Dirección',short:'Todo SERVIYA',accent:'bg-red-50 text-red-700 border-red-200'},
 ADMINISTRADOR_GENERAL:{group:'Dirección',short:'Operación general',accent:'bg-blue-50 text-blue-700 border-blue-200'},
 ADMIN_FINANCIERO:{group:'Finanzas',short:'Dinero y cuentas',accent:'bg-emerald-50 text-emerald-700 border-emerald-200'},
 ADMIN_CUSTODIA:{group:'Finanzas',short:'Custodia y liberaciones',accent:'bg-orange-50 text-orange-700 border-orange-200'},
 ADMIN_OPERACIONES:{group:'Operación',short:'Servicios y contratos',accent:'bg-violet-50 text-violet-700 border-violet-200'},
 ADMIN_VERIFICACION:{group:'Operación',short:'Documentos y validación',accent:'bg-cyan-50 text-cyan-700 border-cyan-200'},
 ADMIN_SOPORTE:{group:'Usuarios',short:'Atención y tickets',accent:'bg-sky-50 text-sky-700 border-sky-200'},
 ADMIN_MODERACION:{group:'Usuarios',short:'Contenido y perfiles',accent:'bg-pink-50 text-pink-700 border-pink-200'},
 ADMIN_DISPUTAS:{group:'Control',short:'Conflictos y evidencias',accent:'bg-rose-50 text-rose-700 border-rose-200'},
 AUDITOR:{group:'Control',short:'Consulta y auditoría',accent:'bg-slate-100 text-slate-700 border-slate-300'}
};
const PERMISSION_LABELS:any={USERS:'Usuarios',SERVICES:'Servicios',VERIFICATION:'Verificación',FINANCE:'Finanzas',DISPUTES:'Disputas',SETTINGS:'Configuración',OPERATIONS:'Operaciones',DEPOSITS:'Depósitos',ESCROW:'Custodia',RELEASES:'Liberaciones',SUPPORT:'Soporte',MODERATION:'Moderación',EVIDENCE:'Evidencias',AUDIT:'Auditoría',READ_ONLY:'Solo lectura',ALL:'Acceso total'};

export const AdminRoleWindows:React.FC=()=>{
 const [access,setAccess]=useState<any>(null); const [roles,setRoles]=useState<Role[]>([]); const [selected,setSelected]=useState(''); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(''); const [mobileOpen,setMobileOpen]=useState(false);
 const load=async()=>{setRefreshing(true);setError('');try{const [a,r]=await Promise.all([api.get<any>('/admin/super-admin/access'),api.get<any>('/admin/administrator-roles')]);const role=String(a?.admin_role||'').toUpperCase();const all=(r?.roles||[]).map((x:any)=>({code:String(x.key||x.code||'').toUpperCase(),name:x.label||x.name,description:x.description,permissions:x.permissions||[]}));setAccess(a);setRoles(all);setSelected(prev=>prev||role||'ADMIN_OPERACIONES')}catch(e:any){setError(e?.message||'No se pudo cargar el acceso administrativo.')}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load()},[]);
 const superAdmin=!!access?.is_super_admin; const visible=useMemo(()=>superAdmin?roles:roles.filter(r=>r.code===String(access?.admin_role||'').toUpperCase()),[superAdmin,roles,access]); const current=roles.find(r=>r.code===selected)||visible[0];
 if(loading)return <div className="min-h-screen bg-slate-100 flex items-center justify-center text-slate-600 font-semibold">Cargando áreas administrativas…</div>;
 if(error)return <div className="min-h-screen bg-slate-100 p-6"><div className="max-w-xl mx-auto p-5 rounded-2xl bg-red-50 border border-red-200 text-red-700 font-bold">{error}<button onClick={load} className="block mt-3 px-4 py-2 rounded-xl bg-white border text-sm">Reintentar</button></div></div>;
 if(!current)return <div className="p-6">No hay un rol administrativo asignado.</div>;
 const Icon=ICONS[current.code]||Settings; const meta=AREA_META[current.code]||AREA_META.ADMINISTRADOR_GENERAL; const choose=(code:string)=>{setSelected(code);setMobileOpen(false);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="min-h-screen bg-slate-100 text-slate-800">
  <header className="sticky top-0 z-30 bg-slate-950 text-white border-b border-white/10 shadow-lg"><div className="max-w-[1500px] mx-auto px-3 sm:px-5 py-3 flex items-center justify-between gap-3"><div className="flex items-center gap-3 min-w-0"><div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center shrink-0"><ShieldCheck className="w-5 h-5"/></div><div className="min-w-0"><p className="text-[10px] font-black tracking-[.18em] text-slate-400">SERVIYA • ADMINISTRACIÓN</p><h1 className="font-black text-base sm:text-lg truncate">Centro de administración</h1></div></div><div className="flex items-center gap-2"><span className="hidden sm:inline-flex px-3 py-2 rounded-xl text-[11px] font-black bg-white/10">{superAdmin?'SUPER ADMINISTRADOR • ACCESO TOTAL':current.name}</span><button onClick={load} disabled={refreshing} title="Actualizar" className="w-10 h-10 rounded-xl bg-white/10 hover:bg-white/15 flex items-center justify-center"><RefreshCw className={`w-4 h-4 ${refreshing?'animate-spin':''}`}/></button><button onClick={()=>setMobileOpen(v=>!v)} className="lg:hidden w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><LayoutDashboard className="w-4 h-4"/></button></div></div></header>
  <div className="max-w-[1500px] mx-auto p-3 sm:p-5 lg:grid lg:grid-cols-[270px_minmax(0,1fr)] lg:gap-5">
   <aside className={`${mobileOpen?'block':'hidden'} lg:block mb-4 lg:mb-0`}><div className="lg:sticky lg:top-[76px] bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Áreas administrativas</p><p className="text-sm font-bold mt-1">{superAdmin?'Selecciona una ventana':'Área asignada'}</p></div><nav className="p-2 max-h-[70vh] overflow-y-auto">{visible.map(r=>{const I=ICONS[r.code]||Settings;const active=r.code===current.code;const m=AREA_META[r.code]||meta;return <button key={r.code} onClick={()=>choose(r.code)} className={`w-full text-left p-3 rounded-xl flex items-center gap-3 mb-1 transition ${active?'bg-slate-900 text-white shadow-sm':'hover:bg-slate-50 text-slate-700'}`}><div className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 ${active?'bg-white/10':'bg-slate-100'}`}><I className="w-4 h-4"/></div><div className="min-w-0 flex-1"><p className="text-xs font-black truncate">{r.name}</p><p className={`text-[10px] mt-0.5 truncate ${active?'text-slate-300':'text-slate-400'}`}>{m.short}</p></div>{active&&<ChevronRight className="w-4 h-4 shrink-0"/>}</button>})}</nav><div className="p-3 border-t border-slate-100 bg-slate-50"><p className="text-[10px] text-slate-500 leading-relaxed">{superAdmin?'El Super Administrador cambia de área con la misma sesión, sin volver a iniciar sesión.':'Tu cuenta solo puede acceder al área administrativa asignada.'}</p></div></div></aside>
   <main className="min-w-0 space-y-4"><section className={`rounded-3xl border p-5 sm:p-6 ${meta.accent}`}><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4"><div className="flex gap-4 min-w-0"><div className="w-12 h-12 rounded-2xl bg-white/80 flex items-center justify-center shrink-0"><Icon className="w-6 h-6"/></div><div><p className="text-[10px] font-black uppercase tracking-wider opacity-70">Ventana activa • {meta.group}</p><h2 className="text-xl sm:text-2xl font-black mt-1">{current.name}</h2><p className="text-sm opacity-80 mt-1 max-w-3xl">{current.description}</p></div></div>{superAdmin&&current.code!=='SUPER_ADMIN'&&<button onClick={()=>choose('SUPER_ADMIN')} className="self-start px-3 py-2 rounded-xl bg-white/80 border border-black/5 text-xs font-black inline-flex items-center gap-2"><ArrowLeft className="w-4 h-4"/> Centro total</button>}</div></section>
    {current.code==='SUPER_ADMIN'?<SuperWorkspace roles={visible} choose={choose}/>:<RoleWorkspace role={current}/>} 
   </main>
  </div></div>;
};

const SuperWorkspace:React.FC<{roles:Role[];choose:(r:string)=>void}>=({roles,choose})=><div className="space-y-4"><section className="grid grid-cols-2 sm:grid-cols-4 gap-3"><QuickCard icon={Users} label="Usuarios" value="Gestión central"/><QuickCard icon={Wallet} label="Finanzas" value="Depósitos y retiros"/><QuickCard icon={Landmark} label="Custodia" value="Fondos protegidos"/><QuickCard icon={ClipboardCheck} label="Control" value="Verificación y disputas"/></section><section className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5"><div className="flex items-center gap-3 mb-4"><Shield className="w-5 h-5"/><div><h3 className="font-black text-lg">Ecosistema completo de SERVIYA</h3><p className="text-xs text-slate-500">Cada área tiene su propia ventana de trabajo. Selecciona una para entrar sin cambiar de sesión.</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">{roles.filter(r=>r.code!=='SUPER_ADMIN').map(r=><button key={r.code} onClick={()=>choose(r.code)} className="text-left p-4 rounded-2xl border border-slate-200 hover:border-slate-400 hover:shadow-sm transition"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center">{React.createElement(ICONS[r.code]||Settings,{className:'w-5 h-5'})}</div><div className="min-w-0"><p className="font-black text-sm">{r.name}</p><p className="text-xs text-slate-500 mt-1">{r.description}</p></div></div><div className="mt-3 text-[10px] font-black text-slate-400 uppercase">{(r.permissions||[]).map(p=>PERMISSION_LABELS[p]||p).join(' • ')}</div></button>)}</div></section><section className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100"><h3 className="font-black">Consola maestra</h3><p className="text-xs text-slate-500 mt-1">La consola financiera, usuarios, auditoría, verificación y demás funciones existentes siguen centralizadas aquí.</p></div><div className="p-3 sm:p-5"><AdminPanelV2/></div></section></div>;

const RoleWorkspace:React.FC<{role:Role}>=({role})=>{const [kpis,setKpis]=useState<Kpis|null>(null);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [tab,setTab]=useState('RESUMEN');const [items,setItems]=useState<any[]>([]);const [message,setMessage]=useState('');
 const load=async()=>{setRefreshing(true);setMessage('');try{const k=await api.get<any>('/admin/kpis');setKpis(k?.stats||null);const path=role.code==='ADMIN_OPERACIONES'?'/services':role.code==='ADMIN_VERIFICACION'?'/admin/verifications':role.code==='ADMIN_CUSTODIA'?'/admin-panel/escrows/pending-deposits':role.code==='ADMIN_FINANCIERO'?'/admin/withdrawals':role.code==='ADMIN_DISPUTAS'?'/disputes':role.code==='ADMIN_SOPORTE'?'/support/tickets':role.code==='ADMIN_MODERACION'?'/admin/users':role.code==='AUDITOR'?'/admin/audit-logs':'/admin/users';try{const d=await api.get<any>(path);setItems(d?.services||d?.verifications||d?.deposits||d?.withdrawals||d?.disputes||d?.tickets||d?.users||d?.logs||[])}catch{setItems([])}}catch(e:any){setMessage(e?.message||'No se pudo actualizar el área.')}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load()},[role.code]);
 const cfg=ROLE_CONFIG[role.code]||ROLE_CONFIG.ADMINISTRADOR_GENERAL; if(loading)return <div className="bg-white rounded-3xl border p-6 text-sm font-bold">Cargando ecosistema de {role.name}…</div>;
 return <div className="space-y-4">{message&&<div className="p-3 rounded-2xl bg-amber-50 border border-amber-200 text-amber-800 text-xs font-bold">{message}</div>}<section className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Kpi icon={Users} label="Usuarios" value={String(kpis?.total_users??0)}/><Kpi icon={Briefcase} label="Servicios" value={String(kpis?.total_services??0)}/><Kpi icon={Banknote} label="En custodia" value={`RD$ ${money(kpis?.escrow_held_rd)}`}/><Kpi icon={AlertTriangle} label={role.code==='ADMIN_DISPUTAS'?'Disputas abiertas':'Pendientes'} value={String(role.code==='ADMIN_VERIFICACION'?kpis?.pending_verifications??0:role.code==='ADMIN_FINANCIERO'?kpis?.pending_withdrawals??0:role.code==='ADMIN_DISPUTAS'?kpis?.open_disputes??0:items.length)}/></section><section className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100 flex gap-2 overflow-x-auto">{cfg.tabs.map((t:string)=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded-xl text-xs font-black whitespace-nowrap ${tab===t?'bg-slate-900 text-white':'bg-slate-50 text-slate-600'}`}>{t}</button>)}<button onClick={load} disabled={refreshing} className="ml-auto px-3 py-2 rounded-xl bg-slate-100 text-xs font-black whitespace-nowrap"><RefreshCw className={`w-3 h-3 inline mr-1 ${refreshing?'animate-spin':''}`}/>Actualizar</button></div><div className="p-5"><div className="flex items-start gap-3 mb-5"><div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center">{React.createElement(cfg.icon,{className:'w-5 h-5'})}</div><div><h3 className="font-black text-lg">{tab}</h3><p className="text-xs text-slate-500 mt-1">{cfg.descriptions[tab]||cfg.description}</p></div></div><WorkArea role={role.code} tab={tab} items={items} kpis={kpis}/></div></section><section className="bg-slate-900 text-white rounded-3xl p-5"><div className="flex items-start gap-3"><LockKeyhole className="w-5 h-5 mt-0.5 text-slate-300"/><div><p className="font-black text-sm">Responsabilidad y permisos</p><p className="text-xs text-slate-400 mt-1">{role.description}</p><div className="flex flex-wrap gap-2 mt-3">{(role.permissions||[]).map(p=><span key={p} className="px-2 py-1 rounded-lg bg-white/10 text-[10px] font-bold">{PERMISSION_LABELS[p]||p}</span>)}</div></div></div></section></div>};

const ROLE_CONFIG:any={
 ADMINISTRADOR_GENERAL:{icon:Settings,description:'Supervisión transversal de usuarios, servicios, seguridad, finanzas, verificación y conflictos.',tabs:['RESUMEN','USUARIOS','SERVICIOS','VERIFICACIÓN','FINANZAS','DISPUTAS','CONFIGURACIÓN'],descriptions:{}},
 ADMIN_FINANCIERO:{icon:Wallet,description:'Control del dinero de SERVIYA: depósitos, comisiones, cuentas bancarias, saldos, retiros y trazabilidad.',tabs:['RESUMEN','DEPÓSITOS','CUSTODIA','COMISIONES','CUENTAS','RETIROS','TRAZABILIDAD'],descriptions:{RETIROS:'Revisar solicitudes y procesar retiros de trabajadores mediante las cuentas registradas.',CUENTAS:'Consultar cuentas corporativas y cuentas bancarias persistentes de trabajadores.',TRAZABILIDAD:'Relacionar servicio, cliente, trabajador, depósito, custodia, comisión, liquidación y retiro.'}},
 ADMIN_OPERACIONES:{icon:BriefcaseBusiness,description:'Gestiona el ciclo operativo completo: servicios, postulaciones, contratación, contratos, ejecución, finalización e incidencias.',tabs:['RESUMEN','SERVICIOS','POSTULACIONES','CONTRATOS','EN PROGRESO','COMPLETADOS','INCIDENCIAS','AUDITORÍA'],descriptions:{SERVICIOS:'Buscar y supervisar servicios publicados, categoría, presupuesto, ubicación, cliente y estado.',POSTULACIONES:'Revisar candidatos, perfiles, verificación y propuestas antes de la contratación.',CONTRATOS:'Supervisar contratos pendientes, activos, completados y cancelados.',EN PROGRESO:'Controlar contratación → depósito → custodia → inicio → evidencias → finalización → liberación.',INCIDENCIAS:'Detectar trabajos detenidos, cancelaciones y casos que requieren intervención o disputa.',AUDITORÍA:'Consultar el historial de acciones y cambios del flujo operativo.'}},
 ADMIN_CUSTODIA:{icon:Landmark,description:'Protege los fondos mientras el servicio está en ejecución y controla depósitos, comprobantes, retención y liberación.',tabs:['RESUMEN','DEPÓSITOS PENDIENTES','COMPROBANTES','FONDOS RETENIDOS','LIBERACIONES','REEMBOLSOS','TRAZABILIDAD'],descriptions:{}},
 ADMIN_VERIFICACION:{icon:FileCheck2,description:'Valida identidad y documentación de trabajadores y controla el estado de verificación.',tabs:['RESUMEN','PENDIENTES','CÉDULA','INFOTEP','DOCUMENTOS','VERIFICADOS','RECHAZADOS'],descriptions:{}},
 ADMIN_SOPORTE:{icon:Headphones,description:'Atiende usuarios, tickets, consultas, incidencias y seguimiento hasta el cierre.',tabs:['RESUMEN','TICKETS','USUARIOS','CONVERSACIONES','INCIDENCIAS','ABIERTOS','CERRADOS'],descriptions:{}},
 ADMIN_MODERACION:{icon:Eye,description:'Supervisa perfiles, servicios, portafolios, reseñas y contenido reportado para mantener la calidad de SERVIYA.',tabs:['RESUMEN','PERFILES','SERVICIOS','PORTAFOLIOS','RESEÑAS','REPORTES','ACCIONES'],descriptions:{}},
 ADMIN_DISPUTAS:{icon:Scale,description:'Investiga conflictos entre cliente y trabajador, revisa evidencias y aplica resoluciones sobre la custodia.',tabs:['RESUMEN','ABIERTAS','EN REVISIÓN','EVIDENCIAS','CLIENTE','TRABAJADOR','RESOLUCIONES','HISTORIAL'],descriptions:{}},
 AUDITOR:{icon:LockKeyhole,description:'Consulta actividad, trazabilidad y registros de auditoría. No ejecuta pagos ni cambios críticos.',tabs:['RESUMEN','AUDITORÍA','USUARIOS','SERVICIOS','FINANZAS','CUSTODIA','SEGURIDAD'],descriptions:{}}
};

const WorkArea:React.FC<{role:string;tab:string;items:any[];kpis:Kpis|null}>=({role,tab,items,kpis})=>{if(tab==='RESUMEN')return <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Task title="Cola de trabajo" text="Revisa primero los casos pendientes de tu área y deja cada operación con un estado claro." icon={ClipboardCheck}/><Task title="Flujo SERVIYA" text="Usuario → servicio → postulación → contrato → depósito → custodia → ejecución → liberación → retiro." icon={ReceiptText}/><Task title="Trazabilidad" text="Toda acción administrativa debe poder relacionarse con usuario, servicio, transacción y fecha." icon={History}/><Task title="Escalamiento" text="Cuando un caso exceda tus permisos, envíalo al área correspondiente sin duplicar procesos." icon={ArrowLeft}/></div>;
 if(items.length)return <div className="space-y-2">{items.slice(0,30).map((x:any,i)=><div key={x.id??i} className="p-4 rounded-2xl border border-slate-200 bg-slate-50 flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-white border flex items-center justify-center shrink-0"><RowIcon role={role} tab={tab}/></div><div className="min-w-0 flex-1"><p className="text-sm font-black truncate">{x.title||x.name||x.email||x.document_type||x.status||`Registro ${i+1}`}</p><p className="text-[11px] text-slate-500 mt-1 truncate">{x.description||x.email||x.status||x.created_at||x.submitted_at||'Registro del sistema'}</p></div><span className="text-[10px] font-black px-2 py-1 rounded-lg bg-white border">{x.status||'REGISTRO'}</span></div>)}</div>;
 return <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Task title={tab} text="Esta vista está preparada para trabajar con los registros del backend de esta área. No se muestran botones ficticios: las operaciones se habilitan cuando existe un endpoint real." icon={Search}/><Task title="Indicadores" text={`Usuarios: ${kpis?.total_users??0} • Servicios: ${kpis?.total_services??0} • Disputas: ${kpis?.open_disputes??0} • Retiros pendientes: ${kpis?.pending_withdrawals??0}`} icon={LayoutDashboard}/></div>};
const RowIcon:React.FC<{role:string;tab:string}>=({role,tab})=>{const M:any={ADMIN_OPERACIONES:Briefcase,ADMIN_FINANCIERO:Wallet,ADMIN_CUSTODIA:Landmark,ADMIN_VERIFICACION:UserCheck,ADMIN_SOPORTE:LifeBuoy,ADMIN_MODERACION:Flag,ADMIN_DISPUTAS:Scale,AUDITOR:History,ADMINISTRADOR_GENERAL:Settings};const I=M[role]||ClipboardCheck;return <I className="w-4 h-4 text-slate-600"/>};
const Task:React.FC<{title:string;text:string;icon:any}>=({title,text,icon:Icon})=><div className="p-4 rounded-2xl border border-slate-200 bg-slate-50"><div className="w-9 h-9 rounded-xl bg-white border flex items-center justify-center"><Icon className="w-4 h-4"/></div><p className="font-black text-sm mt-3">{title}</p><p className="text-xs text-slate-500 mt-1 leading-relaxed">{text}</p></div>;
const QuickCard:React.FC<{icon:any;label:string;value:string}>=({icon:Icon,label,value})=><div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-4"><Icon className="w-5 h-5 text-slate-700"/><p className="text-[10px] font-black uppercase text-slate-400 mt-3">{label}</p><p className="text-xs sm:text-sm font-black mt-1">{value}</p></div>;
const Kpi:React.FC<{icon:any;label:string;value:string}>=({icon:Icon,label,value})=><div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-4"><Icon className="w-5 h-5 text-slate-700"/><p className="text-[10px] font-black uppercase text-slate-400 mt-2">{label}</p><p className="text-base font-black mt-1 truncate">{value}</p></div>;
const money=(n:any)=>Number(n||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2});
