import React, { useEffect, useState } from 'react';
import { BellRing, ImagePlus, Pencil, X, Trash2 } from 'lucide-react';
import { api } from '../services/api';

type Announcement = { id:number; title:string; body:string; image_urls:string[]; audience:string; priority:string; action_label?:string|null; action_tab?:string|null; published:boolean; };
type Form = Omit<Announcement,'id'|'published'> & { published:boolean };
const empty: Form = { title:'', body:'', image_urls:[], audience:'TODOS', priority:'NORMAL', action_label:'', action_tab:'', published:true };

export const AdminAnnouncementsPanel: React.FC = () => {
 const [items,setItems]=useState<Announcement[]>([]); const [form,setForm]=useState<Form>(empty); const [editing,setEditing]=useState<number|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const load=async()=>{try{const d=await api.get<{announcements:Announcement[]}>('/announcements/admin');setItems(d.announcements||[])}catch(e:any){setError(e?.message||'No se pudieron cargar los anuncios.')}};
 useEffect(()=>{load()},[]);
 const addFiles=(files:FileList|null)=>{if(!files)return; Array.from(files).slice(0,8-form.image_urls.length).forEach(file=>{if(!file.type.startsWith('image/'))return;if(file.size>700000){setError('Cada foto debe pesar máximo 700 KB.');return;}const r=new FileReader();r.onload=()=>setForm(f=>({...f,image_urls:[...f.image_urls,String(r.result)].slice(0,8)}));r.readAsDataURL(file)})};
 const save=async()=>{if(!form.title.trim()||!form.body.trim()){setError('Completa el título y el texto del anuncio.');return}setSaving(true);setError('');try{const payload={...form,action_label:form.action_label||null,action_tab:form.action_tab||null};if(editing)await api.patch(`/announcements/admin/${editing}`,payload);else await api.post('/announcements/admin',payload);setForm(empty);setEditing(null);await load()}catch(e:any){setError(e?.message||'No se pudo guardar el anuncio.')}finally{setSaving(false)}};
 const edit=(a:Announcement)=>{setEditing(a.id);setForm({...a,action_label:a.action_label||'',action_tab:a.action_tab||''})};
 const remove=async(id:number)=>{if(!confirm('¿Eliminar este anuncio?'))return;await api.delete(`/announcements/admin/${id}`);await load()};
 return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-blue-600">Comunicación oficial</p><h2 className="mt-1 text-xl font-black text-slate-900">📢 Anuncios</h2><p className="mt-1 text-xs text-slate-500">Los anuncios publicados aparecen en la interfaz de la PWA según la audiencia seleccionada.</p></div><BellRing className="w-6 h-6 text-blue-600"/></div>
 {error&&<div className="mt-3 rounded-xl bg-red-50 border border-red-200 text-red-700 p-3 text-xs font-bold">{error}</div>}
 <div className="mt-5 grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="rounded-2xl bg-slate-50 border border-slate-200 p-4"><div className="flex items-center justify-between"><h3 className="font-black">{editing?'Editar anuncio':'Crear anuncio'}</h3>{editing&&<button onClick={()=>{setEditing(null);setForm(empty)}} className="p-2 rounded-lg bg-white"><X className="w-4 h-4"/></button>}</div>
 <input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Título del anuncio" className="mt-4 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none"/><textarea value={form.body} onChange={e=>setForm(f=>({...f,body:e.target.value}))} placeholder="Texto del anuncio" rows={6} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm outline-none"/>
 <div className="mt-3"><label className="inline-flex items-center gap-2 rounded-xl bg-slate-900 text-white px-4 py-3 text-xs font-black cursor-pointer"><ImagePlus className="w-4 h-4"/> Cargar foto<input type="file" accept="image/*" multiple className="hidden" onChange={e=>addFiles(e.target.files)}/></label><span className="ml-2 text-[10px] text-slate-500">Hasta 8 fotos · 700 KB cada una</span></div>
 {!!form.image_urls.length&&<div className="mt-3 grid grid-cols-2 gap-2">{form.image_urls.map((u,i)=><div key={i} className="relative"><img src={u} alt={`Foto ${i+1}`} className="w-full h-28 object-cover rounded-xl border"/><button onClick={()=>setForm(f=>({...f,image_urls:f.image_urls.filter((_,n)=>n!==i)}))} className="absolute top-1 right-1 bg-white rounded-lg p-1 text-red-600"><X className="w-3 h-3"/></button></div>)}</div>}
 <div className="mt-3 grid grid-cols-2 gap-2"><select value={form.audience} onChange={e=>setForm(f=>({...f,audience:e.target.value}))} className="rounded-xl border bg-white px-3 py-3 text-xs"><option value="TODOS">Todos</option><option value="CLIENTE">Clientes</option><option value="TRABAJADOR">Trabajadores</option></select><select value={form.priority} onChange={e=>setForm(f=>({...f,priority:e.target.value}))} className="rounded-xl border bg-white px-3 py-3 text-xs"><option value="NORMAL">Normal</option><option value="IMPORTANTE">Importante</option><option value="URGENTE">Urgente</option></select></div>
 <div className="mt-2 grid grid-cols-2 gap-2"><input value={form.action_label||''} onChange={e=>setForm(f=>({...f,action_label:e.target.value}))} placeholder="Texto del botón (opcional)" className="rounded-xl border bg-white px-3 py-3 text-xs outline-none"/><input value={form.action_tab||''} onChange={e=>setForm(f=>({...f,action_tab:e.target.value}))} placeholder="Destino interno (opcional)" className="rounded-xl border bg-white px-3 py-3 text-xs outline-none"/></div>
 <button disabled={saving} onClick={save} className="mt-3 w-full rounded-xl bg-blue-600 py-3 text-sm font-black text-white disabled:opacity-50">{saving?'Guardando…':editing?'Guardar cambios':'Publicar anuncio'}</button></div>
 <div className="space-y-2"><h3 className="font-black text-slate-900">Anuncios publicados</h3>{items.length===0?<div className="rounded-xl border border-dashed p-6 text-center text-xs text-slate-500">Todavía no hay anuncios.</div>:items.map(a=><div key={a.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase text-blue-600">{a.audience} · {a.priority}</p><h4 className="mt-1 font-black">{a.title}</h4><p className="mt-1 text-xs text-slate-500 line-clamp-2">{a.body}</p>{a.image_urls?.length>0&&<p className="mt-1 text-[10px] text-emerald-600 font-bold">{a.image_urls.length} foto(s)</p>}</div><div className="flex gap-1"><button onClick={()=>edit(a)} className="p-2 rounded-lg bg-slate-100"><Pencil className="w-4 h-4"/></button><button onClick={()=>remove(a.id)} className="p-2 rounded-lg bg-red-50 text-red-600"><Trash2 className="w-4 h-4"/></button></div></div></div>)}</div></div></section>;
};
