import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {CheckCircle2,Clock3,FileCheck2,ShieldCheck,Wallet,Building2,UserRound,ArrowRight,RefreshCw,Image as ImageIcon,AlertTriangle,KeyRound} from 'lucide-react';
const money=(v:any)=>`RD$ ${Number(v||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dt=(v:any)=>v?new Date(v).toLocaleString('es-DO'):'—';
const name=(r:any,p:string)=>[r?.[`${p}_first_name`],r?.[`${p}_last_name`]].filter(Boolean).join(' ')||r?.[`${p}_name`]||r?.[`${p}_email`]||'—';
export const AdminReleaseDossierPanel:React.FC=()=>{
 const [releases,setReleases]=useState<any[]>([]),[details,setDetails]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[notes,setNotes]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);setError('');try{const r=await api.get<any>('/admin-panel/escrows/pending-release');const rows=r?.pending_releases||[];setReleases(rows);const entries=await Promise.all(rows.map(async(x:any)=>{try{return [x.service_id,await api.get<any>(`/admin-panel/escrows/${x.service_id}/release-dossier`)] as const}catch{return [x.service_id,null] as const}}));setDetails(Object.fromEntries(entries))}catch(e:any){setError(e?.message||'No se pudo cargar el expediente.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const act=async(serviceId:string,kind:'approve'|'hold',releaseOtp?:string)=>{setBusy(`${kind}:${serviceId}`);setNotice('');setError('');try{const body={notes:notes[serviceId]||'',...(kind==='approve'?{otp:String(releaseOtp||'').trim()}: {})};const r=await api.post(`/admin-panel/escrows/${serviceId}/${kind==='approve'?'approve-release':'hold-release'}`,body);setNotice(r?.message||'Decisión registrada correctamente.');await load()}catch(e:any){setError(e?.message||'No se pudo completar la decisión.')}finally{setBusy('')}};
 if(loading)return <section className="mb-5 rounded-3xl border-2 border-emerald-100 bg-white p-5"><div className="flex items-center gap-2 font-black"><RefreshCw className="w-4 h-4 animate-spin"/> Cargando expediente de liberaciones…</div></section>;
 return <section className="mb-5 rounded-3xl border-2 border-emerald-100 bg-white p-4 sm:p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-emerald-600">Retiros • Liberación de Custodia</p><h3 className="text-xl font-black mt-1">Expediente completo para decidir la liberación</h3><p className="text-xs text-slate-500 mt-1">Revisa toda la información, evidencia y el código de conformidad antes de decidir.</p></div><button onClick={load} className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center"><RefreshCw className="w-4 h-4"/></button></div>
 {notice&&<div className="mt-3 p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold">✓ {notice}</div>}{error&&<div className="mt-3 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs font-bold">⚠ {error}</div>}
 {!releases.length?<div className="mt-4 p-4 rounded-2xl bg-slate-50 border text-sm text-slate-500">No hay liberaciones de Custodia pendientes de aprobación.</div>:releases.map((r:any)=>{const d=details[r.service_id]?.dossier||r;const contract=details[r.service_id]?.contract;const history=details[r.service_id]?.process_history||[];const financial=details[r.service_id]?.financial_history||[];const audit=details[r.service_id]?.admin_audit||[];const photos=Array.isArray(d.completion_photos)?d.completion_photos:[];return <article key={String(r.service_id)} className="mt-4 rounded-2xl border-2 border-slate-200 overflow-hidden"><div className="p-4 bg-slate-950 text-white"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">LIBERACIÓN PENDIENTE • CUSTODIA {d.escrow_id||'—'}</p><h4 className="text-lg font-black mt-1">{d.title||r.display_title||'Servicio SERVIYA'}</h4><p className="text-xs text-slate-300 mt-1">Servicio: {d.service_id||r.service_id} • Estado: {d.escrow_status||r.status||'PENDIENTE_APROBACION'}</p></div><div className="text-right"><p className="text-2xl font-black">{money(d.total_amount_rd||r.amount_rd)}</p><p className="text-[10px] uppercase font-bold text-slate-400">Monto total en Custodia</p></div></div></div>
 <div className="p-4 space-y-4"><div className="rounded-2xl border-2 border-emerald-200 bg-emerald-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-emerald-700">Dirección exacta del dinero</p><div className="flex flex-col sm:flex-row sm:items-center gap-3 mt-2"><div className="flex-1 rounded-xl bg-white p-3 border"><p className="text-[10px] text-slate-400 font-bold">SE LIBERA DE</p><p className="font-black">{name(d,'client')}</p><p className="text-xs text-slate-600">{d.client_email||'—'} • {d.client_phone||'—'}</p></div><ArrowRight className="w-5 h-5 text-emerald-700 self-center"/><div className="flex-1 rounded-xl bg-white p-3 border"><p className="text-[10px] text-slate-400 font-bold">PARA</p><p className="font-black">{name(d,'worker')}</p><p className="text-xs text-slate-600">{d.worker_email||'—'} • {d.worker_phone||'—'}</p></div></div><p className="text-xs font-black text-emerald-800 mt-3">CLIENTE → TRABAJADOR</p></div>
 <div className="grid lg:grid-cols-2 gap-3"><Info title="Cliente / origen" icon={<UserRound/>} rows={[['Nombre',name(d,'client')],['Cédula',d.client_cedula],['Correo',d.client_email],['Teléfono',d.client_phone],['ID cliente',d.client_id]]}/><Info title="Trabajador / destino" icon={<ShieldCheck/>} rows={[['Nombre',name(d,'worker')],['Cédula',d.worker_cedula],['Correo',d.worker_email],['Teléfono',d.worker_phone],['Especialidad',d.worker_specialties],['INFOTEP',d.worker_has_infotep?'Sí':'No registrado'],['ID trabajador',d.worker_id]]}/></div>
 <Info title="Servicio y ejecución" icon={<CheckCircle2/>} rows={[['Título',d.title],['Descripción',d.description],['Estado',d.service_status],['Precio acordado',money(d.negotiated_price_rd??d.price_rd)],['Fecha',d.service_date],['Hora',d.service_time],['Duración',d.estimated_duration],['Ubicación',[d.municipality,d.province,d.address_approx].filter(Boolean).join(', ')],['Enviado a revisión',d.completion_submitted?'Sí':'No'],['Fecha de envío',dt(d.completion_submitted_at)],['Resumen',d.completion_summary]]}/>
 <div className="rounded-2xl border-2 border-blue-100 bg-blue-50 p-4"><div className="flex items-center gap-2 text-blue-800"><ImageIcon className="w-5 h-5"/><h5 className="font-black text-sm">Evidencia del trabajo terminado</h5></div>{photos.length?<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 mt-3">{photos.map((src:any,i:number)=><div key={i} className="rounded-xl overflow-hidden border bg-white"><img src={src} alt={`Evidencia ${i+1}`} className="w-full aspect-square object-cover"/><p className="text-[10px] font-bold text-slate-500 px-2 py-1">Evidencia {i+1}</p></div>)}</div>:<div className="mt-3 p-3 rounded-xl bg-white border text-xs text-slate-500">No hay fotos registradas.</div>}<div className="mt-3 rounded-xl bg-white border p-3"><p className="text-[10px] font-black uppercase text-slate-400">Resumen del trabajador</p><p className="text-sm font-semibold text-slate-800 mt-1 whitespace-pre-wrap">{d.completion_summary||'Sin resumen registrado.'}</p></div></div>
 <div className="grid lg:grid-cols-2 gap-3"><Info title="Liquidación financiera" icon={<Wallet/>} rows={[['Bruto / Custodia',money(d.gross_service_amount_rd??d.total_amount_rd)],['Comisión SERVIYA',money(d.platform_commission_rd??d.commission_amount_rd)],['% comisión',d.commission_rate_percent!=null?`${d.commission_rate_percent}%`:'—'],['ISR retenido',money(d.isr_withheld_rd)],['ITBIS retenido',money(d.itbis_withheld_rd)],['Neto trabajador',money(d.net_worker_payout_rd??d.worker_payout_rd)],['Estado Custodia',d.escrow_status],['Depósito',dt(d.deposit_created_at)],['Liberación',dt(d.released_at)]]}/><Info title="Cuenta / depósito" icon={<Building2/>} rows={[['Banco',d.bank_name],['Número',d.account_number],['Tipo',d.account_type],['Titular',d.account_holder],['RNC/Cédula',d.rnc_cedula],['Método',d.payment_method],['Voucher',d.voucher_url?'Disponible':'No disponible']]}/></div>
 <div className="grid lg:grid-cols-2 gap-3"><Info title="Contrato digital" icon={<FileCheck2/>} rows={[['Contrato',contract?.contract_number||'—'],['Versión',contract?.version],['Estado',contract?.status],['Hash',contract?.content_hash],['Cliente aceptó',dt(contract?.client_accepted_at)],['Trabajador aceptó',dt(contract?.worker_accepted_at)],['Bloqueado',dt(contract?.locked_at)]]}/><Info title="Trazabilidad" icon={<Clock3/>} rows={[['Fotos',`${photos.length} evidencia(s)`],['Historial',`${history.length} evento(s)`],['Movimientos',`${financial.length} registro(s)`],['Auditoría',`${audit.length} registro(s)`]]}/></div>
 {(history.length||financial.length||audit.length)&&<div className="grid lg:grid-cols-3 gap-3"><List title="Historial de estados" items={history.map((x:any)=>`${dt(x.created_at)} • ${x.status} • ${x.title} — ${x.message}`)}/><List title="Movimientos financieros" items={financial.map((x:any)=>`${dt(x.created_at)} • ${x.type} • ${money(x.amount)} • ${x.status} • ${x.reference_code||''}`)}/><List title="Auditoría" items={audit.map((x:any)=>`${dt(x.timestamp)} • ${x.action} • ${x.details||''}`)}/></div>}
 <div className="rounded-2xl border-2 border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-2"><AlertTriangle className="w-5 h-5 text-amber-700 mt-0.5"/><div><h5 className="font-black text-sm text-amber-900">Decisión de Administración</h5><p className="text-xs text-amber-800 mt-1">Revisa el expediente antes de decidir. Rechazar mantiene los fondos en Custodia.</p></div></div><div className="mt-3 rounded-2xl border-2 border-indigo-200 bg-white p-4"><div className="flex items-center gap-2 text-indigo-800"><KeyRound className="w-5 h-5"/><h5 className="font-black text-sm">Código OTP de confirmación</h5></div><p className="text-[11px] text-slate-500 mt-1">Este código ya está vinculado a esta liberación y se enviará automáticamente al aprobar.</p><div className="mt-2 text-center rounded-xl bg-slate-950 text-white p-4 text-3xl font-black tracking-[0.35em]">{d.release_otp||'NO DISPONIBLE'}</div><p className="text-[10px] text-slate-500 mt-2 text-center">Estado OTP: {d.otp_verified?'Ya validado':'Listo para autorizar esta liberación'}</p></div><textarea value={notes[d.service_id]||''} onChange={e=>setNotes(v=>({...v,[d.service_id]:e.target.value}))} placeholder="Motivo u observaciones de Administración (opcional)" className="mt-3 w-full rounded-xl border border-amber-200 bg-white p-3 text-sm min-h-20"/><div className="mt-3 flex flex-col sm:flex-row gap-2"><button disabled={!!busy||!d.release_otp||String(d.release_otp).length!==6} onClick={()=>act(String(r.service_id),'approve',String(d.release_otp||''))} className="btn-green flex-1">{busy===`approve:${r.service_id}`?'Liberando…':'Aceptar y liberar fondos'}</button><button disabled={!!busy} onClick={()=>act(String(r.service_id),'hold')} className="btn-gray flex-1">{busy===`hold:${r.service_id}`?'Guardando…':'Rechazar liberación / mantener en Custodia'}</button></div></div>
 </div></article>})}</section>;
};
const Info:React.FC<{title:string;icon:React.ReactNode;rows:any[][]}>=({title,icon,rows})=><div className="rounded-2xl border bg-slate-50 p-4"><div className="flex items-center gap-2 mb-3 text-blue-700"><span className="w-5 h-5">{icon}</span><h5 className="font-black text-sm">{title}</h5></div><div className="space-y-1.5">{rows.map(([k,v],i)=><div key={i} className="grid grid-cols-[130px_1fr] gap-2 text-xs"><span className="text-slate-500 font-semibold">{k}</span><span className="font-bold text-slate-800 break-words whitespace-pre-wrap">{v??'—'}</span></div>)}</div></div>;
const List:React.FC<{title:string;items:string[]}>=({title,items})=><div className="rounded-2xl border bg-white p-4"><h5 className="font-black text-sm mb-2">{title}</h5>{items.length?<div className="space-y-2 max-h-52 overflow-y-auto">{items.map((x,i)=><p key={i} className="text-[11px] text-slate-600 border-b last:border-0 pb-2">{x}</p>)}</div>:<p className="text-xs text-slate-400">Sin registros.</p>}</div>;
