import React,{useEffect,useState} from 'react';
import {api} from '../services/api';
import {Building2,UserRound,ShieldCheck,Wallet,FileCheck2,Clock3,CheckCircle2,RefreshCw,ArrowRight} from 'lucide-react';
const money=(v:any)=>`RD$ ${Number(v||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dt=(v:any)=>v?new Date(v).toLocaleString('es-DO'):'—';
const name=(r:any,p:string)=>[r?.[`${p}_first_name`],r?.[`${p}_last_name`]].filter(Boolean).join(' ')||r?.[`${p}_name`]||r?.[`${p}_email`]||'—';
const Info:React.FC<{title:string;icon:React.ReactNode;rows:any[][]}>=({title,icon,rows})=><div className="rounded-2xl border bg-slate-50 p-4"><div className="flex items-center gap-2 mb-3 text-blue-700"><span className="w-5 h-5">{icon}</span><h5 className="font-black text-sm">{title}</h5></div><div className="space-y-1.5">{rows.map(([k,v],i)=><div key={i} className="grid grid-cols-[130px_1fr] gap-2 text-xs"><span className="text-slate-500 font-semibold">{k}</span><span className="font-bold text-slate-800 break-words">{v??'—'}</span></div>)}</div></div>;
export const AdminDepositDossierPanel:React.FC=()=>{
 const [rows,setRows]=useState<any[]>([]),[details,setDetails]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await api.get<any>('/admin-panel/escrows/pending-deposits');const list=r?.pending_deposits||[];setRows(list);const entries=await Promise.all(list.map(async(x:any)=>{try{return [x.service_id,await api.get<any>(`/admin-panel/escrows/${x.service_id}/release-dossier`)] as const}catch{return [x.service_id,null] as const}}));setDetails(Object.fromEntries(entries));}catch(e:any){setError(e?.message||'No se pudo cargar el expediente de depósito y Custodia.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const act=async(id:string,kind:'approve'|'reject')=>{setBusy(`${kind}:${id}`);setNotice('');setError('');try{const endpoint=kind==='approve'?`/admin-panel/escrows/${id}/approve-deposit`:`/admin-panel/escrows/${id}/reject-deposit`;const r=await api.post(endpoint,{notes:kind==='approve'?'Voucher y operación verificados por Administración.':'Voucher/operación rechazada por Administración.'});setNotice(r?.message||'Acción registrada correctamente.');await load()}catch(e:any){setError(e?.message||'No se pudo completar la acción.')}finally{setBusy('')}};
 if(loading)return <section className="mb-5 rounded-3xl border-2 border-blue-100 bg-white p-5"><div className="flex items-center gap-2 font-black"><RefreshCw className="w-4 h-4 animate-spin"/> Cargando expediente completo de Depósito y Custodia…</div></section>;
 return <section className="mb-5 rounded-3xl border-2 border-blue-100 bg-white p-4 sm:p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-blue-600">Depósitos y Custodia</p><h3 className="text-xl font-black mt-1">Expediente completo de cada operación</h3><p className="text-xs text-slate-500 mt-1">La información queda integrada en esta misma ventana: quién deposita, para quién, banco, voucher, contrato, estados, dinero y trazabilidad.</p></div><button onClick={load} className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center"><RefreshCw className="w-4 h-4"/></button></div>
 {notice&&<div className="mt-3 p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold">✓ {notice}</div>}{error&&<div className="mt-3 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs font-bold">⚠ {error}</div>}
 {!rows.length?<div className="mt-4 p-4 rounded-2xl bg-slate-50 border text-sm text-slate-500">No hay depósitos pendientes de verificación.</div>:rows.map((r:any)=>{const d=details[r.service_id]?.dossier||r;const contract=details[r.service_id]?.contract;const history=details[r.service_id]?.process_history||[];const financial=details[r.service_id]?.financial_history||[];const audit=details[r.service_id]?.admin_audit||[];return <article key={String(r.service_id)} className="mt-4 rounded-2xl border-2 border-slate-200 overflow-hidden"><div className="p-4 bg-slate-950 text-white"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">DEPÓSITO • CUSTODIA {d.escrow_id||'—'}</p><h4 className="text-lg font-black mt-1">{d.title||r.display_title||'Servicio SERVIYA'}</h4><p className="text-xs text-slate-300 mt-1">Servicio: {d.service_id||r.service_id} • Estado: {d.escrow_status||'PENDIENTE_VERIFICACION'}</p></div><div className="text-right"><p className="text-2xl font-black">{money(d.total_amount_rd||r.total_amount_rd)}</p><p className="text-[10px] uppercase font-bold text-slate-400">Monto recibido / en proceso de verificación</p></div></div></div>
 <div className="p-4 space-y-4"><div className="rounded-2xl border-2 border-blue-200 bg-blue-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-blue-700">Destino del depósito</p><div className="flex flex-col sm:flex-row sm:items-center gap-3 mt-2"><div className="flex-1 rounded-xl bg-white p-3 border"><p className="text-[10px] text-slate-400 font-bold">DEPOSITA</p><p className="font-black">{name(d,'client')}</p><p className="text-xs text-slate-600">{d.client_email||'—'} • {d.client_phone||'—'}</p></div><ArrowRight className="w-5 h-5 text-blue-700 self-center"/><div className="flex-1 rounded-xl bg-white p-3 border"><p className="text-[10px] text-slate-400 font-bold">DINERO DESTINADO A</p><p className="font-black">{name(d,'worker')}</p><p className="text-xs text-slate-600">{d.worker_email||'—'} • {d.worker_phone||'—'}</p></div></div><p className="text-xs font-black text-blue-800 mt-3">ESTE DEPÓSITO CORRESPONDE AL SERVICIO Y QUEDA DESTINADO AL TRABAJADOR INDICADO.</p></div>
 <div className="grid lg:grid-cols-2 gap-3"><Info title="Cliente / depositante" icon={<UserRound/>} rows={[['Nombre',name(d,'client')],['Cédula',d.client_cedula],['Correo',d.client_email],['Teléfono',d.client_phone],['ID cliente',d.client_id]]}/><Info title="Trabajador / beneficiario" icon={<ShieldCheck/>} rows={[['Nombre',name(d,'worker')],['Cédula',d.worker_cedula],['Correo',d.worker_email],['Teléfono',d.worker_phone],['Especialidad',d.worker_specialties],['INFOTEP',d.worker_has_infotep?'Sí':'No registrado'],['ID trabajador',d.worker_id]]}/></div>
 <Info title="Servicio relacionado" icon={<CheckCircle2/>} rows={[['Título',d.title],['Descripción',d.description],['Estado',d.service_status],['Precio acordado',money(d.negotiated_price_rd??d.price_rd)],['Fecha',d.service_date],['Hora',d.service_time],['Duración',d.estimated_duration],['Ubicación',[d.municipality,d.province,d.address_approx].filter(Boolean).join(', ')]]}/>
 <div className="grid lg:grid-cols-2 gap-3"><Info title="Dinero y Custodia" icon={<Wallet/>} rows={[['Total depositado',money(d.total_amount_rd)],['Bruto servicio',money(d.gross_service_amount_rd??d.total_amount_rd)],['Comisión SERVIYA',money(d.platform_commission_rd??d.commission_amount_rd)],['% comisión',d.commission_rate_percent!=null?`${d.commission_rate_percent}%`:'—'],['ISR retenido',money(d.isr_withheld_rd)],['ITBIS retenido',money(d.itbis_withheld_rd)],['Neto trabajador',money(d.net_worker_payout_rd??d.worker_payout_rd)],['Estado Custodia',d.escrow_status],['Recibido',dt(d.deposit_created_at)],['Liberado',dt(d.released_at)]]}/><Info title="Cuenta SERVIYA receptora" icon={<Building2/>} rows={[['Banco',d.bank_name],['Número',d.account_number],['Tipo',d.account_type],['Titular',d.account_holder],['RNC/Cédula',d.rnc_cedula],['Método',d.payment_method],['Voucher',d.voucher_url?'Disponible':'No disponible']]}/></div>
 <div className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between gap-2 mb-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Comprobante bancario</p><p className="text-sm font-black">{d.voucher_url?'Voucher recibido y disponible para revisión':'Voucher no disponible'}</p></div>{d.voucher_url&&<a href={d.voucher_url} target="_blank" rel="noreferrer" className="text-xs font-black text-blue-700 underline">Abrir comprobante</a>}</div>{d.voucher_url?<img src={d.voucher_url} alt="Voucher real del depósito" className="w-full max-h-[620px] object-contain rounded-xl border bg-slate-100"/>:<div className="p-5 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">No hay voucher almacenado. No aprobar este depósito.</div>}</div>
 <div className="grid lg:grid-cols-2 gap-3"><Info title="Contrato digital" icon={<FileCheck2/>} rows={[['Contrato',contract?.contract_number],['Estado',contract?.status],['Hash',contract?.content_hash],['Cliente aceptó',dt(contract?.client_accepted_at)],['Trabajador aceptó',dt(contract?.worker_accepted_at)],['Hash aceptación cliente',contract?.client_acceptance_hash],['Hash aceptación trabajador',contract?.worker_acceptance_hash],['Bloqueado',dt(contract?.locked_at)]]}/><Info title="Trazabilidad" icon={<Clock3/>} rows={[['Historial de proceso',`${history.length} evento(s)`],['Movimientos financieros',`${financial.length} registro(s)`],['Auditoría administrativa',`${audit.length} registro(s)`],['ID Custodia',d.escrow_id],['Fecha de depósito',dt(d.deposit_created_at)]]}/></div>
 {(history.length||financial.length||audit.length)&&<div className="grid lg:grid-cols-3 gap-3"><List title="Historial de estados" items={history.map((x:any)=>`${dt(x.created_at)} • ${x.status} • ${x.title} — ${x.message}`)}/><List title="Movimientos financieros" items={financial.map((x:any)=>`${dt(x.created_at)} • ${x.type} • ${money(x.amount)} • ${x.status} • ${x.reference_code||''}`)}/><List title="Auditoría administrativa" items={audit.map((x:any)=>`${dt(x.timestamp)} • ${x.action} • ${x.details||''}`)}/></div>}
 <div className="flex flex-wrap gap-2 pt-1"><button disabled={!!busy||!d.voucher_url} onClick={()=>act(String(r.service_id),'approve')} className="btn-green">{busy===`approve:${r.service_id}`?'Verificando…':'Confirmar depósito y pasar a Custodia'}</button><button disabled={!!busy} onClick={()=>act(String(r.service_id),'reject')} className="btn-red">{busy===`reject:${r.service_id}`?'Rechazando…':'Rechazar depósito'}</button></div></div></article>})}</section>;
};
const List:React.FC<{title:string;items:string[]}>=({title,items})=><div className="rounded-2xl border bg-white p-4"><h5 className="font-black text-sm mb-2">{title}</h5>{items.length?<div className="space-y-2 max-h-52 overflow-y-auto">{items.map((x,i)=><p key={i} className="text-[11px] text-slate-600 border-b last:border-0 pb-2">{x}</p>)}</div>:<p className="text-xs text-slate-400">Sin registros.</p>}</div>;
