import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {AdminPanelV2} from './AdminPanelV2';
import {AdminGlobalActivity} from './AdminGlobalActivity';
import {AdminOperationalWorkspace} from './AdminOperationalWorkspace';
import {ShieldCheck,Settings,Wallet,BriefcaseBusiness,Landmark,FileCheck2,Headphones,Eye,Scale,LockKeyhole,RefreshCw,LayoutDashboard,ChevronRight} from 'lucide-react';

type Role={code:string;name:string;description?:string;permissions?:string[]};
const ICONS:any={SUPER_ADMIN:ShieldCheck,ADMINISTRADOR_GENERAL:Settings,ADMIN_FINANCIERO:Wallet,ADMIN_OPERACIONES:BriefcaseBusiness,ADMIN_CUSTODIA:Landmark,ADMIN_VERIFICACION:FileCheck2,ADMIN_VERIFICACIONES:FileCheck2,ADMIN_SOPORTE:Headphones,ADMIN_MODERACION:Eye,ADMIN_DISPUTAS:Scale,AUDITOR:LockKeyhole};
const GROUP:any={SUPER_ADMIN:'Dirección',ADMINISTRADOR_GENERAL:'Dirección',ADMIN_FINANCIERO:'Finanzas',ADMIN_OPERACIONES:'Operación',ADMIN_CUSTODIA:'Finanzas',ADMIN_VERIFICACION:'Operación',ADMIN_VERIFICACIONES:'Operación',ADMIN_SOPORTE:'Usuarios',ADMIN_MODERACION:'Usuarios',ADMIN_DISPUTAS:'Control',AUDITOR:'Control'};

export const AdminRoleWindows:React.FC=()=>{
 const [access,setAccess]=useState<any>(null);const [roles,setRoles]=useState<Role[]>([]);const [selected,setSelected]=useState('');const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [mobileOpen,setMobileOpen]=useState(false);
 const load=async()=>{setRefreshing(true);setError('');try{const [a,r]=await Promise.all([api.get<any>('/admin/super-admin/access'),api.get<any>('/admin/administrator-roles')]);const role=String(a?.admin_role||'').toUpperCase();const all=(r?.roles||[]).map((x:any)=>({code:String(x.key||x.code||'').toUpperCase(),name:x.label||x.name,description:x.description,permissions:x.permissions||[]}));setAccess(a);setRoles(all);setSelected(prev=>prev||role||'ADMIN_OPERACIONES')}catch(e:any){setError(e?.message||'No se pudo cargar el acceso administrativo.')}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{load()},[]);
 const superAdmin=!!access?.is_super_admin;const visible=useMemo(()=>superAdmin?roles:roles.filter(r=>r.code===String(access?.admin_role||'').toUpperCase()),[superAdmin,roles,access]);const current=roles.find(r=>r.code===selected)||visible[0];
 if(loading)return <div className="min-h-screen bg-slate-100 flex items-center justify-center text-slate-600 font-semibold">Cargando áreas administrativas…</div>;
 if(error)return <div className="min-h-screen bg-slate-100 p-6"><div className="max-w-xl mx-auto p-5 rounded-2xl bg-red-50 border border-red-200 text-red-700 font-bold">{error}<button onClick={load} className="block mt-3 px-4 py-2 rounded-xl bg-white border text-sm">Reintentar</button></div></div>;
 if(!current)return <div className="p-6">No hay un rol administrativo asignado.</div>;
 const choose=(code:string)=>{setSelected(code);setMobileOpen(false);window.scrollTo({top:0,behavior:'smooth'})};const Icon=ICONS[current.code]||Settings;
 return <div className="min-h-screen bg-slate-100 text-slate-800"><header className="sticky top-0 z-30 bg-slate-950 text-white border-b border-white/10 shadow-lg"><div className="max-w-[1500px] mx-auto px-3 sm:px-5 py-3 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><ShieldCheck className="w-5 h-5"/></div><div><p className="text-[10px] font-black tracking-[.18em] text-slate-400">SERVIYA • ADMINISTRACIÓN</p><h1 className="font-black text-base sm:text-lg">Centro de administración</h1></div></div><div className="flex items-center gap-2"><span className="hidden sm:inline-flex px-3 py-2 rounded-xl bg-red-500/15 text-red-200 text-[11px] font-black">{superAdmin?'SUPER ADMINISTRADOR • CONTROL TOTAL':current.name}</span><button onClick={load} disabled={refreshing} className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><RefreshCw className={`w-4 h-4 ${refreshing?'animate-spin':''}`}/></button><button onClick={()=>setMobileOpen(v=>!v)} className="lg:hidden w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center"><LayoutDashboard className="w-4 h-4"/></button></div></div></header>
 <div className="max-w-[1500px] mx-auto p-3 sm:p-5 lg:grid lg:grid-cols-[270px_minmax(0,1fr)] lg:gap-5"><aside className={`${mobileOpen?'block':'hidden'} lg:block mb-4 lg:mb-0`}><div className="lg:sticky lg:top-[76px] bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Áreas administrativas</p><p className="text-sm font-bold mt-1">{superAdmin?'Acceso total del Super Administrador':'Área asignada'}</p></div><nav className="p-2 max-h-[70vh] overflow-y-auto">{visible.map(r=>{const I=ICONS[r.code]||Settings;const active=r.code===current.code;return <button key={r.code} onClick={()=>choose(r.code)} className={`w-full text-left p-3 rounded-xl flex items-center gap-3 mb-1 ${active?'bg-slate-900 text-white':'hover:bg-slate-50 text-slate-700'}`}><div className={`w-9 h-9 rounded-lg flex items-center justify-center ${active?'bg-white/10':'bg-slate-100'}`}><I className="w-4 h-4"/></div><div className="min-w-0 flex-1"><p className="text-xs font-black truncate">{r.name}</p><p className={`text-[10px] mt-0.5 truncate ${active?'text-slate-300':'text-slate-400'}`}>{GROUP[r.code]||'Administración'}</p></div>{active&&<ChevronRight className="w-4 h-4"/>}</button>})}</nav></div></div></aside>
 <main className="min-w-0 space-y-4"><section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6 shadow-sm"><div className="flex items-start gap-4"><div className="w-12 h-12 rounded-2xl bg-slate-100 flex items-center justify-center"><Icon className="w-6 h-6"/></div><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">Ventana activa • {GROUP[current.code]||'Administración'}</p><h2 className="text-xl sm:text-2xl font-black mt-1">{current.name}</h2><p className="text-sm text-slate-500 mt-1 max-w-4xl">{current.description||'Área administrativa protegida por permisos y conectada a los datos reales de SERVIYA.'}</p></div></div></section>
 {superAdmin&&current.code==='SUPER_ADMIN'?<><div className="bg-slate-900 text-white rounded-3xl p-5"><h3 className="text-lg font-black">Control total del Super Administrador</h3><p className="text-sm text-slate-300 mt-1">Una sola sesión, una sola consola oficial y acceso transversal a todas las áreas.</p></div><div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-3 sm:p-5"><AdminPanelV2/></div><AdminGlobalActivity/></>:<AdminOperationalWorkspace role={current.code} name={current.name}/>}</main></div></div>;
};
