import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {Check,X,RefreshCw,ShieldCheck,ArrowLeft,ReceiptText,Building2,Clock3,WalletCards} from 'lucide-react';
const BANKS=['Banreservas','Banco Popular','BHD'];
const normalizeBank=(value:any)=>String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const matchesBank=(value:any,bank:string)=>{const v=normalizeBank(value);if(bank==='Banreservas')return v==='banreservas'||v.includes('reservas');if(bank==='Banco Popular')return v==='bancopopular'||v==='popular';return v==='bhd'||v.includes('bhd');};
export const AdminVoucherVerificationWindow:React.FC<{onClose:()=>void}>=({onClose})=>{
 const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState('');const [error,setError]=useState('');const [bank,setBank]=useState('Banreservas');
 const load=async()=>{setLoading(true);setError('');try{const d=await api.get<any>('/admin-panel/escrows/pending-deposits');setItems(d?.pending_deposits||[])}catch(e:any){setError(e?.message||'No se pudieron cargar las verificaciones de voucher.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(d=>matchesBank(d.bank_name,bank)),[items,bank]);
 const totals=useMemo(()=>({count:filtered.length,total:filtered.reduce((n,d)=>n+Number(d.total_amount_rd||0),0)}),[filtered]);
 const action=async(serviceId:string,approved:boolean)=>{setBusy(serviceId);setMessage('');setError('');try{if(approved)await api.post(`/admin-panel/escrows/${serviceId}/approve-deposit`,{notes:`Voucher verificado por Administración — sesión ${bank}.`});else await api.post(`/admin-panel/escrows/${serviceId}/reject-deposit`,{notes:`Voucher rechazado por Administración — sesión ${bank}.`});setMessage(approved?'Voucher confirmado. Fondos puestos en Custodia y servicio activado.':'Voucher rechazado correctamente.');await load()}catch(e:any){setError(e?.message||'No se pudo procesar el voucher.')}finally{setBusy(null)}};
 return <div className="fixed inset-0 z-[100] bg-slate-100 overflow-y-auto"><div className="min-h-screen max-w-6xl mx-auto p-4 sm:p-6"><header className="bg-orange-950 text-white rounded-3xl p-5 sm:p-7 shadow-xl flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-center gap-3"><button onClick={onClose} className="w-10 h-10 rounded-xl bg-white/10 hover:bg-white/20 flex items-center justify-center"><ArrowLeft/></button><div><div className="inline-flex items-center gap-2 text-orange-200 text-xs font-black"><ShieldCheck className="w-4 h-4"/> SESIÓN DE VERIFICACIONES</div><h1 className="text-xl sm:text-2xl font-black mt-1">Depósitos bancarios por sesión</h1><p className="text-xs sm:text-sm text-orange-200 mt-1">Cada banco tiene su propia etapa de control. Los vouchers no se mezclan.</p></div></div><button onClick={load} disabled={loading} className="bg-white text-orange-950 rounded-xl px-3 py-2 font-black text-xs inline-flex items-center gap-2"><RefreshCw className={loading?'animate-spin':''}/> Actualizar</button></header>
 <div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3">{BANKS.map(b=><button key={b} onClick={()=>setBank(b)} className={`rounded-2xl border-2 p-4 text-left transition ${bank===b?'border-orange-500 bg-orange-50 shadow-sm':'border-slate-200 bg-white'}`}><div className="flex items-center gap-2"><Building2 className="w-5 h-5 text-orange-600"/><span className="font-black text-sm">{b}</span></div><p className="text-xs text-slate-500 mt-2">Sesión exclusiva de depósitos</p><p className="text-lg font-black mt-1">{items.filter(d=>matchesBank(d.bank_name,b)).length} pendientes</p></button>)}</div>
 <div className="mt-5 bg-white rounded-3xl border border-slate-200 p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="inline-flex items-center gap-2 text-orange-700 text-xs font-black"><WalletCards className="w-4 h-4"/> BANCO ACTIVO</div><h2 className="font-black text-xl mt-1">{bank}</h2><p className="text-xs text-slate-500">Etapa: <b>Voucher recibido → Verificación → Custodia</b></p></div><div className="flex gap-5"><div><p className="text-[10px] uppercase font-black text-slate-400">Pendientes</p><p className="text-xl font-black">{totals.count}</p></div><div><p className="text-[10px] uppercase font-black text-slate-400">Total</p><p className="text-xl font-black">RD$ {totals.total.toLocaleString()}</p></div></div></div></div>
 {message&&<div className="mt-4 p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-bold">✓ {message}</div>}{error&&<div className="mt-4 p-4 rounded-2xl bg-red-50 border border-red-200 text-red-700 text-sm font-bold">⚠ {error}</div>}
 <div className="mt-5 flex items-center justify-between"><div><h2 className="font-black text-lg">Pendientes de {bank} ({filtered.length})</h2><p className="text-xs text-slate-500">Revisa el voucher, identifica al depositante y decide si pasa a Custodia.</p></div><ReceiptText className="w-7 h-7 text-orange-600"/></div>
 <div className="mt-4 space-y-4">{!filtered.length?<div className="bg-white rounded-2xl border p-8 text-center"><Clock3 className="w-8 h-8 mx-auto text-slate-300"/><p className="text-sm text-slate-400 mt-2">No hay vouchers pendientes de {bank}.</p></div>:filtered.map(d=><article key={d.id} className="bg-white rounded-3xl border-2 border-orange-100 shadow-sm p-4 sm:p-6"><div className="flex flex-col lg:flex-row justify-between gap-4"><div><h3 className="font-black text-lg">{d.display_title||d.title||'Depósito'}</h3><p className="text-sm mt-1">RD$ {Number(d.total_amount_rd||0).toLocaleString()} • {d.bank_name||bank} • {d.account_number||'—'}</p><p className="text-xs text-slate-500 mt-2">Depositante: <b>{d.client_name||d.client_email||'Cliente'}</b> • {d.client_phone||'Sin teléfono'} • Servicio: {d.title||'—'}</p><p className="text-xs text-slate-500 mt-1">Recibido: {d.created_at?new Date(d.created_at).toLocaleString():'—'}</p></div><span className="self-start text-xs font-black px-3 py-1.5 rounded-full bg-orange-100 text-orange-700">PENDIENTE_VERIFICACION</span></div>{d.voucher_url?<img src={d.voucher_url} alt="Voucher de depósito" className="mt-4 max-h-[520px] w-full object-contain rounded-2xl bg-slate-50 border"/>:<div className="mt-4 p-4 rounded-xl bg-red-50 text-red-700 text-sm font-bold">No hay voucher. No aprobar.</div>}<div className="grid sm:grid-cols-2 gap-3 mt-4"><button disabled={!d.voucher_url||!!busy} onClick={()=>action(String(d.service_id),true)} className="bg-emerald-600 disabled:opacity-40 text-white font-black py-3 rounded-xl text-sm"><Check className="inline w-4 h-4 mr-1"/> Confirmar y poner en Custodia</button><button disabled={!!busy} onClick={()=>action(String(d.service_id),false)} className="bg-white border border-red-200 text-red-700 font-black py-3 rounded-xl text-sm"><X className="inline w-4 h-4 mr-1"/> Rechazar voucher</button></div></article>)}</div></div></div>;
};
