import React,{useCallback,useEffect,useState} from 'react';
import {api} from '../services/api';
import {Clock3,Search,RefreshCw,ShieldCheck,Filter} from 'lucide-react';

type Item={event_type:string;id:string;created_at:string;action:string;entity_type:string;entity_id?:string|null;message?:string|null;status?:string|null;actor_id?:string|null;actor_name?:string|null;actor_email?:string|null};
const fmt=(v:any)=>v?new Date(v).toLocaleString('es-DO',{dateStyle:'short',timeStyle:'medium'}):'—';

export const AdminHistoryPanel:React.FC=()=>{
 const [items,setItems]=useState<Item[]>([]),[q,setQ]=useState(''),[eventType,setEventType]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[total,setTotal]=useState(0);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({limit:'200'});if(q.trim())params.set('q',q.trim());if(eventType)params.set('event_type',eventType);if(status)params.set('status',status);const r=await api.get<any>(`/admin-panel/history?${params.toString()}`);setItems(r?.items||[]);setTotal(Number(r?.total||0))}catch(e:any){setError(e?.message||'No se pudo cargar el historial.')}finally{setLoading(false)}},[q,eventType,status]);
 useEffect(()=>{load()},[load]);
 return <section className="rounded-3xl border border-slate-200 bg-white shadow-sm overflow-hidden">
  <div className="p-5 sm:p-6 border-b bg-slate-950 text-white">
   <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 text-xs font-black text-slate-300"><Clock3 className="w-4 h-4"/> HISTORIAL Y AUDITORÍA</div><h2 className="text-xl sm:text-2xl font-black mt-1">Historial de todo lo realizado</h2><p className="text-sm text-slate-300 mt-1">Busca cualquier caso, usuario, servicio, operación, aprobación, rechazo o cambio registrado.</p></div><button onClick={load} disabled={loading} className="px-4 py-2.5 rounded-xl bg-white text-slate-950 font-black text-sm inline-flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Actualizar</button></div>
   <div className="grid md:grid-cols-[1fr_auto_auto] gap-2 mt-5"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}} placeholder="Buscar usuario, correo, servicio, ID, acción, depósito, retiro..." className="w-full pl-10 pr-3 py-3 rounded-xl bg-white text-slate-900 outline-none"/></div><select value={eventType} onChange={e=>setEventType(e.target.value)} className="px-3 py-3 rounded-xl bg-white text-slate-900 font-bold"><option value="">Todo</option><option value="AUDITORIA">Auditoría</option><option value="PROCESO">Procesos</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="px-3 py-3 rounded-xl bg-white text-slate-900 font-bold"><option value="">Todos los estados</option><option>PENDIENTE</option><option>ACEPTADO</option><option>APROBADO</option><option>RECHAZADO</option><option>COMPLETADO</option><option>EN_PROGRESO</option><option>LIBERADO</option><option>RETENIDO</option><option>EN_DISPUTA</option></select></div>
  </div>
  {error&&<div className="m-4 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 font-bold text-sm">⚠ {error}</div>}
  <div className="p-4"><div className="flex items-center justify-between text-xs text-slate-500 mb-3"><span>{total.toLocaleString('es-DO')} registros encontrados</span><span className="inline-flex items-center gap-1"><Filter className="w-3.5 h-3.5"/> Búsqueda global</span></div>{items.length?<div className="space-y-2">{items.map((x,i)=><article key={`${x.event_type}-${x.id}-${i}`} className="rounded-2xl border border-slate-200 p-4 hover:bg-slate-50"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`px-2 py-1 rounded-full text-[10px] font-black ${x.event_type==='AUDITORIA'?'bg-indigo-100 text-indigo-700':'bg-blue-100 text-blue-700'}`}>{x.event_type}</span>{x.status&&<span className="px-2 py-1 rounded-full text-[10px] font-black bg-slate-100 text-slate-700">{x.status}</span>}<span className="text-xs font-black text-slate-900">{x.action}</span></div><p className="font-bold text-sm mt-2 break-words">{x.message||x.entity_type}</p><div className="flex flex-wrap gap-x-4 gap-y-1 mt-2 text-xs text-slate-500"><span><b>Quién:</b> {x.actor_name||x.actor_id||'Sistema'}</span>{x.actor_email&&<span>{x.actor_email}</span>}<span><b>Entidad:</b> {x.entity_type}{x.entity_id?` #${x.entity_id}`:''}</span></div></div><div className="text-xs text-slate-500 whitespace-nowrap">{fmt(x.created_at)}</div></div></article>)}</div>:<div className="py-12 text-center text-slate-500"><ShieldCheck className="w-8 h-8 mx-auto mb-2 text-slate-300"/><p className="font-black">No se encontraron registros.</p><p className="text-xs mt-1">Prueba otra palabra, ID, correo o tipo de evento.</p></div>}</div>
 </section>;
};
