import React, { useEffect, useState } from 'react';
import { Service, Application } from '../types';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { X, MapPin, Calendar, MessageSquare, Send, Users, Lock, ShieldCheck } from 'lucide-react';
import { NegotiationPanel } from './NegotiationPanel';

interface Props { service: Service; onClose:()=>void; onRefresh:()=>void; onOpenChat:(serviceId:string,receiverId:string)=>void; onOpenDispute:(serviceId:string)=>void; }

export const MobileServiceDetailModal:React.FC<Props>=({service,onClose,onRefresh,onOpenChat,onOpenDispute})=>{
 const {user}=useAuth(); const isWorker=user?.role==='TRABAJADOR'||user?.activeRole==='TRABAJADOR'; const isClient=user?.id===service.client_id; const selected=user?.id===service.worker_id;
 const [apps,setApps]=useState<Application[]>([]); const [msg,setMsg]=useState(''); const [offer,setOffer]=useState(Number(service.price_rd||0)); const [busy,setBusy]=useState(false); const [feedback,setFeedback]=useState('');
 const load=async()=>{if(!isClient)return;try{const d=await api.get<{applications:Application[]}>(`/services/${service.id}/applications`);setApps(d.applications||[]);}catch{}};
 useEffect(()=>{load();},[service.id,isClient]);
 const apply=async(e:React.FormEvent)=>{e.preventDefault();if(!msg.trim()){setFeedback('Escribe un mensaje para presentarte al cliente.');return;}setBusy(true);setFeedback('');try{await api.post('/applications',{service_id:service.id,message:msg.trim(),offered_price_rd:offer,availability_note:'Disponibilidad inmediata'});setFeedback('Postulación enviada. El cliente recibió la notificación.');setMsg('');await load();onRefresh();}catch(e:any){setFeedback(e.message||'No se pudo enviar la postulación.')}finally{setBusy(false)}};
 const select=async(id:string)=>{setBusy(true);setFeedback('');try{await api.post(`/applications/${id}/select`,{});setFeedback('Trabajador seleccionado. Ahora pueden negociar el precio final. No hay depósito todavía.');await load();onRefresh();}catch(e:any){setFeedback(e.message||'No se pudo seleccionar.')}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-[60] bg-slate-950/75 backdrop-blur-sm overflow-y-auto overscroll-contain"><div className="min-h-full flex items-end sm:items-center justify-center p-0 sm:p-4"><div className="bg-white w-full sm:max-w-2xl sm:rounded-3xl rounded-t-3xl shadow-2xl overflow-hidden max-h-[96vh] flex flex-col">
  <div className="shrink-0 bg-white border-b px-3 sm:px-4 py-3 flex items-center gap-2 sm:gap-3"><button onClick={onClose} className="p-2 rounded-xl bg-slate-100 shrink-0" aria-label="Cerrar"><X className="w-5 h-5"/></button><div className="min-w-0 flex-1"><p className="text-[10px] uppercase font-black text-blue-600 truncate">{service.category_name}</p><h2 className="font-black text-base leading-tight break-words">{service.title}</h2></div><span className="shrink-0 max-w-[38%] text-center text-[9px] sm:text-[10px] font-bold px-2 py-1 rounded-lg bg-amber-50 text-amber-800 break-words">{service.status.replaceAll('_',' ')}</span></div>
  <div className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-4 space-y-4 pb-10 overscroll-contain">
   {feedback&&<div className="p-3 rounded-xl bg-blue-50 text-blue-800 border border-blue-200 text-xs font-semibold break-words leading-relaxed">{feedback}</div>}
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div className="bg-slate-50 rounded-xl p-3 min-w-0"><p className="text-[10px] text-slate-500">Presupuesto inicial</p><p className="font-black text-lg break-words">RD$ {Number(service.price_rd||0).toLocaleString()}</p><p className="text-[10px] text-slate-500 mt-1 leading-relaxed">Orientativo. No se deposita antes de negociar.</p></div><div className="bg-emerald-50 rounded-xl p-3 min-w-0"><p className="text-[10px] text-emerald-700">Precio acordado</p><p className="font-black text-lg text-emerald-700 break-words">{service.negotiated_price_rd?`RD$ ${Number(service.negotiated_price_rd).toLocaleString()}`:'Pendiente'}</p></div></div>
   <div className="rounded-2xl border p-4"><p className="text-sm text-slate-700 leading-relaxed break-words whitespace-pre-wrap">{service.description}</p><div className="mt-3 grid grid-cols-1 gap-2 text-xs text-slate-600"><div className="flex items-start gap-2 min-w-0"><MapPin className="w-4 h-4 text-red-500 shrink-0"/><span className="break-words">{service.municipality}, {service.province} • {service.address_approx}</span></div><div className="flex items-start gap-2 min-w-0"><Calendar className="w-4 h-4 text-blue-500 shrink-0"/><span className="break-words">{service.service_date} • {service.service_time}</span></div></div></div>
   {service.images?.length>0&&<div><p className="font-black text-xs uppercase text-slate-500 mb-2">Fotos del servicio</p><div className="grid grid-cols-2 sm:grid-cols-3 gap-2">{service.images.slice(0,10).map((x,i)=><img key={i} src={x} className="w-full aspect-square object-cover rounded-xl" alt={`Foto ${i+1}`}/>)}</div></div>}
   {isWorker&&!selected&&!['COMPLETADA','CANCELADA'].includes(service.status)&&<form onSubmit={apply} className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 space-y-3"><div className="flex items-center gap-2"><Users className="w-5 h-5 text-emerald-600 shrink-0"/><p className="font-black text-sm">Postularme a este servicio</p></div><p className="text-[11px] text-emerald-800 leading-relaxed">Presenta tu propuesta y escribe el mensaje que recibirá el cliente.</p><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Ej.: Hola, puedo realizar este trabajo. Tengo experiencia y disponibilidad..." className="w-full min-h-28 resize-y p-3 rounded-xl border bg-white text-sm leading-relaxed break-words"/><div><label className="text-[11px] font-bold text-slate-600">Tu propuesta inicial (RD$)</label><input type="number" min="1" value={offer} onChange={e=>setOffer(Number(e.target.value))} className="w-full mt-1 p-3 rounded-xl border bg-white text-sm font-bold"/></div><button disabled={busy} className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-3.5 rounded-xl font-black text-xs disabled:opacity-50"><Send className="inline w-4 h-4 mr-1"/>{busy?'Enviando postulación…':'Enviar postulación'}</button></form>}
   {selected&&service.status==='TRABAJADOR_SELECCIONADO'&&<div className="rounded-2xl bg-amber-50 border border-amber-200 p-4"><p className="font-black text-sm text-amber-900">Trabajador seleccionado</p><p className="text-xs text-amber-800 mt-1 leading-relaxed break-words">La contratación entra ahora en negociación. El presupuesto publicado es solo orientativo.</p><button onClick={()=>onOpenChat(service.id,service.client_id)} className="mt-3 w-full bg-white border border-blue-200 text-blue-700 py-3 rounded-xl font-bold text-xs"><MessageSquare className="inline w-4 h-4 mr-1"/>Abrir chat con cliente</button></div>}
   {selected&&service.status==='TRABAJADOR_SELECCIONADO'&&<div className="relative min-h-0 rounded-2xl border border-blue-100 bg-slate-50 p-1"><NegotiationPanel serviceId={service.id} clientId={service.client_id} workerId={service.worker_id!} budget={Number(service.price_rd||0)} title={service.title} onRefresh={onRefresh} onOpenChat={onOpenChat}/></div>}
   {isClient&&service.status==='TRABAJADOR_SELECCIONADO'&&<div className="rounded-2xl bg-blue-50 border border-blue-200 p-4"><div className="flex gap-2"><Lock className="w-5 h-5 text-blue-600 shrink-0"/><div className="min-w-0"><p className="font-black text-sm text-blue-900">Primero negociación, después pago</p><p className="text-xs text-blue-800 mt-1 leading-relaxed break-words">No deposites el presupuesto publicado. Negocia y acepta el precio final; el botón de pago en Custodia aparecerá cuando el precio esté acordado.</p></div></div><button onClick={()=>service.worker_id&&onOpenChat(service.id,service.worker_id)} className="mt-3 w-full bg-blue-600 text-white py-3 rounded-xl font-bold text-xs"><MessageSquare className="inline w-4 h-4 mr-1"/>Negociar por chat</button></div>}
   {isClient&&apps.length>0&&<div className="space-y-2"><p className="font-black text-sm">Postulaciones recibidas</p>{apps.map(a=><div key={a.id} className="rounded-2xl border p-3 min-w-0"><div className="flex gap-2"><img src={a.worker_avatar||'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120'} className="w-10 h-10 rounded-full object-cover shrink-0"/><div className="min-w-0 flex-1"><p className="font-bold text-xs break-words">{a.worker_name} {a.worker_is_verified?'✓':''}</p><p className="text-[10px] text-slate-500 break-words">{a.worker_profession} • ★ {a.worker_rating}</p><p className="text-xs mt-1 font-bold">Propuesta: RD$ {Number(a.offered_price_rd||0).toLocaleString()}</p></div></div><div className="mt-2 rounded-xl bg-slate-50 border border-slate-200 p-3"><p className="text-[10px] font-black uppercase text-slate-500 mb-1">Mensaje de postulación</p><p className="text-xs text-slate-700 leading-relaxed break-words whitespace-pre-wrap">{a.message}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-2"><button onClick={()=>onOpenChat(service.id,a.worker_id)} className="py-2.5 rounded-xl border border-blue-200 text-blue-700 text-xs font-bold">Mensaje</button>{a.status!=='SELECCIONADO'&&<button disabled={busy} onClick={()=>select(a.id)} className="py-2.5 rounded-xl bg-blue-600 text-white text-xs font-bold">Seleccionar</button>}</div></div>)}</div>}
   {isClient&&service.status==='EN_PROGRESO'&&<button onClick={()=>onOpenDispute(service.id)} className="w-full py-3 rounded-xl bg-red-50 border border-red-200 text-red-700 font-black text-xs">Abrir disputa / proteger fondos</button>}
   <div className="rounded-2xl bg-slate-900 text-white p-4 flex gap-3"><ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0"/><p className="text-[11px] text-slate-300 leading-relaxed break-words">Custodia SERVIYA protege el pago. La liberación final requiere confirmación del cliente y <b className="text-white">aprobación administrativa</b>.</p></div>
  </div>
 </div></div></div>;
};
