import React from 'react';
import { X, ShieldCheck } from 'lucide-react';

interface PoliciesModalProps { onClose: () => void; }

export const PoliciesModal: React.FC<PoliciesModalProps> = ({ onClose }) => {
 const rules=[
  ['1. Flujo completo de SERVIYA','El flujo de una contratación sigue estas etapas: Publicar servicio → Postulación → Selección → Negociación → Depósito → Verificación administrativa → Custodia → Contrato digital → Aceptación electrónica → Inicio oficial → Ejecución → Finalización → Confirmación del cliente → Liberación → Retiro del trabajador → Cierre y valoración. Cada etapa debe quedar registrada con su estado correspondiente.'],
  ['2. Confirmación y estados','Cada acción importante debe generar una confirmación inmediata para informar que SERVIYA recibió la acción. Además, el resultado debe quedar guardado como estado persistente. Si una acción es rechazada, el sistema debe indicar el motivo concreto y qué debe corregirse cuando corresponda.'],
  ['3. Cliente y fondos','El CLIENTE puede depositar fondos para pagar servicios. No existe retiro normal para clientes. El saldo del cliente se utiliza para pagar servicios dentro de SERVIYA y permanece sujeto al flujo de Custodia cuando corresponde.'],
  ['4. Trabajador/Técnico y retiros','El TRABAJADOR/TÉCNICO es el usuario normal que puede solicitar retiros. Solo puede retirar fondos disponibles; el dinero pendiente, retenido en Custodia o en disputa no está disponible para retiro. Administración procesa y controla las solicitudes.'],
  ['5. Selección, negociación y acuerdo','Cliente y trabajador pueden intercambiar propuestas y condiciones mediante el sistema. Antes de avanzar al depósito deben quedar claros el precio acordado, alcance, fecha, duración, ubicación, materiales y demás condiciones relevantes.'],
  ['6. Depósito y cuenta receptora','El cliente debe utilizar las cuentas bancarias activas de SERVIYA que aparezcan en el flujo de depósito y seleccionar la cuenta receptora correspondiente antes de registrar la transferencia. Las cuentas de recepción de SERVIYA son diferentes de las cuentas bancarias de retiro de los trabajadores.'],
  ['7. Verificación administrativa','Después de enviar el comprobante, el depósito queda pendiente de verificación. Administración revisa el comprobante y la información de la operación. Si lo rechaza, debe quedar registrado el motivo y qué debe corregir el cliente. Si lo aprueba, los fondos pasan al estado de Custodia correspondiente y continúa el siguiente paso.'],
  ['8. Custodia SERVIYA','El dinero entra en Custodia solo después de la verificación correspondiente. Mientras esté retenido, no se considera dinero liberado al trabajador y no puede utilizarse como saldo disponible para retiro.'],
  ['9. Contrato digital','Cuando el depósito es aprobado y corresponde emitir el contrato, SERVIYA debe notificar al usuario y llevarlo directamente al Contrato Digital. El contrato muestra las condiciones de la operación y debe quedar disponible para lectura y aceptación electrónica.'],
  ['10. Aceptación electrónica e inicio oficial','Las partes deben aceptar electrónicamente el contrato cuando el flujo lo requiera. La aceptación queda registrada. El trabajo no debe considerarse iniciado oficialmente hasta que se cumplan las condiciones de inicio establecidas por el flujo.'],
  ['11. Ejecución y evidencia','El trabajador debe cumplir las condiciones acordadas y puede presentar fotos, documentos, mensajes y resumen del trabajo. Las evidencias pueden utilizarse para conformidad, garantía, auditoría o mediación.'],
  ['12. Finalización y confirmación del cliente','El trabajador marca el trabajo como terminado cuando realmente ha completado lo acordado. El cliente revisa el resultado y registra su conformidad o reporta un problema. La conformidad del cliente debe quedar guardada como parte del historial del servicio.'],
  ['13. Liberación de fondos','La liberación se realiza después de las validaciones correspondientes. Antes de ejecutarla, Administración debe confirmar que el dinero corresponde al cliente y servicio correctos y que la cuenta bancaria de destino pertenece al trabajador asociado a esa operación. Si existe una inconsistencia, la liberación debe bloquearse y registrarse el motivo.'],
  ['14. Trabajador y pago','Una vez aprobada y ejecutada la liberación, el trabajador recibe el monto neto correspondiente en su billetera, después de aplicar la comisión configurada por SERVIYA. El pago liberado queda registrado en el historial financiero.'],
  ['15. Garantía SERVIYA','Cuando corresponda según las condiciones del servicio, la garantía se activa después de la finalización y liberación. La cobertura indicada para el servicio puede incluir una re-visita para corregir un defecto relacionado directamente con el trabajo contratado.'],
  ['16. Garantía: qué NO incluye','La garantía no es ilimitada. No cubre daños por mal uso, accidentes, modificaciones o reparaciones realizadas por terceros, desgaste normal, nuevas fallas no relacionadas con el trabajo contratado ni condiciones ajenas al servicio acordado.'],
  ['17. Re-visita y solución','El cliente puede solicitar una re-visita durante una garantía activa. El trabajador debe atender una reclamación válida y realizar la corrección cuando corresponda. El cliente debe aportar una descripción clara y, cuando sea posible, evidencia del problema.'],
  ['18. Incumplimiento después del pago','Si se determina que el trabajador incumplió después de la liberación, la responsabilidad económica por la corrección o reembolso corresponde al trabajador responsable según el caso y las políticas aplicables. SERVIYA gestiona, registra e investiga el proceso y no asume automáticamente con fondos propios las obligaciones del trabajador.'],
  ['19. Disputas y fondos protegidos','Si existe desacuerdo, cliente o trabajador pueden abrir una disputa. Administración revisará evidencias, mensajes, condiciones acordadas, historial y demás información disponible. Si la disputa ocurre antes de la liberación, los fondos que sigan en Custodia pueden mantenerse protegidos mientras se resuelve el caso.'],
  ['20. Cancelaciones y no presentación','Las cancelaciones se evalúan según el estado del servicio, las condiciones acordadas y la situación de los fondos. Una cancelación o rechazo debe dejar un estado y motivo registrados. Cuando corresponda, el sistema debe indicar al usuario qué debe corregir o qué siguiente paso puede realizar.'],
  ['21. Verificación y conducta','La verificación de identidad y certificaciones puede ser requerida para trabajadores. No se permite fraude, información falsa, suplantación, abuso, daño intencional ni uso indebido de SERVIYA.'],
  ['22. Auditoría e historial','Las acciones relevantes de usuarios y Administración deben conservar un historial consultable: publicaciones, postulaciones, selección, negociación, depósitos, vouchers, verificaciones, Custodia, contratos, aceptaciones, inicio, ejecución, finalización, conformidad, liberaciones, retiros, disputas, verificaciones y cambios administrativos.']
 ];
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/70 backdrop-blur-sm p-3 sm:p-4 overflow-y-auto"><div className="bg-white rounded-3xl max-w-3xl w-full p-5 sm:p-8 shadow-2xl border border-slate-200 relative my-4 max-h-[92vh] overflow-y-auto"><button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 p-2 rounded-full hover:bg-slate-100" aria-label="Cerrar"><X className="w-5 h-5"/></button><div className="flex items-start gap-2 mb-1 pr-8"><ShieldCheck className="w-6 h-6 text-blue-600 shrink-0"/><div><h2 className="text-xl font-black text-slate-900">Políticas y Reglas SERVIYA</h2><p className="text-xs text-slate-500 mt-1">Condiciones del flujo completo: contratación, pagos, Custodia, contrato digital, ejecución, liberación, retiros, garantía, disputas y auditoría.</p></div></div><div className="mt-5 grid grid-cols-1 lg:grid-cols-2 gap-3 text-xs text-slate-700">{rules.map(([title,text])=><div key={title} className="bg-slate-50 border border-slate-100 rounded-2xl p-4"><p className="font-bold text-slate-900 mb-1">{title}</p><p className="leading-relaxed text-slate-600">{text}</p></div>)}</div></div></div>;
};
