import React from 'react';
import { X, ShieldCheck } from 'lucide-react';

interface PoliciesModalProps { onClose: () => void; }

export const PoliciesModal: React.FC<PoliciesModalProps> = ({ onClose }) => {
 const rules=[
  ['1. Custodia SERVIYA','El pago solo entra en Custodia SERVIYA después de que cliente y trabajador hayan acordado el precio final. El presupuesto publicado es orientativo y no significa dinero depositado ni retenido.'],
  ['2. Cliente y fondos','El cliente puede depositar fondos para pagar servicios. No existe retiro normal para clientes. El cliente conserva la decisión de aprobar la finalización, mientras Administración mantiene la facultad de aprobar y ejecutar la liberación conforme al flujo de SERVIYA.'],
  ['3. Trabajador y pago','Una vez que el trabajo termina, el cliente confirma la finalización y Administración aprueba la liberación, el trabajador recibe el dinero disponible que le corresponde. SERVIYA no retiene el pago únicamente por existir un período de garantía.'],
  ['4. Trabajador y retiros','El trabajador puede solicitar retiros de fondos disponibles. Los retiros quedan sujetos a validación y procesamiento administrativo.'],
  ['5. Negociación y precio final','Cliente y trabajador pueden intercambiar propuestas y condiciones mediante el sistema. El pago se realiza por el precio acordado, no automáticamente por el presupuesto inicial.'],
  ['6. Ejecución y evidencia','El trabajador debe cumplir las condiciones acordadas y puede presentar fotos y resumen del trabajo. Las evidencias pueden utilizarse para conformidad, garantía o mediación.'],
  ['7. Garantía SERVIYA: qué incluye','Cuando el cliente aprueba el trabajo y Administración libera el pago, se activa la garantía indicada en el servicio. La cobertura estándar definida por SERVIYA es de 60 días. Puede incluir una re-visita para corregir un defecto relacionado directamente con el trabajo contratado, cuando corresponda.'],
  ['8. Garantía: qué NO incluye','La garantía no es ilimitada. No cubre daños por mal uso, accidentes, modificaciones o reparaciones realizadas por terceros, desgaste normal, nuevas fallas no relacionadas con el trabajo contratado ni condiciones ajenas al servicio acordado.'],
  ['9. Re-visita y solución','El cliente puede solicitar una re-visita durante una garantía activa. El trabajador debe atender una reclamación válida y realizar la corrección cuando corresponda. El cliente debe aportar una descripción clara y, cuando sea posible, evidencia del problema.'],
  ['10. Incumplimiento del trabajador después del pago','La garantía funciona después de que el trabajador haya cobrado. Si se determina que el trabajador incumplió, la responsabilidad económica por la corrección o reembolso corresponde al trabajador responsable. SERVIYA actúa como plataforma de intermediación, gestión e investigación y no asume automáticamente con fondos propios las obligaciones económicas del trabajador.'],
  ['11. Reembolso por incumplimiento','Si Administración determina que corresponde un reembolso por responsabilidad del trabajador después de la liberación, se registra la obligación correspondiente contra el trabajador. SERVIYA podrá gestionar la reclamación y aplicar las medidas disponibles dentro de la plataforma. La liberación previa del pago no convierte a SERVIYA en garante económico del trabajo.'],
  ['12. Incumplimiento y medidas administrativas','Cuando un trabajador sea responsable de un incumplimiento, podrá quedar registrada la incidencia. Según la gravedad o reincidencia, SERVIYA podrá limitar temporalmente retiros o nuevas operaciones, exigir la regularización de una obligación pendiente, suspender la cuenta o bloquearla conforme a las reglas de la plataforma.'],
  ['13. Disputas','Si existe desacuerdo, cliente o trabajador pueden abrir una disputa. Administración revisará evidencias, mensajes, condiciones acordadas, historial de la re-visita y demás información disponible. La resolución deberá indicar quién resulta responsable y qué acción corresponde.'],
  ['14. Fondos en custodia','Cuando una reclamación ocurre antes de la liberación, los fondos que todavía estén en Custodia SERVIYA pueden mantenerse protegidos mientras Administración resuelve el caso. Si el pago ya fue liberado al trabajador, se aplica el régimen de responsabilidad posterior al pago descrito en estas políticas.'],
  ['15. Cancelaciones y no presentación','Las cancelaciones se evalúan según el estado del servicio, las condiciones acordadas y si existen fondos en custodia. El cliente puede reportar una no presentación o incumplimiento cuando corresponda.'],
  ['16. Verificación y conducta','La verificación de identidad y certificaciones puede ser requerida para trabajadores. No se permite fraude, información falsa, suplantación, abuso, daño intencional ni uso indebido de SERVIYA.']
 ];
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/70 backdrop-blur-sm p-3 sm:p-4 overflow-y-auto"><div className="bg-white rounded-3xl max-w-3xl w-full p-5 sm:p-8 shadow-2xl border border-slate-200 relative my-4 max-h-[92vh] overflow-y-auto"><button onClick={onClose} className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 p-2 rounded-full hover:bg-slate-100" aria-label="Cerrar"><X className="w-5 h-5"/></button><div className="flex items-start gap-2 mb-1 pr-8"><ShieldCheck className="w-6 h-6 text-blue-600 shrink-0"/><div><h2 className="text-xl font-black text-slate-900">Políticas y Reglas SERVIYA</h2><p className="text-xs text-slate-500 mt-1">Condiciones de contratación, pagos, Custodia, garantía, re-visitas, incumplimientos, disputas y retiros.</p></div></div><div className="mt-5 grid grid-cols-1 lg:grid-cols-2 gap-3 text-xs text-slate-700">{rules.map(([title,text])=><div key={title} className="bg-slate-50 border border-slate-100 rounded-2xl p-4"><p className="font-bold text-slate-900 mb-1">{title}</p><p className="leading-relaxed text-slate-600">{text}</p></div>)}</div></div></div>;
};
