import React,{useEffect,useState} from 'react';
import {useWallet} from '../context/WalletContext';
import {useAuth} from '../context/AuthContext';
import {api} from '../services/api';
import {WorkerBankAccountPanel} from './WorkerBankAccountPanel';
import {Wallet as WalletIcon,Lock,Clock,ArrowUpRight,CheckCircle,Building2,ShieldCheck,FileText,X,History,Receipt,ChevronRight} from 'lucide-react';

interface SavedBankAccount{ id:number|string; bank_name:string; account_type:string; account_number:string; account_holder_name:string; account_holder_cedula:string; is_active:boolean }
interface PaymentReceipt{service_id:string;reference:string;status:string;service_title:string;service_description:string;client_name?:string;worker_name?:string;worker_bank_name?:string;worker_account_type?:string;worker_account_number?:string;worker_account_holder?:string;scheduled_date?:string;scheduled_time?:string;estimated_duration?:string;agreement_date?:string;custody_at?:string;started_at?:string;completed_at?:string;released_at?:string;work_duration_label?:string;completion_summary?:string;payment_method?:string;total_paid_by_client_rd:number;commission_percent:number;commission_rd:number;worker_net_rd:number;rules:string[]}
const money=(v:number)=>`RD$ ${Number(v||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})`;
const dateTime=(v?:string)=>v?new Date(v).toLocaleString('es-DO'):'No registrado';
const mask=(n:string)=>String(n||'').length<=4?String(n||''):`•••• ${String(n).slice(-4)}`;
type WindowName='history'|'bank'|'receipts'|null;

export const WalletView:React.FC=()=>{
 const {wallet,transactions,withdrawRD}=useWallet(); const {user}=useAuth();
 const role=String(user?.activeRole||user?.role||'').toUpperCase(); const isWorker=role==='TRABAJADOR'; const isClient=role==='CLIENTE';
 const [window,setWindow]=useState<WindowName>(null); const [showWithdrawModal,setShowWithdrawModal]=useState(false); const [withdrawAmount,setWithdrawAmount]=useState<number|''>(''); const [savedAccount,setSavedAccount]=useState<SavedBankAccount|null>(null); const [loadingAccount,setLoadingAccount]=useState(false); const [submitting,setSubmitting]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [receipts,setReceipts]=useState<PaymentReceipt[]>([]); const [selectedReceipt,setSelectedReceipt]=useState<PaymentReceipt|null>(null);
 useEffect(()=>{if(!isWorker){setSavedAccount(null);return} let cancelled=false;setLoadingAccount(true);api.get<{bank_account:SavedBankAccount|null}>('/worker/bank-account').then(d=>{if(!cancelled)setSavedAccount(d.bank_account?.is_active?d.bank_account:null)}).catch(()=>{if(!cancelled)setSavedAccount(null)}).finally(()=>{if(!cancelled)setLoadingAccount(false)});return()=>{cancelled=true}},[isWorker]);
 useEffect(()=>{if(!isWorker&&!isClient)return;api.get<{receipts:PaymentReceipt[]}>('/payment-receipts').then(d=>setReceipts(d.receipts||[])).catch(()=>setReceipts([]))},[isWorker,isClient,transactions.length]);
 const available=Number(wallet?.available_rd||0);
 const handleWithdraw=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');if(!isWorker)return setError('Los retiros están reservados exclusivamente para Trabajadores.');if(!savedAccount)return setError('Primero configura tu cuenta bancaria.');if(!withdrawAmount||Number(withdrawAmount)<=0)return setError('Ingresa un monto válido.');if(Number(withdrawAmount)>available)return setError('El monto no puede superar tu saldo disponible.');setSubmitting(true);try{await withdrawRD({amount_rd:Number(withdrawAmount)});setMessage(`Solicitud de retiro de RD$ ${Number(withdrawAmount).toLocaleString()} enviada a Administración.`);setShowWithdrawModal(false);setWithdrawAmount('')}catch(err:any){setError(err?.message||'No se pudo procesar el retiro.')}finally{setSubmitting(false)}};
 const selectAllForWithdrawal=()=>{if(available>0){setWithdrawAmount(available);setError('')}};
 if(isClient)return null;
 return <div className="space-y-6 pb-12 max-w-4xl mx-auto">
  <div><h1 className="text-2xl sm:text-3xl font-black text-slate-900">MI BILLETERA SERVIYA</h1><p className="text-xs sm:text-sm text-slate-500">Gestión transparente de fondos y pagos protegidos mediante Custodia SERVIYA.</p></div>
  {message&&<div className="p-3.5 bg-emerald-50 text-emerald-800 text-xs font-semibold rounded-2xl border border-emerald-200 flex items-center gap-2"><CheckCircle className="w-4 h-4"/>{message}</div>}{error&&<div className="p-3.5 bg-red-50 text-red-700 text-xs font-semibold rounded-2xl border border-red-200">{error}</div>}
  <div className="bg-slate-900 text-white rounded-3xl p-6 sm:p-8 shadow-2xl border border-slate-800 space-y-6"><div className="flex items-center justify-between border-b border-slate-800 pb-4"><div className="flex items-center gap-2"><WalletIcon className="w-6 h-6 text-emerald-400"/><span className="font-bold text-sm tracking-wider uppercase text-slate-300">Balance General (RD$)</span></div><span className="text-xs text-blue-400 bg-blue-950 px-2.5 py-1 rounded-full border border-blue-900 font-bold">DOP</span></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="p-4 bg-slate-800/90 rounded-2xl border border-slate-700/80"><span className="text-xs text-slate-400 font-semibold uppercase block">Disponible</span><p className="text-2xl sm:text-3xl font-black text-emerald-400">RD$ {wallet?wallet.available_rd.toLocaleString():'0.00'}</p></div><div className="p-4 bg-slate-800/90 rounded-2xl border border-slate-700/80"><div className="flex items-center gap-1.5 text-xs text-slate-400 font-semibold uppercase"><Lock className="w-3.5 h-3.5 text-amber-400"/>En Custodia</div><p className="text-2xl sm:text-3xl font-black text-amber-400">RD$ {wallet?wallet.escrow_rd.toLocaleString():'0.00'}</p></div><div className="p-4 bg-slate-800/90 rounded-2xl border border-slate-700/80"><div className="flex items-center gap-1.5 text-xs text-slate-400 font-semibold uppercase"><Clock className="w-3.5 h-3.5 text-blue-400"/>Pendiente Retiro</div><p className="text-2xl sm:text-3xl font-black text-blue-400">RD$ {wallet?wallet.pending_rd.toLocaleString():'0.00'}</p></div></div><button onClick={()=>{setError('');setWithdrawAmount('');setShowWithdrawModal(true)}} disabled={!savedAccount||loadingAccount} className="w-full bg-blue-600 hover:bg-blue-500 disabled:bg-slate-700 disabled:text-slate-400 text-white font-bold text-sm py-3 rounded-xl flex items-center justify-center gap-2"><ArrowUpRight className="w-4 h-4"/>{loadingAccount?'Cargando cuenta bancaria...':savedAccount?'Solicitar Retiro':'Configura tu cuenta bancaria primero'}</button></div>
  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
   <button onClick={()=>setWindow('history')} className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm text-left hover:border-blue-300 hover:shadow-md transition"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="p-3 rounded-2xl bg-blue-50 text-blue-600"><History className="w-5 h-5"/></span><div><h2 className="font-black">Historial de retiros</h2><p className="text-xs text-slate-500 mt-1">Todas tus solicitudes y movimientos de retiro.</p></div></div><ChevronRight className="w-5 h-5 text-slate-400"/></div></button>
   {isWorker&&<button onClick={()=>setWindow('bank')} className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm text-left hover:border-emerald-300 hover:shadow-md transition"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="p-3 rounded-2xl bg-emerald-50 text-emerald-600"><Building2 className="w-5 h-5"/></span><div><h2 className="font-black">Mi cuenta bancaria</h2><p className="text-xs text-slate-500 mt-1">Cuenta de destino para tus retiros.</p></div></div><ChevronRight className="w-5 h-5 text-slate-400"/></div></button>}
   <button onClick={()=>setWindow('receipts')} className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm text-left hover:border-amber-300 hover:shadow-md transition"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="p-3 rounded-2xl bg-amber-50 text-amber-600"><Receipt className="w-5 h-5"/></span><div><h2 className="font-black">Comprobantes y facturas</h2><p className="text-xs text-slate-500 mt-1">Factura y comprobante emitidos por SERVIYA.</p></div></div><ChevronRight className="w-5 h-5 text-slate-400"/></div></button>
  </div>
  {showWithdrawModal&&<div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm p-4 overflow-y-auto"><div className="min-h-full flex items-center justify-center"><form onSubmit={handleWithdraw} className="bg-white rounded-3xl max-w-md w-full shadow-2xl my-6 p-6"><div className="flex items-start justify-between gap-4 mb-5"><div><h2 className="text-xl font-black">Solicitar retiro</h2><p className="text-xs text-slate-500 mt-1">El retiro se enviará a tu cuenta bancaria configurada.</p></div><button type="button" onClick={()=>setShowWithdrawModal(false)} className="p-2 rounded-xl bg-slate-100"><X className="w-5 h-5"/></button></div><div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 mb-4"><span className="text-[10px] uppercase font-bold text-emerald-700">Disponible para retiro</span><p className="text-2xl font-black text-emerald-700 mt-1">{money(available)}</p></div><label className="block text-xs font-bold text-slate-600 mb-2">Monto a retirar</label><div className="flex gap-2"><input type="number" min="1" max={available} step="0.01" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value===''?'':Number(e.target.value))} placeholder="Ingresa el monto" className="flex-1 border border-slate-200 rounded-xl px-4 py-3 text-sm font-bold outline-none focus:ring-2 focus:ring-blue-500"/><button type="button" onClick={selectAllForWithdrawal} disabled={available<=0} className="shrink-0 px-4 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-200 disabled:text-slate-400 text-white text-xs font-black">Retirar todo</button></div><p className="text-[11px] text-slate-500 mt-2">El botón coloca automáticamente todo tu saldo disponible en el monto del retiro.</p>{savedAccount&&<div className="mt-4 p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs"><span className="font-bold block">Cuenta de destino</span><span>{savedAccount.bank_name} • {savedAccount.account_type}</span><span className="block text-slate-500">{mask(savedAccount.account_number)} • {savedAccount.account_holder_name}</span></div>}<div className="flex gap-2 mt-5"><button type="button" onClick={()=>setShowWithdrawModal(false)} className="flex-1 py-3 rounded-xl bg-slate-100 text-slate-700 text-sm font-bold">Cancelar</button><button type="submit" disabled={submitting||!withdrawAmount||available<=0} className="flex-1 py-3 rounded-xl bg-blue-600 hover:bg-blue-500 disabled:bg-slate-300 text-white text-sm font-bold">{submitting?'Procesando...':'Confirmar retiro'}</button></div></form></div></div>}
  {window==='history'&&<div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm p-4 overflow-y-auto"><div className="min-h-full flex items-center justify-center"><div className="bg-white rounded-3xl max-w-3xl w-full shadow-2xl my-6"><div className="p-6 border-b flex items-center justify-between"><div><h2 className="text-xl font-black">Historial de retiros</h2><p className="text-xs text-slate-500 mt-1">Historial completo de movimientos de tu billetera.</p></div><button onClick={()=>setWindow(null)} className="p-2 rounded-xl bg-slate-100"><X className="w-5 h-5"/></button></div><div className="p-6 space-y-3">{transactions.length===0?<p className="text-xs text-slate-500 text-center py-8">Aún no registras movimientos.</p>:transactions.map(tx=><div key={tx.id} className="p-4 bg-slate-50 rounded-2xl border border-slate-100 flex items-center justify-between gap-3 text-xs"><div><span className="font-bold block">{tx.description}</span><span className="text-[11px] text-slate-500">{new Date(tx.created_at).toLocaleString('es-DO')} • Ref: {tx.reference}</span></div><div className="text-right"><span className="font-black text-sm block">RD$ {tx.amount_rd.toLocaleString()}</span><span className="text-[10px] font-bold text-slate-400 uppercase">{tx.status}</span></div></div>)}</div></div></div></div>}
  {window==='bank'&&<div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm p-4 overflow-y-auto"><div className="min-h-full flex items-center justify-center"><div className="bg-white rounded-3xl max-w-2xl w-full shadow-2xl my-6"><div className="p-6 border-b flex items-center justify-between"><div><h2 className="text-xl font-black">Mi cuenta bancaria</h2><p className="text-xs text-slate-500 mt-1">Esta información permanece fuera de la pantalla principal.</p></div><button onClick={()=>setWindow(null)} className="p-2 rounded-xl bg-slate-100"><X className="w-5 h-5"/></button></div><div className="p-6">{savedAccount&&<div className="mb-5 p-4 bg-emerald-50 rounded-2xl border border-emerald-200"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-emerald-600"/><span className="font-black text-sm">Cuenta configurada</span></div><p className="text-sm font-bold mt-2">{savedAccount.bank_name} • {savedAccount.account_type}</p><p className="text-xs text-slate-500 mt-1">Cuenta {mask(savedAccount.account_number)} • Titular: {savedAccount.account_holder_name}</p></div>}<WorkerBankAccountPanel/></div></div></div></div>}
  {window==='receipts'&&<div className="fixed inset-0 z-50 bg-slate-950/70 backdrop-blur-sm p-4 overflow-y-auto"><div className="min-h-full flex items-center justify-center"><div className="bg-white rounded-3xl max-w-3xl w-full shadow-2xl my-6"><div className="p-6 border-b flex items-center justify-between"><div><h2 className="text-xl font-black">Comprobantes y facturas SERVIYA</h2><p className="text-xs text-slate-500 mt-1">Documentos emitidos después de la liberación del pago.</p></div><button onClick={()=>setWindow(null)} className="p-2 rounded-xl bg-slate-100"><X className="w-5 h-5"/></button></div><div className="p-6 space-y-3">{receipts.length===0?<p className="text-xs text-slate-500 text-center py-10">Aún no hay comprobantes disponibles.</p>:receipts.map(r=><div key={r.service_id} className="p-4 bg-emerald-50/60 rounded-2xl border border-emerald-100 flex items-center justify-between gap-3"><div><span className="font-black block">{r.service_title}</span><span className="text-[11px] text-slate-500 block mt-1">Liberado • {dateTime(r.released_at)}</span><span className="text-[11px] text-slate-500">Ref: {r.reference}</span></div><button onClick={()=>setSelectedReceipt(r)} className="shrink-0 px-3 py-2 rounded-xl bg-emerald-600 text-white text-xs font-bold"><FileText className="w-3.5 h-3.5 inline mr-1"/>Ver factura</button></div>)}</div></div></div></div>}
  {selectedReceipt&&<div className="fixed inset-0 z-[60] bg-slate-950/80 backdrop-blur-sm p-4 overflow-y-auto"><div className="min-h-full flex items-center justify-center"><div className="bg-white rounded-3xl max-w-2xl w-full shadow-2xl overflow-hidden my-6"><div className="bg-slate-900 text-white p-6 flex items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-widest text-emerald-400">SERVIYA</p><h3 className="text-xl sm:text-2xl font-black mt-1">Comprobante de pago y desembolso</h3><p className="text-xs text-slate-400 mt-1">Trabajo • Confianza • Oportunidades</p></div><button onClick={()=>setSelectedReceipt(null)} className="p-2 rounded-xl bg-white/10"><X className="w-5 h-5"/></button></div><div className="p-6 space-y-5"><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><div><span className="text-[10px] uppercase text-slate-400 font-bold">Servicio</span><p className="font-black">{selectedReceipt.service_title}</p></div><div><span className="text-[10px] uppercase text-slate-400 font-bold">Referencia</span><p className="font-bold">{selectedReceipt.reference}</p></div><div><span className="text-[10px] uppercase text-slate-400 font-bold">Cliente</span><p>{selectedReceipt.client_name||'—'}</p></div><div><span className="text-[10px] uppercase text-slate-400 font-bold">Trabajador</span><p>{selectedReceipt.worker_name||'—'}</p></div></div><div className="p-4 bg-blue-50 rounded-2xl border border-blue-100"><p className="text-[10px] uppercase text-blue-600 font-bold">Cuenta bancaria del trabajador</p><p className="font-black mt-1">{selectedReceipt.worker_bank_name||'No registrada'} • {selectedReceipt.worker_account_type||''}</p><p className="text-sm mt-1">Cuenta: {selectedReceipt.worker_account_number||'No registrada'}</p><p className="text-xs text-slate-500 mt-1">Titular: {selectedReceipt.worker_account_holder||selectedReceipt.worker_name||'—'}</p></div><div className="p-4 bg-slate-50 rounded-2xl border"><p className="text-[10px] uppercase text-slate-400 font-bold">Descripción del servicio</p><p className="text-sm text-slate-700 mt-1">{selectedReceipt.service_description}</p>{selectedReceipt.completion_summary&&<><p className="text-[10px] uppercase text-slate-400 font-bold mt-3">Resumen de finalización</p><p className="text-sm text-slate-700 mt-1">{selectedReceipt.completion_summary}</p></>}</div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[['Total pagado',selectedReceipt.total_paid_by_client_rd],['Comisión SERVIYA',selectedReceipt.commission_rd],['Neto trabajador',selectedReceipt.worker_net_rd]].map(([label,value])=><div key={String(label)} className="p-4 rounded-2xl border bg-white"><p className="text-[10px] uppercase text-slate-400 font-bold">{label}</p><p className="font-black mt-1">{money(Number(value))}</p></div>)}</div><div className="text-xs text-slate-500">Este comprobante corresponde a una operación del modelo de simulación de SERVIYA.</div></div></div></div></div>}
 </div>;
};
