import React, { useEffect, useState } from 'react';
import { ShieldCheck, X, CalendarDays, RefreshCw, CheckCircle2, Clock3, AlertTriangle, Printer, PlayCircle } from 'lucide-react';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';

type Revisit = { id:string; issue:string; description:string; status:string; scheduled_at?:string|null; resolution_notes?:string|null; created_at?:string|null; resolved_at?:string|null };
type WarrantyPayload = { warranty:{ id:string; service_id:string; certificate_ref?:string|null; coverage_days:number; status:string; activated_at?:string|null; expires_at?:string|null; client_name?:string|null; worker_name?:string|null; service_title?:string|null; amount_rd:number; expired:boolean }; revisits:Revisit[] };
type ContractItem = { service_id:string; contract_number?:string|null };
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('es-DO',{dateStyle:'medium',timeStyle:'short'}):'—';
const labels:Record<string,string>={SOLICITADA:'Solicitada',PROGRAMADA:'Programada',CORRECCION_EN_PROCESO:'Corrección en proceso',CORRECCION_REALIZADA:'Corrección realizada — pendiente de confirmación',CERRADA:'Cerrada',ESCALADA_ADMIN:'Escalada a Administración'};

export const WarrantyLauncher:React.FC=()=>{
 const { user } = useAuth();
 const [open,setOpen]=useState(false); const [serviceId,setServiceId]=useState(''); const [contractNumber,setContractNumber]=useState(''); const [data,setData]=useState<WarrantyPayload|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [issue,setIssue]=useState(''); const [description,setDescription]=useState(''); const [schedule,setSchedule]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const isClient=user?.activeRole==='CLIENTE' || user?.role==='CLIENTE';
 useEffect(()=>{
  const inject=()=>{
   const hash=Array.from(document.querySelectorAll<HTMLElement>('p')).find(n=>(n.textContent||'').includes('Hash SHA-256:'));
   if(!hash)return;
   const root=hash.closest<HTMLElement>('.bg-white')||hash.parentElement?.closest<HTMLElement>('.bg-white'); if(!root||root.querySelector('[data-serviya-warranty-launcher]'))return;
   const number=root.querySelector('h3')?.textContent?.trim()||'';
   const wrap=document.createElement('div'); wrap.setAttribute('data-serviya-warranty-launcher','true'); wrap.style.cssText='margin-top:10px;';
   const btn=document.createElement('button'); btn.type='button'; btn.textContent='🛡️ Garantía SERVIYA'; btn.style.cssText='width:100%;padding:12px 14px;border-radius:12px;border:1px solid #0f766e;background:#ecfdf5;color:#0f766e;font-weight:900;font-size:13px;cursor:pointer;';
   btn.onclick=async(e)=>{e.preventDefault();e.stopPropagation();setContractNumber(number);setOpen(true);setError('');setMessage('');setData(null);setServiceId('');try{const list=await api.get<{contracts:ContractItem[]}>('/contracts');const match=(list?.contracts||[]).find(c=>String(c.contract_number||'')===number);if(!match?.service_id)throw new Error('Este contrato todavía no tiene un servicio identificable para la garantía.');setServiceId(String(match.service_id));}catch(err:any){setError(err?.message||'No se pudo identificar el contrato registrado.');}};
   wrap.appendChild(btn); root.appendChild(wrap);
  };
  const observer=new MutationObserver(inject); observer.observe(document.body,{childList:true,subtree:true}); inject(); return()=>observer.disconnect();
 },[]);
 useEffect(()=>{if(open&&serviceId)void load();},[open,serviceId]);
 const load=async()=>{setLoading(true);setError('');try{setData(await api.get<WarrantyPayload>(`/completion/${serviceId}/warranty`));}catch(e:any){setData(null);setError(e?.message||'No se pudo cargar la garantía.');}finally{setLoading(false);}};
 const action=async(path:string,body:any,success:string)=>{setBusy(true);setError('');setMessage('');try{const r=await api.post<any>(`/completion/${serviceId}/warranty/revisits/${path}`,body);setMessage(`${success} Estado guardado: ${r?.status||'OK'}.`);setSchedule('');await load();}catch(e:any){setError(e?.message||'La acción fue rechazada.');}finally{setBusy(false);}};
 const request=async()=>{if(!isClient){setError('Las solicitudes de revisita las inicia el cliente. Como trabajador, atiende las solicitudes desde Historial y seguimiento.');return;}if(issue.trim().length<3||description.trim().length<10){setError('Indica el problema y una explicación de al menos 10 caracteres.');return;}setBusy(true);setError('');setMessage('');try{const r=await api.post<any>(`/completion/${serviceId}/warranty/revisit`,{issue:issue.trim(),description:description.trim()});setMessage(`Revisita solicitada correctamente. Estado guardado: ${r?.status||'SOLICITADA'}.`);setIssue('');setDescription('');await load();}catch(e:any){setError(e?.message||'La solicitud fue rechazada.');}finally{setBusy(false);}};
 const printCertificate=()=>{if(!data)return;const w=window.open('','_blank','width=900,height=900');if(!w){setError('El navegador bloqueó la ventana de impresión.');return;}w.document.write(`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Certificado ${data.warranty.certificate_ref||'GAR-SRV'} • SERVIYA</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#0f172a}.sheet{border:2px solid #0f766e;border-radius:18px;padding:28px}.brand{font-size:28px;font-weight:900;letter-spacing:2px;color:#0f766e}.sub{color:#475569}.badge{display:inline-block;padding:7px 12px;border-radius:10px;background:#ecfdf5;color:#047857;font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.box{border:1px solid #cbd5e1;border-radius:12px;padding:12px}.label{font-size:11px;color:#64748b;text-transform:uppercase;font-weight:700}.value{font-size:16px;font-weight:800;margin-top:4px}.footer{margin-top:28px;border-top:1px solid #cbd5e1;padding-top:14px;font-size:11px;color:#64748b}</style></head><body><div class="sheet"><div class="brand">SERVIYA</div><h1>Certificado de Garantía</h1><p class="sub">Trabajo • Confianza • Oportunidades</p><p class="badge">${data.warranty.status} · ${data.warranty.coverage_days} días</p><div class="grid"><div class="box"><div class="label">Certificado</div><div class="value">${data.warranty.certificate_ref||'GAR-SRV'}</div></div><div class="box"><div class="label">Servicio</div><div class="value">${data.warranty.service_title||'—'}</div></div><div class="box"><div class="label">Cliente</div><div class="value">${data.warranty.client_name||'—'}</div></div><div class="box"><div class="label">Trabajador</div><div class="value">${data.warranty.worker_name||'—'}</div></div><div class="box"><div class="label">Activada</div><div class="value">${fmt(data.warranty.activated_at)}</div></div><div class="box"><div class="label">Vencimiento</div><div class="value">${fmt(data.warranty.expires_at)}</div></div><div class="box"><div class="label">Monto del servicio</div><div class="value">RD$ ${Number(data.warranty.amount_rd||0).toLocaleString('es-DO',{minimumFractionDigits:2})}</div></div><div class="box"><div class="label">Contrato</div><div class="value">${contractNumber||'—'}</div></div></div><h2>Protección SERVIYA</h2><p>La garantía cubre problemas directamente relacionados con el trabajo realizado y permite registrar una solicitud de revisita durante el período vigente.</p><p>No cubre daños por mal uso, accidentes, terceros, modificaciones ni trabajos adicionales no incluidos en el acuerdo.</p><div class="footer">Certificado generado desde el registro de garantía de SERVIYA. Documento informativo asociado al servicio y a su historial.</div></div><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),700)}</script></body></html>`);w.document.close();};
 const close=()=>{setOpen(false);setData(null);setError('');setMessage('');setIssue('');setDescription('');setSchedule('');setServiceId('');};
 return open?<div className="fixed inset-0 z-[95] bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-5" onClick={close}><div className="w-full max-w-2xl max-h-[94vh] overflow-y-auto rounded-3xl bg-slate-100 shadow-2xl" onClick={e=>e.stopPropagation()}>
  <div className="sticky top-0 z-10 bg-white border-b border-slate-200 p-5 flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-emerald-700">SERVIYA • PROTECCIÓN</p><h2 className="text-2xl font-black text-slate-900 mt-1">Garantía SERVIYA</h2><p className="text-xs text-slate-500 mt-1">Contrato emitido → aceptación electrónica → garantía → certificado → vencimiento.</p></div><button onClick={close} className="p-2 rounded-xl bg-slate-100"><X className="w-5 h-5"/></button></div>
  <div className="p-4 sm:p-5 space-y-4">{loading&&<div className="bg-white rounded-2xl p-7 text-center text-sm text-slate-500">Cargando garantía…</div>}{error&&<div className="rounded-2xl border border-red-200 bg-red-50 text-red-800 p-4 text-sm font-semibold flex gap-2"><AlertTriangle className="w-5 h-5 shrink-0"/>{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 text-emerald-800 p-4 text-sm font-bold flex gap-2"><CheckCircle2 className="w-5 h-5 shrink-0"/>{message}</div>}{data&&<>
   <section className={`rounded-2xl border p-5 ${data.warranty.expired?'border-slate-300 bg-white':'border-emerald-200 bg-emerald-50'}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-white flex items-center justify-center"><ShieldCheck className="w-7 h-7 text-emerald-600"/></div><div><p className="text-[10px] uppercase tracking-widest font-black text-emerald-700">Certificado de garantía</p><h3 className="font-black text-lg text-slate-900">${data.warranty.certificate_ref||'GAR-SRV'}</h3></div></div><span className="px-3 py-1.5 rounded-xl bg-white text-xs font-black text-emerald-700">${data.warranty.status}</span></div><div className="grid grid-cols-2 gap-3 mt-5"><div className="bg-white rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-400">Cobertura</p><p className="text-xl font-black">${data.warranty.coverage_days} días</p></div><div className="bg-white rounded-xl p-3"><p className="text-[10px] uppercase font-bold text-slate-400">Vence</p><p className="text-sm font-black">${fmt(data.warranty.expires_at)}</p></div></div><div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-slate-700"><p><b>Contrato:</b> ${contractNumber||'—'}</p><p><b>Servicio:</b> ${data.warranty.service_title||'—'}</p><p><b>Cliente:</b> ${data.warranty.client_name||'—'}</p><p><b>Trabajador:</b> ${data.warranty.worker_name||'—'}</p><p><b>Activada:</b> ${fmt(data.warranty.activated_at)}</p><p><b>Monto:</b> RD$ ${Number(data.warranty.amount_rd||0).toLocaleString('es-DO',{minimumFractionDigits:2})}</p></div><button onClick={printCertificate} className="mt-4 w-full rounded-xl border border-slate-300 bg-white py-3 text-xs font-black text-slate-800"><Printer className="inline w-4 h-4 mr-1"/>Imprimir / guardar certificado</button></section>
   <section className="bg-white rounded-2xl border border-slate-200 p-5"><h3 className="font-black text-slate-900">Qué cubre</h3><ul className="mt-2 text-xs text-slate-600 space-y-2 list-disc pl-5"><li>Problemas directamente relacionados con el trabajo realizado.</li><li>Correcciones cuando el resultado no corresponde con lo acordado.</li><li>Una revisita para evaluar y corregir el problema cubierto.</li><li>Seguimiento e historial dentro de SERVIYA.</li></ul><h3 className="font-black text-slate-900 mt-5">Qué no cubre</h3><ul className="mt-2 text-xs text-slate-600 space-y-2 list-disc pl-5"><li>Mal uso, accidentes, terceros o modificaciones posteriores.</li><li>Trabajos adicionales no incluidos en el acuerdo.</li><li>Desgaste normal o problemas ajenos al servicio certificado.</li></ul></section>
   {isClient&&!data.warranty.expired&&<section className="bg-white rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2"><RefreshCw className="w-5 h-5 text-blue-600"/><h3 className="font-black">Solicitar revisita</h3></div><p className="text-xs text-slate-500 mt-1">La solicitud la inicia el cliente mientras la garantía esté vigente.</p><input value={issue} onChange={e=>setIssue(e.target.value)} placeholder="Problema a revisar" className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Explica qué ocurrió (mínimo 10 caracteres)" rows={4} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/><button disabled={busy} onClick={request} className="mt-3 w-full rounded-xl bg-blue-600 text-white py-3 text-sm font-black disabled:opacity-50">{busy?'Registrando…':'Solicitar revisita'}</button></section>}
   {!isClient&&!data.warranty.expired&&<section className="bg-indigo-50 rounded-2xl border border-indigo-200 p-5"><div className="flex items-center gap-2"><Clock3 className="w-5 h-5 text-indigo-600"/><h3 className="font-black text-slate-900">Atención de revisitas</h3></div><p className="text-xs text-slate-600 mt-2">Las solicitudes de revisita las inicia el cliente. Cuando aparezca una solicitud, podrás programarla, iniciarla, registrar la corrección, confirmar la solución o escalarla a Administración desde Historial y seguimiento.</p></section>}
   <section className="bg-white rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2"><Clock3 className="w-5 h-5 text-indigo-600"/><h3 className="font-black">Historial y seguimiento</h3></div>{!data.revisits.length?<p className="text-xs text-slate-500 mt-3">No hay revisitas registradas.</p>:<div className="mt-3 space-y-3">{data.revisits.map(r=><article key={r.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-sm">{r.issue}</p><p className="text-[11px] text-slate-500 mt-1">Solicitada: {fmt(r.created_at)}</p></div><span className="text-[10px] font-black px-2 py-1 rounded-lg bg-white">{labels[r.status]||r.status}</span></div><p className="text-xs text-slate-600 mt-2">{r.description}</p>{r.scheduled_at&&<p className="text-xs text-blue-700 font-bold mt-2"><CalendarDays className="inline w-3.5 h-3.5 mr-1"/>{fmt(r.scheduled_at)}</p>}{r.resolution_notes&&<p className="text-xs bg-white rounded-xl p-3 mt-2"><b>Resolución:</b> {r.resolution_notes}</p>}
    {r.status==='SOLICITADA'&&<div className="mt-3 flex flex-wrap gap-2"><input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)} className="flex-1 min-w-[180px] rounded-xl border border-slate-200 p-2.5 text-xs"/><button disabled={busy||!schedule} onClick={()=>action(`${r.id}/schedule`,{scheduled_at:new Date(schedule).toISOString()},'Revisita programada.')} className="rounded-xl bg-indigo-600 text-white px-3 py-2 text-xs font-black">Programar</button></div>}
    {r.status==='PROGRAMADA'&&<button disabled={busy} onClick={()=>action(`${r.id}/start`,{},'Revisita iniciada.')} className="mt-3 rounded-xl bg-amber-500 text-white px-3 py-2 text-xs font-black"><PlayCircle className="inline w-4 h-4 mr-1"/>Iniciar</button>}
    {r.status==='CORRECCION_EN_PROCESO'&&<button disabled={busy} onClick={()=>{const notes=window.prompt('Describe la corrección realizada:','Corrección realizada conforme al servicio acordado.');if(notes&&notes.trim().length>=5)void action(`${r.id}/complete`,{notes:notes.trim()},'Corrección registrada.');}} className="mt-3 rounded-xl bg-emerald-600 text-white px-3 py-2 text-xs font-black">Registrar corrección</button>}
    {r.status==='CORRECCION_REALIZADA'&&<button disabled={busy} onClick={()=>action(`${r.id}/confirm`,{},'Solución confirmada y revisita cerrada.')} className="mt-3 rounded-xl bg-emerald-600 text-white px-3 py-2 text-xs font-black"><CheckCircle2 className="inline w-4 h-4 mr-1"/>Confirmar solución</button>}
    {['SOLICITADA','PROGRAMADA','CORRECCION_EN_PROCESO','CORRECCION_REALIZADA'].includes(r.status)&&<button disabled={busy} onClick={()=>{if(window.confirm('¿Escalar esta revisita a Administración SERVIYA?'))void action(`${r.id}/escalate`,{},'Revisita escalada a Administración.');}} className="mt-3 ml-2 rounded-xl border border-red-200 bg-red-50 text-red-700 px-3 py-2 text-xs font-black"><AlertTriangle className="inline w-4 h-4 mr-1"/>Escalar</button>}
   </article>)}</div>}</section>
  </>}
 </div></div></div>:null;
};
