import React, { useEffect, useMemo, useState } from 'react';
import { Search, MapPin, Star, ShieldCheck, MessageSquare } from 'lucide-react';
import { api } from '../services/api';

interface Worker { id:string; first_name:string; last_name:string; province?:string; municipality?:string; rating?:number; jobs_completed?:number; is_verified?:boolean; avatar_url?:string; profession?:string; hourly_rate_rd?:number; bio?:string; availability?:string; }
interface Props { onOpenChat?: (serviceId:string, receiverId:string)=>void; }

export const WorkersView: React.FC<Props> = ({ onOpenChat }) => {
 const [workers,setWorkers]=useState<Worker[]>([]); const [query,setQuery]=useState(''); const [province,setProvince]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{try{const d=await api.get<{workers:Worker[]}>('/users/workers');if(alive)setWorkers(d?.workers||[]);}catch{if(alive)setWorkers([]);}finally{if(alive)setLoading(false);}})();return()=>{alive=false}},[]);
 const filtered=useMemo(()=>workers.filter(w=>{const q=query.toLowerCase().trim(); if(q&&!`${w.first_name} ${w.last_name} ${w.profession||''} ${w.bio||''}`.toLowerCase().includes(q))return false;if(province&&w.province!==province)return false;return true}),[workers,query,province]);
 const provinces=[...new Set(workers.map(w=>w.province).filter(Boolean))] as string[];
 return <section className="space-y-5 pb-12">
  <div className="rounded-3xl bg-slate-900 text-white p-6 sm:p-8"><p className="text-blue-300 text-xs font-black uppercase tracking-widest">SERVIYA • PROFESIONALES</p><h1 className="text-2xl sm:text-3xl font-black mt-1">Encuentra trabajadores y técnicos</h1><p className="text-sm text-slate-300 mt-2">Compara perfiles, experiencia, valoración y verificación antes de contratar.</p></div>
  <div className="bg-white rounded-2xl border border-slate-200 p-4 grid grid-cols-1 md:grid-cols-2 gap-3"><label className="flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5"><Search className="w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre o especialidad..." className="w-full bg-transparent outline-none text-sm"/></label><select value={province} onChange={e=>setProvince(e.target.value)} className="bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5 text-sm outline-none"><option value="">Todas las provincias</option>{provinces.map(p=><option key={p} value={p}>{p}</option>)}</select></div>
  {loading?<div className="bg-white rounded-2xl border p-10 text-center text-sm text-slate-500">Cargando profesionales...</div>:filtered.length===0?<div className="bg-white rounded-2xl border p-10 text-center text-sm text-slate-500">No hay profesionales que coincidan con tu búsqueda.</div>:<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map(w=><article key={w.id} className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm flex flex-col"><div className="flex gap-3"><img src={w.avatar_url||'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150'} className="w-14 h-14 rounded-full object-cover border-2 border-blue-100"/><div className="min-w-0"><h2 className="font-black text-slate-900 truncate">{w.first_name} {w.last_name}</h2><p className="text-xs font-semibold text-blue-700 mt-0.5">{w.profession||'Técnico Especializado'}</p><div className="flex flex-wrap gap-2 mt-1 text-[11px] text-slate-500"><span className="inline-flex items-center gap-1"><Star className="w-3 h-3 fill-current"/> {Number(w.rating||0).toFixed(1)}</span><span>{w.jobs_completed||0} trabajos</span>{w.is_verified&&<span className="inline-flex items-center gap-1 text-emerald-700 font-bold"><ShieldCheck className="w-3 h-3"/> Verificado</span>}</div></div></div><p className="text-xs text-slate-600 mt-4 line-clamp-3 flex-1">{w.bio||'Profesional disponible para realizar servicios mediante SERVIYA.'}</p><div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between gap-2"><span className="text-xs font-black text-slate-900">Desde RD$ {Number(w.hourly_rate_rd||0).toLocaleString()}/hora</span>{onOpenChat&&<button onClick={()=>onOpenChat('',w.id)} className="inline-flex items-center gap-1 bg-blue-50 text-blue-700 border border-blue-200 px-3 py-2 rounded-xl text-xs font-bold"><MessageSquare className="w-3.5 h-3.5"/>Mensaje</button>}</div>{w.municipality&&<div className="mt-2 text-[11px] text-slate-400 flex items-center gap-1"><MapPin className="w-3 h-3"/>{w.municipality}, {w.province}</div>}</article>)}</div>}
 </section>;
};
