import React, { useEffect, useState } from 'react';
import { Camera, CheckCircle, MessageSquare, ShieldCheck, FileCheck2, Play, CircleCheckBig, LockKeyhole } from 'lucide-react';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { Service } from '../types';
import { WorkPhotosModal } from './WorkPhotosModal';
import { NegotiationPanel } from './NegotiationPanel';
import { WorkStatusPanel } from './WorkStatusPanel';

interface Props { service: Service; onRefresh: () => void; onOpenChat: (serviceId: string, receiverId: string) => void; embedded?: boolean; showNegotiation?: boolean; }
export const WorkFlowActions: React.FC<Props> = ({ service, onRefresh, onOpenChat, embedded=false, showNegotiation=true }) => {
  const { user } = useAuth();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [showPhotos, setShowPhotos] = useState(false); const [completion, setCompletion] = useState<any>(null); const [summary, setSummary] = useState(''); const [warranty, setWarranty] = useState<any>(null);
  const isWorker = user?.id === service.worker_id; const isClient = user?.id === service.client_id;
  const load = async () => { try { setCompletion(await api.get(`/completion/${service.id}`)); } catch { setCompletion(null); } try { const w:any = await api.get(`/completion/${service.id}/warranty`); setWarranty(w?.warranty || null); } catch { setWarranty(null); } };
  useEffect(() => { if(user) load(); }, [service.id, service.status, user?.id]);
  const executeWork = async () => { if (!window.confirm('¿Confirmas que vas a iniciar oficialmente este trabajo? La Custodia permanecerá protegida.')) return; setBusy(true); setError(''); setSuccess(''); try { await api.post(`/completion/${service.id}/execute`); setSuccess('Trabajo iniciado oficialmente. La Custodia permanece protegida.'); await load(); onRefresh(); } catch(e:any) { setError(e?.message || 'No se pudo iniciar el trabajo.'); } finally { setBusy(false); } };
  const submitCompletion = async () => { if(!summary.trim()){setError('Escribe un resumen de lo realizado antes de marcar el trabajo como terminado.');return;} setBusy(true);setError('');setSuccess(''); try{await api.post(`/completion/${service.id}/submit`,{summary:summary.trim()});setSuccess('Trabajo marcado como terminado y enviado a revisión. El cliente debe comprobar la evidencia y aprobar la liberación.');await load();onRefresh();}catch(e:any){setError(e.message||'No se pudo marcar el trabajo como terminado.')}finally{setBusy(false)} };
  const approveCompletion = async () => { if(!window.confirm('¿Confirmas que revisaste el trabajo y estás conforme? Los fondos seguirán protegidos hasta que Administración procese la liberación.')) return; setBusy(true); setError(''); setSuccess(''); try { await api.post(`/completion/${service.id}/approve`); setSuccess('Conformidad registrada. La solicitud de liberación fue enviada a Administración.'); await load(); onRefresh(); } catch(e:any) { setError(e.message || 'No se pudo registrar la aprobación.'); } finally { setBusy(false); } };
  if(!user||!service.worker_id||(!isWorker&&!isClient)) return null;
  const selected=service.status==='TRABAJADOR_SELECCIONADO'; const inProgress=service.status==='EN_PROGRESO'; const completed=service.status==='COMPLETADA';
  return <>
    <div className={embedded ? 'w-full' : 'fixed bottom-20 md:bottom-6 left-1/2 -translate-x-1/2 z-[45] w-[calc(100%-1.5rem)] max-w-2xl'}><div className="bg-white border border-slate-200 shadow-xl rounded-2xl p-3">
      {error&&<div className="mb-2 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs font-semibold p-2.5">{error}</div>}{success&&<div className="mb-2 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold p-2.5">{success}</div>}
      <div className="flex items-start justify-between gap-3 mb-2"><div><p className="text-[10px] uppercase tracking-widest font-black text-blue-600">Continuidad del trabajo</p><p className="text-sm font-black text-slate-900">{service.status.replaceAll('_',' ')}</p></div><div className="hidden sm:block text-[10px] text-slate-500 text-right">Selección → negociación → custodia → progreso → evidencia → conformidad → finalización</div></div>
      <WorkStatusPanel service={service}/>
      {selected&&showNegotiation&&<div className="space-y-3 mt-3"><NegotiationPanel serviceId={service.id} clientId={service.client_id} workerId={service.worker_id} budget={service.price_rd} title={service.title} onRefresh={onRefresh} onOpenChat={onOpenChat}/>{isWorker&&<button onClick={executeWork} disabled={busy} className="w-full inline-flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-black text-sm px-4 py-3 rounded-xl disabled:opacity-50"><Play className="w-4 h-4"/>{busy?'Iniciando…':'Iniciar trabajo oficialmente'}</button>}</div>}
      {selected&&isWorker&&!showNegotiation&&<button onClick={executeWork} disabled={busy} className="w-full mt-3 inline-flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-black text-sm px-4 py-3 rounded-xl disabled:opacity-50"><Play className="w-4 h-4"/>{busy?'Iniciando…':'Iniciar trabajo oficialmente'}</button>}
      {inProgress&&<div className="space-y-3 mt-3"><div className="rounded-xl bg-blue-50 border border-blue-200 p-3 text-xs text-blue-900"><b>Custodia retenida.</b> El pago está protegido. {isWorker?'Actualiza el estado, comparte evidencia y al terminar marca el trabajo como terminado.':'Sigue el avance, revisa la evidencia y confirma cuando el trabajo esté terminado.'}</div>{isWorker&&!completion?.completion_submitted&&<div className="rounded-2xl border-2 border-emerald-200 bg-emerald-50 p-3 space-y-2"><p className="text-xs font-black text-emerald-950">¿Terminaste el trabajo?</p><p className="text-[11px] text-emerald-800">Sube la evidencia y escribe el resumen antes de enviarlo al cliente para revisión.</p><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Resumen del trabajo realizado..." className="w-full border border-emerald-300 bg-white rounded-xl p-2.5 text-xs min-h-20"/><div className="flex flex-col sm:flex-row gap-2"><button onClick={()=>setShowPhotos(true)} disabled={busy} className="flex-1 inline-flex items-center justify-center gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs px-3 py-3 rounded-xl disabled:opacity-50"><Camera className="w-4 h-4"/>Subir fotos del trabajo</button><button onClick={submitCompletion} disabled={busy||!summary.trim()} className="flex-1 inline-flex items-center justify-center gap-1.5 bg-slate-900 hover:bg-slate-800 text-white font-black text-xs px-3 py-3 rounded-xl disabled:opacity-50"><FileCheck2 className="w-4 h-4"/>{busy?'Enviando…':'Marcar trabajo como terminado'}</button></div></div>}{isClient&&completion?.completion_submitted&&completion?.status!=='PENDIENTE_APROBACION'&&<button onClick={approveCompletion} disabled={busy} className="w-full inline-flex items-center justify-center gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs px-3 py-3 rounded-xl disabled:opacity-50"><CheckCircle className="w-4 h-4"/>Confirmar trabajo y solicitar liberación</button>}{completion?.completion_submitted&&<div className="rounded-xl bg-amber-50 border border-amber-200 p-3 text-xs text-amber-900"><b>Trabajo enviado a revisión.</b> {isClient?(completion?.status==='PENDIENTE_APROBACION'?'Tu aprobación ya fue registrada. Administración debe liberar los fondos.':'Revisa las fotos y, cuando estés conforme, confirma el trabajo.'):'Esperando la conformidad del cliente y la liberación de fondos.'}</div>}<button onClick={()=>onOpenChat(service.id,isWorker?service.client_id:service.worker_id!)} className="w-full inline-flex items-center justify-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs px-3 py-3 rounded-xl"><MessageSquare className="w-4 h-4"/>Mensajes</button></div>}
      {completed&&<div className="rounded-2xl bg-emerald-50 border-2 border-emerald-300 p-4 sm:p-5 space-y-3 mt-3"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-full bg-emerald-600 text-white flex items-center justify-center"><CircleCheckBig className="w-6 h-6"/></div><div><p className="text-[10px] uppercase tracking-widest font-black text-emerald-700">SERVIYA • ESTADO FINAL</p><h3 className="text-lg sm:text-xl font-black text-emerald-950">PROCESO FINALIZADO</h3><p className="text-xs text-emerald-800">El trabajo fue aprobado y Administración liberó los fondos.</p></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-2"><div className="rounded-xl bg-white/80 border border-emerald-200 p-3"><p className="text-[10px] uppercase font-black text-slate-400">Cliente</p><p className="text-xs font-bold text-slate-800 mt-1">Conformidad registrada</p></div><div className="rounded-xl bg-white/80 border border-emerald-200 p-3"><p className="text-[10px] uppercase font-black text-slate-400">Trabajador</p><p className="text-xs font-bold text-slate-800 mt-1">Pago liberado a su billetera</p></div><div className="rounded-xl bg-white/80 border border-emerald-200 p-3"><p className="text-[10px] uppercase font-black text-slate-400">Custodia</p><p className="text-xs font-bold text-slate-800 mt-1">Fondos liberados</p></div></div><div className="rounded-xl bg-white border border-emerald-200 p-3 text-xs text-emerald-900 flex items-center gap-2"><LockKeyhole className="w-4 h-4 shrink-0"/><span><b>Proceso cerrado.</b> Esta confirmación la pueden ver tanto el Cliente como el Trabajador/Técnico.</span></div></div>}
      {warranty&&<div className="mt-2 rounded-xl bg-emerald-50 border border-emerald-200 p-3 text-xs text-emerald-900 flex items-start gap-2"><ShieldCheck className="w-4 h-4 shrink-0"/><div><b>Garantía SERVIYA activa por {warranty.coverage_days} días.</b><br/>Certificado: {warranty.certificate_ref} • Vence: {new Date(warranty.expires_at).toLocaleDateString()}</div></div>}
    </div></div>
    {showPhotos&&isWorker&&<WorkPhotosModal service={service} onClose={()=>setShowPhotos(false)} onRefresh={onRefresh}/>} 
  </>;
};