export type UserRole = 'CLIENTE' | 'TRABAJADOR' | 'ADMIN';
export type ServiceStatus = 'PUBLICADA' | 'RECIBIENDO_POSTULACIONES' | 'TRABAJADOR_SELECCIONADO' | 'EN_PROGRESO' | 'COMPLETADA' | 'CANCELADA' | 'EN_DISPUTA';
export type ApplicationStatus = 'PENDIENTE' | 'SELECCIONADO' | 'RECHAZADO';
export type VerificationStatus = 'SIN_VERIFICAR' | 'PENDIENTE' | 'VERIFICADO' | 'RECHAZADO';
export type DisputeStatus = 'ABIERTA' | 'EN_REVISION' | 'RESUELTA' | 'CERRADA';
export type WithdrawalStatus = 'PENDIENTE' | 'PROCESANDO' | 'COMPLETADO' | 'RECHAZADO';
export type TransactionType = 'depósito' | 'pago' | 'comisión' | 'reembolso' | 'liberación' | 'retiro' | 'ajuste';
export interface User { id:string; first_name:string; last_name:string; full_name?:string; email:string; phone:string; cedula?:string; role:UserRole; activeRole:'CLIENTE'|'TRABAJADOR'; province:string; municipality:string; bio?:string; avatar_url?:string; created_at:string; rating:number; jobs_completed:number; is_verified:boolean; worker_profile?:WorkerProfile; }
export interface WorkerProfile { id?:string; user_id?:string; profession:string; bio?:string; specialties?:string[]; experience_years?:number; hourly_rate_rd?:number; availability?:'TIEMPO_COMPLETO'|'MEDIO_TIEMPO'|'FINES_DE_SEMANA'|'POR_HORAS'; portfolio_images?:string[]; certifications?:string[]; verification_status?:VerificationStatus; }
export interface Category { id:string; name:string; slug:string; icon:string; description:string; subcategories:string[]; }
export interface Service { id:string; title:string; description:string; category_id:string; category_name:string; subcategory?:string; price_rd:number; negotiated_price_rd?:number|null; negotiation_status?:'PENDIENTE'|'PENDIENTE_ACEPTACION'|'ACORDADO'; province:string; municipality:string; address_approx:string; service_date:string; service_time:string; estimated_duration:string; images:string[]; completion_photos?:string[]; requirements:string[]; payment_type:'EFECTIVO'|'CUSTODIA_SERVIYA'; status:ServiceStatus; client_id:string; client_name:string; client_avatar?:string; client_rating:number; worker_id?:string; worker_name?:string; completion_submitted?:boolean; completion_summary?:string; completion_submitted_at?:string; created_at:string; applications_count:number; }
export interface Application { id:string; service_id:string; worker_id:string; worker_name:string; worker_avatar?:string; worker_profession?:string; worker_rating:number; worker_is_verified:boolean; message:string; offered_price_rd:number; availability_note:string; status:ApplicationStatus; created_at:string; }
export interface Contract { id:string; service_id:string; service_title:string; client_id:string; worker_id:string; agreed_price_rd:number; commission_rd:number; status:ServiceStatus; escrow_id?:string; started_at:string; completed_at?:string; }
export interface Wallet { id:string; user_id:string; available_rd:number; escrow_rd:number; pending_rd:number; total_received_rd:number; total_spent_rd:number; updated_at:string; }
export interface WalletTransaction { id:string; wallet_id:string; user_id:string; type:TransactionType; amount_rd:number; description:string; reference:string; status:'EXITOSO'|'PENDIENTE'|'FALLIDO'; created_at:string; }
export interface Payment { id:string; service_id:string; payer_id:string; amount_rd:number; commission_rd:number; net_amount_rd:number; payment_method:'TARJETA'|'TRANSFERENCIA_BANCO'|'PAYPAL'|'SALDO_BILLETERA'; status:'COMPLETADO'|'PENDIENTE'|'REEMBOLSADO'; created_at:string; }
export interface Escrow { id:string; service_id:string; client_id:string; worker_id:string; total_amount_rd:number; commission_rate_percent:number; commission_amount_rd:number; worker_payout_rd:number; status:'RETENIDO'|'LIBERADO'|'REEMBOLSADO'|'EN_DISPUTA'; release_otp?:string; otp_verified?:boolean; created_at:string; released_at?:string; }
export interface Review { id:string; service_id:string; reviewer_id:string; reviewer_name:string; reviewer_role:'CLIENTE'|'TRABAJADOR'; target_user_id:string; rating:number; comment:string; created_at:string; }
export interface Notification { id:string; user_id:string; title:string; message:string; type:string; read:boolean; related_entity_id?:string; created_at:string; }
export interface Message { id:string; service_id:string; sender_id:string; sender_name:string; receiver_id:string; content:string; created_at:string; }
export interface Dispute { id:string; service_id:string; service_title:string; opened_by_user_id:string; opened_by_name:string; against_user_id:string; against_name:string; reason:string; description:string; evidence_urls:string[]; status:DisputeStatus; resolution_notes?:string; created_at:string; }
export interface VerificationDocument { id:string; user_id:string; document_type:'CEDULA_FRONTAL'|'CEDULA_TRASERA'|'CERTIFICACION_NO_ANTECEDENTES'|'TITULO_TECNICO'; document_url:string; status:VerificationStatus; notes?:string; submitted_at:string; }
export interface Withdrawal { id:string; user_id:string; user_name:string; amount_rd:number; bank_name:string; account_type:'AHORROS'|'CORRIENTE'; account_number:string; account_holder_name:string; account_holder_cedula:string; status:WithdrawalStatus; requested_at:string; processed_at?:string; }
export interface PlatformSetting { platform_commission_percent:number; min_withdrawal_rd:number; min_service_price_rd:number; support_phone:string; support_email:string; }
export interface AuditLog { id:string; user_id?:string; action:string; details:string; ip_address?:string; created_at:string; }
